Artem Yasevich, Stage4
polis-vk/2022-nosql-lsm pull request #100
Opened 2022-03-27 15:36 UTC by a-yasevich

2022-03-28 09:57 UTC, incubos requested changes
Не проходят новые тесты:
```
> Task :test

CompactionTest > compactAndAdd(Dao) > ru.mail.polis.CompactionTest.compactAndAdd(Dao)[1] FAILED
    org.opentest4j.AssertionFailedError at CompactionTest.java:123

82 tests completed, 1 failed
```

2022-03-30 17:13 UTC, incubos requested changes

2022-04-01 10:23 UTC, incubos commented
Нужно зарезолвить конфликты.

2022-04-01 10:28 UTC, incubos requested changes

2022-04-01 10:28 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/StringDao.java
> +    public void compact() throws IOException {
Применимы все замечания об отказоустойчивости от @Artyomcool с последнего занятия.

2022-04-06 11:27 UTC, incubos requested changes
Есть ряд замечаний к корректности/отказоустойчивости.

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +        retainOnlyCompactedFile(daoFilesCount - 1);
В случае, если существует только data **или** meta, поведение будет некорректным, верно?

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +    private void savaData(Iterator<BaseEntry<String>> dataIterator,
`saveData()`?

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
>          try (DataOutputStream dataStream = new DataOutputStream(new BufferedOutputStream(
Если БД упала во время записи файлов, конструктор подхватит недозаписанные файлы, верно?

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/StringDao.java
> +    public void compact() throws IOException {
Не совсем. См. комментарии по коду.

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +        retainOnlyCompactedFile(filesBefore);
Если произошёл сбой и мы не все файлы успели удалить, будет работать некорректно.

2022-04-06 11:27 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +    void compact(Iterator<BaseEntry<String>> mergeIterator) throws IOException {
Представьте, что сбой может быть на любой строчке и внутри всех вызываемых методов. Recovery в таком случае должно работать корректно: либо мы игнорируем результаты прерванного compaction (и, возможно, подчищаем их), либо пытаемся разобраться в том, что произошло, и довести процесс до конца (гораздо более сложный вариант).

2022-04-06 19:35 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +    private void savaData(Iterator<BaseEntry<String>> dataIterator,
saveData().

2022-04-06 19:36 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +        retainOnlyCompactedFile(daoFilesCount - 1);
Верно, исправил

2022-04-06 19:37 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
>          try (DataOutputStream dataStream = new DataOutputStream(new BufferedOutputStream(
Верно, исправил

2022-04-10 11:48 UTC, incubos approved these changes
До конца корректное решение сделать не удалось, но попытка хорошая. 10 баллов.

2022-04-10 11:48 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +            retainOnlyCompactedFiles();
Если во время compact мы успели переименовать только data-файл, а затем упали, то здесь мы его сотрём, верно?

2022-04-10 11:48 UTC, incubos commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +            Files.move(compactedMeta, pathToMeta(0));
И останется только этот файл, а потом ничего не откроется, потому что нет пары data+meta.

2022-04-10 21:06 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +            retainOnlyCompactedFiles();
Нет. Если произошёл такой сценарий, то значит, что произошло удаление всех файлов кроме compacted, тогда в директории будет ровно два файла и удалять мы ничего не будем

2022-04-10 21:15 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/Storage.java
> +            Files.move(compactedMeta, pathToMeta(0));
Если этот коммментарий - продолжение предыдущего, то останутся оба файла.

2022-04-11 15:47 UTC, merged