Stage 4 | Ponomarev Stepan
polis-vk/2022-nosql-lsm pull request #101
Opened 2022-03-29 18:55 UTC by step-ponomarev

2022-03-29 18:57 UTC, step-ponomarev commented
ТАЙМАУТ

2022-04-09 14:24 UTC, atimofeyev requested changes

2022-04-09 14:24 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                final Iterator<Path> filesToRemove = ssTableFiles.sorted(Comparator.reverseOrder()).iterator();
а зачем тут в сортированном виде проходимся?

2022-04-09 14:24 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                    .filter(f -> !f.getFileName().toString().contains(String.valueOf(timestamp)))
опасный механизм сравнения, в теории более маленькое число может быть подстрокой в более большом

2022-04-09 14:24 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final SortedMap<MemorySegment, TimestampEntry> data = new ConcurrentSkipListMap<>(Utils.COMPARATOR);
а что будет если в процессе компакшена мы что-то попробуем положить в ДАО?

2022-04-09 14:24 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        ssTables.clear();
их наверное стоит как-то корректно закрыть?

2022-04-10 14:50 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final SortedMap<MemorySegment, TimestampEntry> data = new ConcurrentSkipListMap<>(Utils.COMPARATOR);
Данные лягут в стору и со следующем флашем улетят в хранилище.

2022-04-10 15:11 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                final Iterator<Path> filesToRemove = ssTableFiles.sorted(Comparator.reverseOrder()).iterator();
Чтобы удалить сначала детей, а потом саму папочку.

2022-04-10 15:12 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                    .filter(f -> !f.getFileName().toString().contains(String.valueOf(timestamp)))
Да подправил

2022-04-10 15:12 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        ssTables.clear();
ага, закрываю

2022-04-13 21:19 UTC, atimofeyev requested changes
что-то фейлятся проверки, надо бы поправить это

2022-04-13 21:19 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final SortedMap<MemorySegment, TimestampEntry> data = new ConcurrentSkipListMap<>(Utils.COMPARATOR);
на самом деле запись просто потеряется, если ее попробуют вставить уже после того как мы пройдемся и соберем все данные. Так как по текущей логике мы все компактим и закрываем стор, и все что инмемори просто теряется. Но на текущем этапе мы считаем что это происходит пока в одном потоке так что не страшно

2022-04-13 21:49 UTC, atimofeyev requested changes

2022-04-13 21:49 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                flush(memTable, timestamp)
здесь мы создадим еще один файл из данных которые скомпактились из мемтейбла? по условию задачи мы хотели чтобы данные из мемтейбла скомпактились в один файл и не создавали второго

2022-04-16 15:33 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +                flush(memTable, timestamp)
Ага, поправил.

2022-04-16 15:34 UTC, step-ponomarev commented
Тест по таймауту отпадает, локально не отпадает. Я с этим ничего не могу сделать, разве что тригеррить тест пока он все-таки не пройдет...  :/

2022-04-24 18:58 UTC, atimofeyev requested changes

2022-04-24 18:58 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +        final long timestamp = System.currentTimeMillis();
лучше брать nanoTime()

2022-04-24 18:58 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        //TODO: Нужен ли конкурентный флаш?
на этом этапе не нужен

2022-04-24 18:58 UTC, atimofeyev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        ssTables.removeIf(ssTable -> ssTable.getCreatedTime() < timestamp);
здесь опасная ситуация, особенно с милисекундами, если мы удаляем файлы на основе временной составляющей, то надо гарантировать монотонно возрастающий счетчик, просто брать время не гарантирует этого

2022-04-24 18:59 UTC, atimofeyev approved these changes

2022-04-24 19:03 UTC, merged