Lutsenko Dmitrii Stage4
polis-vk/2022-nosql-lsm pull request #102
Opened 2022-03-30 12:09 UTC by LutsenkoDm

2022-03-30 17:21 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +    public void compact() throws IOException {
Существуют случаи, когда вообще ничего делать не нужно. Учтёте их?

2022-03-31 09:15 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +    public void compact() throws IOException {
Добавил обработку 2 таких случаев

2022-04-01 10:28 UTC, incubos commented
Нужно зарезолвить конфликты.

2022-04-01 10:29 UTC, incubos requested changes

2022-04-01 10:29 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +    public void compact() throws IOException {
Применимы все замечания об отказоустойчивости от @Artyomcool с последнего занятия.

2022-04-02 11:08 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +    public void compact() throws IOException {
Замечания исправил, конфликты решил

2022-04-06 11:50 UTC, incubos requested changes
Есть ряд замечаний к корректности/отказоустойчивости.

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            lock.writeLock().unlock();
Если вылетит не `IOException`, мы останемся залоченными навсегда.

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +        // При ошибке выше чтение будет из корректного compact-файла, который останется самым приоритетным файлом
В compact-файл не пишутся могилы, что является проблемой в данном подходе. Представьте ситуацию, когда в последнем файле был некий ключ, могила для него была в памяти, мы сформировали compact-файл без ключа (и могилы), начали удалять старые файлы, но не удалили последний файл (перед compact-файлом) из-за сбоя. Переоткрываем БД -- теперь могилы нигде нет и ключ из последнего файла воскресает.

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            bufferedFileWriter.flush();
Зачем это?

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            Files.move(tempCompactionFilePath, lastFilePath);
Переименование файла до его закрытие хоть и работает в Linux, но здесь выглядит неожиданно.

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            lock.writeLock().unlock();
Лучше сделать явный отдельный `try ... finally`.

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            while (allEntriesIterator.hasNext()) {
Почему мы формируем новый файл под локом?

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            for (Map.Entry<Path, FileInputStream> filesMapEntry : filesMap.entrySet()) {
Если номера файлов содержат несколько чисел разной длины (а это допустимо), мы будем удалять файлы не по порядку (потому что сортировка на основе `Path`) и станут возможны интересные спецэффекты, если не все файлы удастся удалить -- догадываетесь какие?

2022-04-06 11:50 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +        // Если compact-файл успешно создан, то независимо от успеха удаления старых файлов данные в памяти очищаются
"независимо от успеха удаления" -- эта гарантия является оптимизацией лишнего flush в случае сбоя во время compact? К сбоям нужно готовиться, но это относительно редкие события, поэтому в данном случае оптимизация выглядит лишней и лишь усложняет код и его понимание.

2022-04-06 15:36 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            bufferedFileWriter.flush();
Убрал

2022-04-06 15:37 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            Files.move(tempCompactionFilePath, lastFilePath);
Вынес в место сразу после закрытия файла

2022-04-06 15:38 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            while (allEntriesIterator.hasNext()) {
Лок перенес в место, где уже происходит удаление файлов

2022-04-06 15:41 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +            for (Map.Entry<Path, FileInputStream> filesMapEntry : filesMap.entrySet()) {
Да, догадываюсь, эти спецэффекты будут проявляться уже при количестве файлов более 10, но в данной мапе переопределен Comparator и сортировка идет не на основе Path, а аналогично целочисленной, что позволяет избежать подобных неприятностей

2022-04-06 15:42 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/PersistenceRangeDao.java
> +        // Если compact-файл успешно создан, то независимо от успеха удаления старых файлов данные в памяти очищаются
Очистка памяти теперь происходит только в случае успеха

2022-04-10 12:24 UTC, incubos approved these changes
Теперь выглядит корректно. 18 баллов.

2022-04-11 15:48 UTC, merged