Trofimov Artyom | Stage 4
polis-vk/2022-nosql-lsm pull request #104
Opened 2022-03-30 17:08 UTC by artem24630

2022-04-09 15:04 UTC, atimofeyev requested changes

2022-04-09 17:00 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +    private volatile boolean commit = true;
возможно, не очень удачное название, но у меня commit используется для обозначения того, что изменений не было после последнего flush. Соответственно, когда только создалось InMemoryDao, никаких изменений не могло произойти, поэтому commit = true

2022-04-09 18:20 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
убрал, теперь не потеряются

2022-04-13 21:47 UTC, atimofeyev requested changes

2022-04-13 21:47 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            commit = false;
тут явные проблемы с многопоточностью, но можно это оставить на следующие стейджы

2022-04-13 21:47 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
теперь мы тут можем потерять данные в случае многопоточности, но это я так понимаю на след этапы

Но тут мы запишем новый файл из тех данных что ушли в компакшен, а мы этого не хотели

2022-04-14 11:12 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            commit = false;
да, тут локов не хватает, но с ними пока что тесты не проходят по времени, и поэтому на следующий этап оставлю

2022-04-14 11:14 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
да, на этом этапе в компакшене нужно было брать и то, что в памяти лежит, а на следующем стейдже уже только компакшн по файликам

2022-04-14 11:33 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
и кстати не запишется новый файл, так как commit = true

2022-04-14 20:48 UTC, atimofeyev approved these changes

2022-04-14 20:48 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
ну так после пута станет false

2022-04-14 20:48 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            data.clear();
в общем на следующем этапе это все придется исправлять

2022-04-14 20:49 UTC, atimofeyev reviewed
18 баллов

2022-04-14 22:17 UTC, merged