Alexander Kiselyov, Stage 4
polis-vk/2022-nosql-lsm pull request #107
Opened 2022-03-30 22:30 UTC by AlexanderKiselyov

2022-04-01 10:37 UTC, incubos requested changes

2022-04-01 10:37 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private boolean isCompacted;
Зачем этот флаг?

2022-04-01 10:37 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +    void compact(Iterator<BaseEntry<byte[]>> iterator) throws IOException {
Применимы все замечания об отказоустойчивости от @Artyomcool с последнего занятия.

2022-04-02 14:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private boolean isCompacted;
убрал

2022-04-02 14:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +    void compact(Iterator<BaseEntry<byte[]>> iterator) throws IOException {
исправил

2022-04-06 14:21 UTC, incubos requested changes
Есть серьёзные вопросы к корректности/отказоустойчивости решения.

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.createCompactedFiles(basePath);
Зачем создавать пустые файлы заранее?

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.saveDataAndIndexesCompact(iterator);
Что произойдёт в случае сбоя, когда файлы будут недозаписаны?

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
>      private final List<FileIterator> fileIterators = new ArrayList<>();
Для чего это поле? Почему мы добавляем итераторы на каждый `get()` и удаляем только на `compact()`?

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.deleteAllFiles(ssTables, ssIndexes, filesCount);
Что произойдёт в случае сбоя, когда не все файлы удалятся?

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    public CompactOperations(Map<String, String> fileNames) {
Передавать параметры в `Map` в Java не принято. Тем более, что все значения константные.

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    void createCompactedFiles(Path basePath) throws IOException {
Для чего этот метод?

2022-04-06 14:21 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +        if (compactedIndex != null) {
Если произойдёт сбой и индекс мы не сможем переименовать?

2022-04-07 14:26 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
>      private final List<FileIterator> fileIterators = new ArrayList<>();
Каждый такой итератор у меня отвечает за файл, по которому я итерируюсь. Перед тем, как удалять файлы в методе compact(), я закрываю все такие потоки. Также этот метод фигурирует в методе close() у Dao, чтобы закрыть все открытые потоки, если они еще не были закрыты.

2022-04-07 18:17 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        Map<String, String> fileNames = new HashMap<>();
исправил

2022-04-07 18:19 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
>          filesCount = ssTables.size();
добавил проверку и восстановление ошибок при компакте в методе checkFiles

2022-04-07 18:19 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.createCompactedFiles(basePath);
убрал

2022-04-07 18:20 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.saveDataAndIndexesCompact(iterator);
добавил отслеживание сбоя через переименовывание файлов

2022-04-07 18:20 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        compactOperations.deleteAllFiles(ssTables, ssIndexes, filesCount);
добавил отслеживание сбоя через переименовывание файлов

2022-04-07 18:20 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    public CompactOperations(Map<String, String> fileNames) {
убрал

2022-04-07 18:20 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    void createCompactedFiles(Path basePath) throws IOException {
убрал

2022-04-10 12:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        Map<String, String> fileNames = new HashMap<>();
Значения всегда передаются одни и те же. Почему просто не сослаться на константы, предварительно вынеся их в отдельный класс?

2022-04-10 12:48 UTC, incubos approved these changes
Happy path работает, но отказоустойчивость не доделана. 10 баллов.

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    private final String noSuchFile;
Зачем это поле? Почему не в месте бросания исключения с указанием, какой именно файл не найден?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                    Files.delete(basePath.resolve(fileName + "0" + fileExtension));
Почему эта проверка касается только нулевого файла?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                throw new NoSuchFileException(noSuchFile);
Разве мы не можем удалить файл и продолжить работу, как в случае выше? Зачем это исключение?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileName))
Почему `String.valueOf()`, а не просто `toString()`?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileIndexName))
`toString()`?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileName))
`startsWith()` вместо `contains()`?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileIndexName))
`startsWith()` вместо `contains()`?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +            Files.createFile(compactedFile);
Сам файл не создастся разве?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +            Files.createFile(compactedIndex);
Сам файл не создастся разве?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +        if (compactedFile != null) {
В каком случае может быть `null`? Разве это не свидетельствует об ошибке в коде?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +        if (compactedIndex != null) {
В каком случае может быть `null`? Разве это не свидетельствует об ошибке в коде?

2022-04-10 12:48 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                checkContinueCompactionConflicts(basePath, file, files);
ОК, зачистили остальные файлы, а кто переименует файлы в нулевую таблицу?

2022-04-10 17:13 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +    private final String noSuchFile;
убрал поле

2022-04-10 17:13 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                    Files.delete(basePath.resolve(fileName + "0" + fileExtension));
добавил проверки всех файлов в хранилище

2022-04-10 17:14 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                throw new NoSuchFileException(noSuchFile);
убрал лишнее исключение

2022-04-10 17:14 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileName))
изменил

2022-04-10 17:14 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileIndexName))
изменил

2022-04-10 17:14 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileName))
изменил

2022-04-10 17:14 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                        .filter(f -> String.valueOf(f.getFileName()).contains(fileIndexName))
изменил

2022-04-10 17:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +            Files.createFile(compactedFile);
убрал проверку

2022-04-10 17:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +            Files.createFile(compactedIndex);
убрал проверку

2022-04-10 17:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +        if (compactedFile != null) {
убрал проверку

2022-04-10 17:15 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +        if (compactedIndex != null) {
убрал проверку

2022-04-10 17:16 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/CompactOperations.java
> +                checkContinueCompactionConflicts(basePath, file, files);
добавил методы переименования файлов

2022-04-11 15:50 UTC, merged