Stage 4 tests
polis-vk/2022-nosql-lsm pull request #108
Opened 2022-03-31 10:27 UTC by LutsenkoDm

2022-03-31 15:06 UTC, incubos requested changes
Есть замечания. Не совсем понятно, для чего здесь циклы с кучей итераций.

2022-03-31 15:06 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage4IdempotentTest.java
> +    void closeIdempotentEmpty(Dao<String, Entry<String>> dao) throws IOException {
Зачем во всех методах суффикс `Idempotent`, если это уже в названии класса?

2022-03-31 15:06 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage4IdempotentTest.java
> +public class Stage4IdempotentTest extends BaseTest {
Нужно ли везде проверять 5000 раз?

2022-04-01 10:37 UTC, incubos commented
Исправления принимаются до завтра, чтобы от тестов был толк до дедлайна. Ждать?

2022-04-01 11:13 UTC, LutsenkoDm commented
> Исправления принимаются до завтра, чтобы от тестов был толк до дедлайна. Ждать?

Хотел бы уточнить по поводу исправлений: 
5000 раз для проверки того что повторный close() или compact() приводит потери производительности, подразумевается что если такая потеря будет, то тесты упадут по Timeout. Отличаются только начальные условия: (empty, 1 файл, несколько файлов)
В тестах при этих итерациях compact не должен выполняться так как работа будет всегда с 1 фалом. При одной итерации compact может быть сделан, но потеря производительности при этом не будет обнаружена. 
Для close аналогично.
Где 100 итераций, compact будет каждый раз выполняться, но для 2 файлов, тут тоже хотел дать pressure на производительность, хотя этот тест отличается от других и возможно его стоит убрать?

2022-04-05 17:17 UTC, incubos approved these changes
6 баллов. Спасибо за вклад!

2022-04-05 17:17 UTC, merged