Bakin Daniil - Stage 1
polis-vk/2022-nosql-lsm pull request #11
Opened 2022-02-26 15:20 UTC by donebd

2022-02-26 16:00 UTC, donebd commented
Форс пушы же не запрещены? Я тут просто с codeclimate развлекался

2022-02-26 16:54 UTC, Artyomcool commented on src/main/java/ru/mail/polis/daniilbakin/InMemoryDao.java
> +            new ConcurrentSkipListSet<>(Comparator.comparing(BaseEntry::key));
Посмотрите пожалуйста внутрь реализации этого класса, возможно у вас появятся идеи, как сделать лучше.

2022-02-26 16:56 UTC, Artyomcool requested changes

2022-02-26 16:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/ByteBufferDaoFactory.java
> -@DaoFactory
Это менять не разрешается.

2022-02-26 16:58 UTC, donebd commented on src/main/java/ru/mail/polis/test/ByteBufferDaoFactory.java
> -@DaoFactory
Просто я так понял, это была реализация Саши Косницкого, и для того чтобы юзалась моя реализация нужно убрать аннтоацию, может я не прав.

2022-02-26 17:33 UTC, donebd commented
С двумя @DaoFactory билд падает

2022-02-26 18:02 UTC, Artyomcool commented
Форс-пуш не нужен, я смотрю сумму изменений и мержить буду со сквошем

2022-02-26 18:03 UTC, Artyomcool requested changes

2022-02-26 18:03 UTC, Artyomcool commented on src/main/java/ru/mail/polis/daniilbakin/InMemoryDao.java
> +        }
entrySet() -> values()

2022-02-26 18:47 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/InMemoryDao.java
> +        }
Да, круто, спасибо

2022-02-27 09:57 UTC, Artyomcool approved these changes
Полный балл, * 1.2

2022-03-03 17:09 UTC, merged