Kosnitskiy Alexander, stage 4
polis-vk/2022-nosql-lsm pull request #115
Opened 2022-04-03 22:51 UTC by Sanerins

Реализовал 4 стадию в соответствии с указанными требованиями

2022-04-06 16:38 UTC, incubos requested changes
Есть вопросы и замечания.

2022-04-06 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +                --numberOfFiles;
Очень непривычно выглядит -- обычно считают узнаваемые файлы, а не декрементят неизвестные.

2022-04-06 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +                    renameFile(config, FILE + COMPOSITE_EXTENSION, FILE + 0 + SAFE_EXTENSION);
Несуществование файла выглядит исключительной ситуацией, о которой нужно сообщать.

2022-04-06 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        renameFile(config,FILE + IN_PROGRESS_EXTENSION, FILE + COMPOSITE_EXTENSION);
Последовательность всех этих переименований очень тесно связана с логикой `DaoUtility.workWithPaths()`, поэтому хотелось бы, чтобы код жил рядом в одном месте.

2022-04-06 19:39 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +    private static long workWithPaths(List<Path> paths, Config config) throws IOException {
Переименовал в более читаемое название

2022-04-06 19:40 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +        long numberOfFiles = paths.size();
Количество файлов, которые не являются "левыми". Если все файлы "левые", например, то мы вернем 0. Переименовал метод, чтобы это было более очевидно

2022-04-06 19:42 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +                --numberOfFiles;
Исправлю данную проблему, чтобы было более очевидно

2022-04-06 19:53 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +                    renameFile(config, FILE + COMPOSITE_EXTENSION, FILE + 0 + SAFE_EXTENSION);
Исправил

2022-04-06 20:10 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        renameFile(config,FILE + IN_PROGRESS_EXTENSION, FILE + COMPOSITE_EXTENSION);
Действительно, вынес в `DaoUtility`, спасибо!

2022-04-10 13:27 UTC, incubos approved these changes
Решение выглядит рабочим, но есть замечания. 15 баллов.

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +    public static final String COMPOSITE_EXTENSION = PersistenceDao.COMPOSITE_EXTENSION;
Ссылки во всех этих константах из `DaoUtility` на `PersistenceDao` выглядят как протекающая абстракция. Обычно заводят отдельный класс с константами и используют константы из него напрямую.

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +        Files.move(source, source.resolveSibling(newFileName));
Зачем тут `resolveSibling()`, а не `config.basePath().resolve()`?

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +    public static void renameFile(Config config, String fileName, String newFileName) throws IOException {
Зачем здесь `Config`, а не готовый `basePath()`?

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +        Files.move(source, source.resolveSibling(newFileName));
Не хватает `ATOMIC_MOVE`.

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +                deleteFiles(config, paths.size() / 2);
Удалять файлы лучше после проверки ниже, иначе у нас вообще никаких данных не останется.

2022-04-10 13:27 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoUtility.java
> +            if (path.toString().endsWith(INDEX + COMPOSITE_EXTENSION)) {
Лучше это делать в отдельном блоке/методе, иначе мы считаем `numberOfFiles`, а когда встречаем `COMPOSITE_EXTENSION` внезапно удаляем лишнее, пересчитываем и выходим.

2022-04-11 15:49 UTC, merged