Alina Shestakova, Stage 1
polis-vk/2022-nosql-lsm pull request #12
Opened 2022-02-26 17:04 UTC by Anilochka

2022-02-26 18:06 UTC, Artyomcool requested changes

2022-02-26 18:06 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +        }
Аллокация во время сравнения (частая операция) - не самый лучший вариант.

2022-02-26 18:06 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/ByteBufferDaoFactory.java
> +//@DaoFactory
Так делать запрещено

2022-02-26 21:22 UTC, Anilochka commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +        }
Поняла, поправила, теперь нахожу относительное смещение до первых различающихся байт у o1 и o2 и сравниваю по этим байтам, только пока что тесты проходят только локально

2022-02-27 10:03 UTC, Artyomcool approved these changes
Полный балл, х1.5

2022-03-03 17:11 UTC, merged