Kovalenko Pavel, Stage 4
polis-vk/2022-nosql-lsm pull request #120
Opened 2022-04-05 12:53 UTC by PaaavelZ

2022-04-06 17:10 UTC, incubos requested changes
Есть сомнения в корректности поведения при возможных сбоях.

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/LSMDao.java
> +        serializer.write(mergeIterator);
Что будет, если произойдёт сбой и файлы будут недозаписаны?

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
Если уж делать на regex, то давайте делать эффективно без нескольких `replace()`. См. `Pattern.matcher()` и другие методы.

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            sstables.put(priority, new PairedFiles(dataIterator.next(), indexesIterator.next()));
Почему мы уверены, что `priority` соответствует именам файлов?

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            return FileVisitResult.TERMINATE;
Разве такая ситуация не свидетельствует о том, что БД закоррапчена?

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        PairedFiles lastPairedFiles = addPairedFiles();
Т.е. мы сразу создаём пустые файлы и добавляем их в `sstables`, где они и останутся жить даже в случае ошибок при последующей записи, верно? Кроме того, они будут видны при переоткрытии БД и прочитаются некорректно.

2022-04-06 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/LSMDao.java
> +    public void compact() throws IOException {
Пока не выглядит отказоустойчиво.

2022-04-07 10:12 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            sstables.put(priority, new PairedFiles(dataIterator.next(), indexesIterator.next()));
priority = 1 будет сопоставлена пара файлов - data1.txt и indexes1.txt. У priority = 12 будет сопоставлена пара файлов - data12.txt и index12.txt. За сортировку имён файлов (их сравнивание) отвечает класс PathComparator. Поэтому мы уверены здесь только лишь в том, что файлы будут отсортированы в нужном порядке. Но если, скажем, у нас в директории хранится пара data7.txt и index11.txt, то очевидна дыра в логике.

2022-04-07 10:14 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            return FileVisitResult.TERMINATE;
Мне казалось, что если мы визитёра терминейтним, то вылетит исключение. Сейчас проверю

2022-04-07 10:22 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            return FileVisitResult.TERMINATE;
Исключение не вылетает. Моя ошибка. Но даже если бы вылетало, нам было бы трудно понять, что пошло не так, без пояснений в самом исключении, поэтому надо кидать своё. Поправил.

2022-04-07 10:40 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
Тут риджексы задействованы немного косвенно, мне надо лишь раздробить строку так, чтобы вынуть из неё число. То есть вот есть у меня data12.txt, мне надо отбросить 'data', '.txt', и вынуть получившееся число. Без replace'ов трудно представляю, как это сделать даже на Pattern'е.

2022-04-07 11:05 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
В мачере есть replaceAll, я так понимаю, работает он за один проход. Или можно ещё эффективнее?

2022-04-07 11:17 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            sstables.put(priority, new PairedFiles(dataIterator.next(), indexesIterator.next()));
Дыру заплатал.

2022-04-07 19:27 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
Почитал спеку по тому, что Вы назвали, мне показалось Ваше предложение просто сделать риджексы более ярко выраженными и, быть может, оптимизировать часть обработки риджекса его пре-компиляцией. Сделал на Matcher.replaceAll, но остаётся ощущение, что Вы ожидали другого.

2022-04-07 19:30 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/ConfigVisitor.java
> +            sstables.put(priority, new PairedFiles(dataIterator.next(), indexesIterator.next()));
Теперь проверяю то, что каждый файл должен соответствовать своей итерации (на первой итерации у нас должна быть пара data1-indexes1, на второй - data2-indexes2) за счёт добавления функции isPairedFiles (номера файлов равны) и сравнения этих номеров с текущей итерацией (должны быть равны)

2022-04-08 20:27 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        PairedFiles lastPairedFiles = addPairedFiles();
1) при переоткрытии БД FileIterator не читает пустые файлы из-за вот такой проверки
![image](https://user-images.githubusercontent.com/76079492/162525320-900375bc-bde5-4eae-a6b7-18b6add72c24.png)
2) если возникла ошибка, лучшее, что мы можем сделать - удалить закорапченные файлы и прокинуть ошибку выше по иерархии.

2022-04-08 20:32 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        PairedFiles lastPairedFiles = addPairedFiles();
Теперь удаляю такие файлы. Кстати, по реализации пустых файлов теперь не может быть - на ошибках мы их удаляем, а в случае пустых close(), flush() и compact() мы ничего не делаем (бесплатно их вызываем).

2022-04-09 07:38 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/LSMDao.java
> +    public void compact() throws IOException {
На данный момент имею такую защиту:
1) если во время компактинга удалились не все файлы (вылетела ошибка), то мы это находим при переоткрытии Дао и кидаем исключение;
2) если во время компактинга удалились все файлы, но не мувнулись оба скомпакченных файла, то мы это также находим на переоткрытии Дао и бросаем исключение (мы точно не знаем, успели ли мы скомпактить всё или же нет, а старые данные уже утеряны, так что мы не можем нести ответственность за те данные, что остались после закоррапченного компактинга);
3) если во время компактинга успел мувнуться лишь один файл, мы это также находим при переоткрытии и аналогичным образом кидаем исключение (на самом деле, в теории можно было бы сделать проверку на количество найденных файлов, на наличие среди них лога, куда мы писали наши скомпакченные файлы, но эта задача кажется нетривиальной и потребует серьёзных усилий, нагромождая наш код);
4) если ошибка вылетает во время записи в файл (запись у нас централизована в одной функции сериалайзера), то мы в блоке catch удаляем файлы, куда записывали, и пробрасываем исключение выше, чтобы о нём все знали;
5) если ошибка вылетает при получении mergeIterator'а в любой части кода, мы ничего не теряем;
6) если ошибка вылетает между получением mergeIterator'а и компактинга всех файлов, то мы по факту ничего не теряем, у нас остаётся возможность при следующем переоткрытии Дао сделать новый компакт по старым файликам.

Однако всё это было ещё на уровне ошибок по типу "Отказ диска". Если же мы вырубились из питания, то никакие файлики мы удалить не успеем, ничего сделать не успеем. Для такого случая в каждом файле будем содержать мета-информацию о файле (в нашем случае самую простую - записался ли до конца файл или нет). При переоткрытии Дао мы в ConfigVisitor проверяем файлы не только на то, что они парны и последовательны, но и на то, записались ли они до конца или нет. Мне помнится из условий выполнения этого стейджа, что мы можем пожертвовать последней порцией данных. Тогда все записанные файлы мы "возрождаем", а незаписанные выбрасываем. А незаписанные файлы - это наши энтрики, которые были в самой последней порции данных, так что в этом плане всё должно быть в порядке. Тогда если в дата файле есть мета, то мы его принимаем (если он был парным и последовательным, мы можем ручаться всё ещё за то, что такая пара валидна мета записывается в самом конце, уже все энтри в этих файлах лежать, причин не доверять им нет). Если же в дата файле нет меты, то мы выбрасываем такую пару файлов (эта пара гарантированно была последней) (остаётся шанс того, что в них недозаписались энтрики, а может, всё оборвалось на середине записи какой-то энтри, этого нам никогда уже не узнать). А чтобы такие файлы не складировались, удаляем их.

2022-04-10 08:26 UTC, PaaavelZ commented
Не проходят только канкарент тесты, но как я вижу по https://github.com/polis-vk/2022-nosql-lsm/pull/126, с этим есть проблемы, или нет?

2022-04-10 13:34 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
Я имел в виду что-то вроде `data(\\d+).*` и вынуть после матчинга группу `(\\d+)`, в то время как текущее решение пытается заменить все нечисловые символы на пустую строку.

2022-04-10 13:45 UTC, incubos approved these changes
Happy path работает, но отказоустойчивость могла бы быть лучше, поэтому 12 баллов.

2022-04-10 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +            writeMeta(new FileMeta(FileMeta.finishedWrite), dataFile);
Перед этим не хватает `sync()` на диск.

2022-04-10 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/CompactVisitor.java
> +        if (!file.renameTo(newFile)) {
Скорее всего, неатомарно -- см. JavaDoc.

2022-04-10 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/pavelkovalenko/visitors/CompactVisitor.java
> +    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
Порядок перечисления файлов не определён, поэтому возможны дырки в случае сбоев. Текущая реализация рассматривает дырки как аварийную ситуацию, но можно было бы сделать лучше, потому что все данные есть в последнем файле и мы ничего не потеряли.

2022-04-10 18:09 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/PathComparator.java
> +        return Integer.parseInt(filename.replace(parts[0], REPLACEMENT).replace(parts[1], REPLACEMENT));
Понял, честно, до такого уровня применения риджексов я пока в своей практике не доходил, но предложение звучит очень интересно! Отдельная благодарность за это замечание

2022-04-11 15:48 UTC, merged