Stage 4: Lev Saskov
polis-vk/2022-nosql-lsm pull request #123
Opened 2022-04-06 08:48 UTC by levs2001

2022-04-07 15:17 UTC, Artyomcool requested changes
Задание реализовано некорректно

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StoragePart.java
> +        assert key.isPresent();
ассерты в джаве по-умолчанию не работают

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StoragePart.java
> +    private void remapIfNeed(int changedSize) throws IOException {
чаще всего лучше посчитать заранее, чем тратить лишний mmap

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StoragePart.java
> +        return mapFile(filePath, (int) filePath.toFile().length());
ну тут как раз разница не велика, вы всё равно в той части кода, которая должна работать редко, да и возможностей не очень много

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +        for (int i = 0; i < Integer.MAX_VALUE; i++) {
for (int i = 0; ; i++)

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            throw new FileSystemException("Renaming compaction file error.");
и вот вы на этом месте потеряли данные

2022-04-07 15:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            throw new FileSystemException("Renaming compaction file error.");
или на строчку выше
или ещё на строчку выше
или ещё на строчку выше

вы не можете сначала удалить данные, а потом надеяться, что всё будет хорошо

2022-04-07 15:29 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +        for (int i = 0; i < Integer.MAX_VALUE; i++) {
Так было, но код клаймат ругается

2022-04-12 07:21 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StoragePart.java
> +        return mapFile(filePath, (int) filePath.toFile().length());
В stage5 уберу комментарий.

2022-04-12 14:31 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            throw new FileSystemException("Renaming compaction file error.");
В stage 5 исправлю.

2022-04-24 15:10 UTC, Artyomcool reviewed
1/4 * 1.2, грубая потеря данных

2022-04-24 15:10 UTC, merged