Add stage 5 description
polis-vk/2022-nosql-lsm pull request #126
Opened 2022-04-08 10:22 UTC by incubos

2022-04-10 12:27 UTC, Artyomcool requested changes

2022-04-10 12:27 UTC, Artyomcool commented on README.md
> +* Поведение всех других методов `Dao` после вызова `close()` не определено
По-моему надо ещё добавить "включая итерирования по предварительно полученному итератору"

2022-04-10 12:27 UTC, Artyomcool commented on README.md
> +Требуется обеспечить потокобезопаность **всех** методов `Dao`, т.е. любые методы могут вызываться одновременно из разных потоков и поведение должно быть корректным.
По-моему стоит добавить про то, что по итератору тоже можно ходить, что он не инвалидируется и т.п., кроме после close

2022-04-10 12:32 UTC, incubos commented on README.md
> +Требуется обеспечить потокобезопаность **всех** методов `Dao`, т.е. любые методы могут вызываться одновременно из разных потоков и поведение должно быть корректным.
Дописал.

2022-04-10 12:32 UTC, incubos commented on README.md
> +* Поведение всех других методов `Dao` после вызова `close()` не определено
Годное замечание. Дописал.

2022-04-11 15:29 UTC, Artyomcool approved these changes

2022-04-11 15:29 UTC, merged