Stage 5 tests
polis-vk/2022-nosql-lsm pull request #127
Opened 2022-04-13 10:18 UTC by PaaavelZ

2022-04-18 16:52 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +public class Stage5Close extends BaseTest {
Имена классов с модульными тестами должны иметь суффикс `Test` (IDEA это подсказывает) -- касается и остальных классов тоже.

2022-04-18 17:07 UTC, incubos requested changes
Есть вопросы/замечания/предложения.

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        int count = 50_000; // > 2 MB
Стоит поднять порог, потому что железо может быть быстрее, чем кажется.

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        assert(millisElapsed < 50 + nThreads*3);
Почему условие зависит от количества потоков? Реально только первый `flush()` должен выполнять работу, да и то -- асинхронно.

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        Thread.sleep(500);
Для чего этот `sleep()`?

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        runInParallel(nThreads, count, value -> dao.upsert(entries.get(value))).close();
На замену `entries.get(value)` есть метод `valueAt()`.

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        runInParallel(nThreads, count, value -> dao.upsert(new BaseEntry<>(entries.get(value).key(), null))).close();
Вместо `entries.get(value).key()` будет эффективнее использовать `keyAt()`.

2022-04-18 17:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        assert(millisElapsed < 50 + nThreads*3);
Почему здесь участвует `nThreads`?

2022-04-18 19:50 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Timer.java
> +    public long elapse() {
Согласен, не заметил такого дублирования кода на каждом чихе)

2022-04-18 19:55 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Timer.java
> +    public long elapse() {
Теперь это elapseMs

2022-04-18 20:00 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +        assert(millisElapsed > 500);
Просто я немного прикинул, два флаша (25к + 15к) за полсекунды вроде звучит очень быстро, и решил остановиться на 500мс. Хотя да, многовато вышло. Надо подождать так, чтобы не сложилось впечатления, что таска передана в очередь и никто её не ждёт. Как Вам предложение увеличить нагрузку до 100к ентри и оставить эти 500мс? Или ещё как-то покрутить, просто у меня в тестах 50мс - сигнал о том, что таска закинута в ExecutorService на выполнение. Мб с такой оценкой я тоже переборщил

2022-04-18 20:01 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Timer.java
> +    public static final Timer INSTANSE = new Timer();
Согласен, теперь у Таймера один статический метод

2022-04-18 20:02 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +        assert(millisElapsed > 500);
Да, поправил, с непривычки

2022-04-18 20:02 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        int count = 50_000; // > 2 MB
Полностью согласен, увеличил до миллиона

2022-04-18 20:08 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        assert(millisElapsed < 50 + nThreads*3);
Если внимательно посмотреть на runInParallel, то можно заметить, что можно заметить немного его сложноватую структуру. Мне показалось, что на каждый поток из nThreads при такой структуре будет тратиться порядка 3мс (пока в цикле мы побудем, пока run() сделаем), то есть это, по моим оценкам, nThreads*3 ms, и у нас есть наша таска, которая выполнится в единственном числе - на неё выделяю 50ms на то, чтобы внутри она немного подготовилась, локи залокались, и таска закинулась в сервис
![image](https://user-images.githubusercontent.com/76079492/163869712-00492f27-592e-44e4-8088-50e9864bb963.png)

2022-04-18 20:22 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        Thread.sleep(500);
Когда-то у него был сакральный смысл, сейчас лучше это удалить

2022-04-18 20:24 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        assert(millisElapsed < 50 + nThreads*3);
Чуть выше ответил по этому поводу

2022-04-18 20:26 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        runInParallel(nThreads, count, value -> dao.upsert(entries.get(value))).close();
Последовал примеру из BasicConcurrentTest. И мне тут нужна энтря, так что entryAt
![image](https://user-images.githubusercontent.com/76079492/163872409-f748f08b-1f99-490e-b3ff-d0978f915114.png)

2022-04-18 20:29 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +public class Stage5Close extends BaseTest {
Сделано

2022-04-18 20:35 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        runInParallel(nThreads, count, value -> dao.upsert(entries.get(value))).close();
Только мне нужна энтря, наверно, Вы имели в виду entryAt

2022-04-18 20:36 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Compact.java
> +        runInParallel(nThreads, count, value -> dao.upsert(entries.get(value))).close();
Поменял

2022-04-19 10:38 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        assert(millisElapsed < 50 + nThreads*3);
Можно понизить оценку примерно до 50 + nThreads*1.5 или даже до 50 + nThreads, но мне всё равно кажется, что зависимость от кол-ва потоков есть, ибо каждый на себя берёт какой-то процессорный квант времени

2022-04-19 11:07 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/Utils.java
> +    public static final int N_ENTRIES_FOR_FLUSH = (int) Math.ceil((double) FLUSH_TRESHOLD / N_BYTES_FOR_ENTRY);
Возник вопрос - как корректно считать, сколько байт занимает энтря? В ТЗ написано: "При превышении размера таблицы в памяти указанного порога". То есть размер таблицы мы считаем как N * sizeOf(Entry), или как N * sizeOf(Map.Entry<String, Entry<String>>), или вообще считать так, как записываем (сначала 4 байта на размер ключа, потом сам ключ, потом ещё 4 байта на размер значения и потом само значение)?

2022-04-21 18:06 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +        assert(millisElapsed > 500);
Больше записей будет выглядеть норм.

2022-04-21 18:09 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Flush.java
> +        assert(millisElapsed < 50 + nThreads*3);
Но мы же обсуждаем модульные тесты. Чем проще, тем лучше.

2022-04-21 18:12 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/Utils.java
> +    public static final int N_ENTRIES_FOR_FLUSH = (int) Math.ceil((double) FLUSH_TRESHOLD / N_BYTES_FOR_ENTRY);
В идеале мы хотели бы максимально точную оценку занимаемого места в Heap, но это гораздо сложнее, чем кажется, поэтому в нашем курсе приемлемым будет и последний вариант.

2022-04-21 19:29 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/Stage5Close.java
> +        assert(millisElapsed > 500);
Увеличил размер до 100к, время задержки понизил до 300мс

2022-04-21 19:30 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/Utils.java
> +    public static final int N_ENTRIES_FOR_FLUSH = (int) Math.ceil((double) FLUSH_TRESHOLD / N_BYTES_FOR_ENTRY);
Попытался повторить то, что писал Артём Дроздов (жду, пока код появится на гите, чтобы повторение было точным)

2022-04-21 20:50 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/Utils.java
> +    public static final int N_ENTRIES_FOR_FLUSH = (int) Math.ceil((double) FLUSH_TRESHOLD / N_BYTES_FOR_ENTRY);
По совету Артёма Дроздова теперь определяю верхнюю и нижнюю границу (супремум и инфимум) для размера энтри, которая может встретиться в различных реализациях, и в зависимости от гарантированного числа вставок для автофлашинга манипулирую этими числами в своих тестах

2022-04-24 08:27 UTC, incubos commented
@Artyomcool посмотришь тоже?

2022-04-24 09:07 UTC, incubos requested changes
Есть вопросы и замечания.

2022-04-24 09:07 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +            millisElapsed = Timer.elapseMs(() -> assertSame(dao.get(tmb), null));
У нас ведь должна остаться единственная могила по `nIterations - 1`, разве нет? В цикле выше на каждой итерации мы **перезаписываем все значения**, а затем добавляем могилку по номеру итерации.

2022-04-25 16:29 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/FlushTest.java
> +        int count = Utils.INFIMUM_N_ENTRIES_FOR_FLUSH - 1;
Где-то нам нужно гарантированно запустить автофлашинг для всех реализаций, а где-то - гарантированно его не запустить. Для этих целей используются числа SUPREMUM_N_ENTRIES и (INFIMUM_N_ENTRIES - 1). Возникает ощущение, что последняя может быть занесена в константу.

2022-04-25 16:41 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        runInParallel(100, count, value -> dao.upsert(entryAt(value))).close();
Ориентировался на данное Вами замечание. SUPREMUM_N_ENTRIES - это что-то около 25к энтри. 3 таких штуки - примерно 75к. Наверно, многовато.
![image](https://user-images.githubusercontent.com/76079492/165134542-65561832-9fad-4cac-9775-e0b1a7042215.png)

2022-04-25 16:45 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
Согласен, у меня крутилась эта идея в голове, но не мог найти её реализации. Сейсас вижу это через простенький FileVisitor, который внутри будет крутить счётчик файлов и выдавать его наружу.

2022-04-25 17:13 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
Но в то же время мы всё равно должны сделать некоторый временной срез нашего каталога, ибо мы же не можем ждать бесконечно. Нам нужна какая-то точка выхода из ожидания. А гарантированное число файлов, которое будет вопроизведено в процессе upsert'инга, мы определить не можем, ибо работаем в терминах SUPREMUM и INFIMUM. Где-то 15к апсертов (INFIMUM) хватит для автофлашинга, а где-то для этого нужно будет 30к. В то же время во втором кейсе, с более легковесными энтрями, у нас уже возникнет два автофлашинга, а равно - удвоится число файлов в нашей директории. Так что приходится лишь "пристреливаться" по времени, подбирать наиболее подходящее для большинства машин в худших случаях.

2022-04-25 17:13 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(100); // wait until dao is flushing
Чуть выше ответил

2022-04-25 17:41 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
На моей не самой быстрой и не самой дорогой машине этот тест проходит за 655мс. Можно поставить 1.5 секунды на ожидание на всякий случай.
![image](https://user-images.githubusercontent.com/76079492/165143866-53770cff-fced-414d-bbfa-e6538e80e0b3.png)

2022-04-25 17:43 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
Ответил выше по похожему вопросу, увеличил время ожидания до полутора секунд.

2022-04-25 17:50 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +            millisElapsed = Timer.elapseMs(() -> assertSame(dao.get(tmb), null));
Задумка была немного другой - в трёх файлах три могилки. Упустил из виду эту деталь, что данные переписываются.  Но вообще цель была таковой, чтобы в трёх файлах были уникальные значения, которые можно было бы изъять и проверить, что доступ ко всем данным сохраняется. Вместо могилок теперь вставляю пары "brilliant<N>"-"brilliant".

2022-04-26 08:09 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/Utils.java
> +public final class Utils {
Оставил супремумы и инфимумы "в кишках" Utils, наружу теперь выдаю более говорящие названия

2022-04-26 08:37 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
Согласен, в голове крутилась такая идея, но не мог найти ей реализации. Теперь создаю таску, которая с периодичностью раз в полсекунды просыпается и смотрит на количество файлов, если изменилось с предыдущего раза - переписывает свои данные и снова засыпает, если нет - то выходит из цикла.

2022-04-26 08:38 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        Thread.sleep(1_000); // wait until dao is flushing
Тут тоже проблема с наблюдением за файлами, которую я уже решил.

2022-04-26 08:40 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/ConfigRunnable.java
> +                Thread.sleep(500);
В идеале даже без сна будет хорошо, но это ведь syscall'ы, и их очень много, или я ошибаюсь?

2022-04-26 09:59 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        runInParallel(100, count, value -> dao.upsert(entryAt(value))).close();
Интересным моментом является то, что где-то SUPREMUM'а хватит на 1 автофлаш, а где-то - на 2. В зависимости от реализации, так что приходится жонглировать коэффициентами только так.

2022-04-26 10:01 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        runInParallel(100, count, value -> dao.upsert(entryAt(value))).close();
Изначально я вообще хотел создать аннотации, чтобы каждый человек для себя выбрал, какая у него реализация, и в зависимости от этого у нас были бы более универсальные и простые тесты, мы бы оперировали лишь одной константой - количеством энтрей для автофлаша.

2022-04-26 11:35 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/AbstractTest.java
> +    int ENTRY_SIZE = EntrySizeRealization.ONE.getEntrySize();
Теперь реализацию можно поменять вот здесь в одном месте, и она будет автоматически применена во всех тестах.

2022-04-26 12:04 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/EntrySizeRealization.java
> +public enum EntrySizeRealization {
Исходя из замечания Вадима касательно размера энтри - 
![image](https://user-images.githubusercontent.com/76079492/165295194-d0a834b3-9475-4d38-b848-682cfb3e03c5.png)
сделал вывод о том, что больше, чем представлено здесь, релизаций быть не может (мы должны учитывать записи и в дата файле, и в индексах, различаться они лишь будут учитыванием/игнорированием Character.BYTES и использованием интов/лонгов для записи смещений и размеров ключей и значений). Переносы строки не учитываю, ибо использование их приводит к увеличанию перформанса (на миллион энтрей у нас появляется (2 + 2) * миллион = 4 миллиона байт ~~ 4 МБ на переносы строк). Поэтому переносов строк <b>не должно быть</b>.

2022-04-27 01:30 UTC, PaaavelZ commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/CompactTest.java
> +        runInParallel(100, count, value -> dao.upsert(entryAt(value))).close();
Сделал AbstractTest, через который трансферю нужные константы, а также сделал в нём отдельный тест на действительное канкарент-взаимодействие с дао с разных сторон, подумал, что он не вписывается в рамки FlushTest, CompactTest и остальных.

2022-04-30 10:25 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/EntrySizeRealization.java
> +public enum EntrySizeRealization {
У других ребят есть не только строковые реализации (т.е. в основном они как раз не строковые). Не возникнет ли проблем с этим?

2022-04-30 10:26 UTC, incubos commented on src/test/java/ru/mail/polis/pavelkovalenko/stage5/AbstractTest.java
> +        List<ParallelTask> tasks = List.of(
К сожалению, я не понял, что имеется в виду.

2022-04-30 11:01 UTC, incubos requested changes
Получился целый фреймфорк, большой и многословный. Вмёрдживать это и заставлять всех студентов разбираться с ним мы не будем (а иначе им придётся).
Кода получилось очень много, сравнимо со всеми остальными тестами. Код использует множество предположений о времени, размерах и его трудно параметризовать.
Кроме того, запилено много вспомогательных классов, которые сами по себе требуют тестирования.
Предлагаю 10 баллов за попытку реализации. Ещё 10 баллов, если ваше собственное решение для 5 этапа пройдёт эти тесты.

2022-04-30 14:55 UTC, PaaavelZ commented
> Получился целый фреймфорк, большой и многословный. Вмёрдживать это и заставлять всех студентов разбираться с ним мы не будем (а иначе им придётся). Кода получилось очень много, сравнимо со всеми остальными тестами. Код использует множество предположений о времени, размерах и его трудно параметризовать. Кроме того, запилено много вспомогательных классов, которые сами по себе требуют тестирования. Предлагаю 10 баллов за попытку реализации. Ещё 10 баллов, если ваше собственное решение для 5 этапа пройдёт эти тесты.

Хорошо

2022-04-30 14:55 UTC, closed without merging