REFACTOR 1-4 stages
polis-vk/2022-nosql-lsm pull request #131
Opened 2022-04-16 02:44 UTC by RalerCulte

Refactored code

2022-04-18 17:10 UTC, incubos reviewed
Можно вмёрджить после #116, видимо?

2022-04-18 17:10 UTC, incubos commented on src/main/java/ru/mail/polis/test/glebkomissarov/MemorySegmentDaoFactory.java
> +@DaoFactory(stage = 4, week = 1005000)
Зачем такой `week`?

2022-04-19 17:19 UTC, RalerCulte commented
> Можно вмёрджить после #116, видимо?

Да

2022-04-24 08:28 UTC, incubos requested changes
Переведите на меня, как можно будет вмёрдживать.

2022-04-24 20:51 UTC, RalerCulte commented
> Переведите на меня, как можно будет вмёрдживать.

Можно мерджить

2022-04-30 09:56 UTC, merged

2022-04-30 09:56 UTC, incubos commented
> > Переведите на меня, как можно будет вмёрдживать.
> 
> Можно мерджить

Done. Прошу прощения за задержку.