Lustesenko Dmitrii Stage5
polis-vk/2022-nosql-lsm pull request #133
Opened 2022-04-16 20:04 UTC by LutsenkoDm

2022-04-17 11:23 UTC, LutsenkoDm commented
Не проходит 3 теста: 
testHugeData по Timeout из-за autoflush-ей (100_000 отдельных чтений по двум файлам с ~45000 записями)  
2 тестах из CompactionTest не успевают сделаться upsert (при увеличении flushThresholdBytes проходит overwrite), тест multiple противоречит спецификации: требует одного файла после compact, но так как compact теперь только по диску, то в close память сохраниться в еще один файл и тест упадет. 
Code climate ругается на размер файла (274 > 250) , хочет конструктор в анонимном классе вместо блока инициализации и try с ресурсами, где ресурсов нет.

2022-05-02 16:45 UTC, LutsenkoDm commented
> 

     Узким местом является бинарный поиск, который будет выполняться 100_000 раз, а именно строка номер 164, избавиться / изменить которую я не могу:   
bufferedReader.skip(position - left);
     Так как я выбрал реализацию на строках, без ByteBuffer и MemorySegment, то не переписывая чтение файлов с их помощью и логику бинарного поиска,  вариантов оптимизации чтения файлов для прохождения testHugeData я не вижу. Также для подтверждения того,  что дело именно в чтении, а не в автоматическом flush (причина не относится к Stage 5) добавлен тест аналогичный testHugeData , где 100_000 чтений заменены на вызов dao.all(), который успешно проходит.

2022-05-02 16:49 UTC, LutsenkoDm commented
> testHugeData можно не отключать, попробуйте попрофилировать свой тест и найти узкое место, скажу подсказку, что скорее всего все дело в медленном чтении файла

 Узким местом является бинарный поиск, который будет выполняться 100_000 раз, а именно строка номер 164, избавиться / изменить которую я не могу: bufferedReader.skip(position - left);
Так как я выбрал реализацию на строках, без ByteBuffer и MemorySegment, то не переписывая чтение файлов с их помощью и логику бинарного поиска, вариантов оптимизации чтения файлов для прохождения testHugeData я не вижу. Также для подтверждения того, что дело именно в чтении, а не в автоматическом flush (причина не относится к Stage 5) добавлен тест аналогичный testHugeData , где 100_000 чтений заменены на вызов dao.all(), который успешно проходит.
Почему-то добавляется scroll, хотя добавлять его я не хотел

2022-05-02 16:50 UTC, LutsenkoDm commented
> testHugeData можно не отключать, попробуйте попрофилировать свой тест и найти узкое место, скажу подсказку, что скорее всего все дело в медленном чтении файла

    Узким местом является бинарный поиск, который будет выполняться 100_000 раз, а именно строка номер 164, избавиться / изменить которую я не могу: bufferedReader.skip(position - left);
     Так как я выбрал реализацию на строках, без ByteBuffer и MemorySegment, то не переписывая чтение файлов с их помощью и логику бинарного поиска, вариантов оптимизации чтения файлов для прохождения testHugeData я не вижу. Также для подтверждения того, что дело именно в чтении, а не в автоматическом flush (причина не относится к Stage 5) добавлен тест аналогичный testHugeData , где 100_000 чтений заменены на вызов dao.all(), который успешно проходит.

2022-05-03 19:54 UTC, atimofeyev commented
если узкое место в поиске по файлу, который нельзя поправить, то надо подумать что можно поправить?
например размер буффера в BufferedReader?

а оп поводу CompactionTest.overwrite убежден что можно поправить реализацию, оставив реализацию на строках, чтобы тест проходил, ищите узкое место, вероятно стоит как-то переосмыслить структуры программы

про multiple не понял про описанную проблему, у меня этот тест не прошел по той же причине что и overwrite

2022-05-04 08:21 UTC, LutsenkoDm commented
> если узкое место в поиске по файлу, который нельзя поправить, то надо подумать что можно поправить? например размер буффера в BufferedReader?
> 
> а по поводу CompactionTest.overwrite убежден что можно поправить реализацию, оставив реализацию на строках, чтобы тест проходил, ищите узкое место, вероятно стоит как-то переосмыслить структуры программы
> 
> про multiple не понял про описанную проблему, у меня этот тест не прошел по той же причине что и overwrite

Увеличение размера буфера в BufferedReader не помогло, тест также падает по Timeout. Причина не столько в самом поиске, а в самом подходе, используемом в реализации на строках. При использовании BufferedReader так или иначе будет 100_000 обращений к диску и даже при добавлении оптимизаций вложиться в 5 секунд мне кажется невозможным, если только не использовать, например, MappedByteBuffer, чтобы обращение к диску было только 1 раз, но тогда реализация будет уже не на строках. Но общим случаем является получение range, тогда проблема обращения к диску нивелируется.  Данный тест предполагает чтение только из памяти, но в связи с введением autoflush в нем идет обращение к диску, чего как мне кажется не предполагалось изначально.  В общем случае данный тест теперь не совсем корректный и возможно следует уменьшить размер entries, к примеру до 40_000, чтобы не доходило до autoflush.

В CompactionTest.overwrite причина падения не связана с чтением с диска, поэтому реализация на строках или нет никак не влияет. Дело в том что все вставляемые entry очень большого размера, в моей реализации 524309 байт. Размер таблицы в памяти flushThresholdBytes равен 1048576 байт. Размер двух entry(все они одинакового размера) составляет 1048618 байт. Таким образом таблица в памяти вмещает только одну entry из данного, так как вторая  уже не влезает.
Получается следующий сценарий, (в тесте вставляется 10 entry в цикле):
1) Первая entry добавляется в первую таблицу в памяти
2) Вторая entry вызывает autoflush и добавляется во вторую таблицу в памяти
3) Третья entry не помещается во вторую таблицу и база отвечает отказом
В итоге получается так что одна таблица в памяти может поместить одну entry и autoflush не успевает выполниться за вызов одного upsert и база справедливо выдает отказ. Ожидание upsert-ми flush запрещено спецификацией, так как если вставляемое entry не помещается в таблицу, то база обязана выдать сразу отказ.
При увеличении flushThreshold (138 строка файла DaoTest) в 3 раза данный тест локально у меня проходит.

Для теста CompactionTest.multiple ситуация аналогична описанной для overwrite. Плюс эвристическая проверка в конце теста:   assertTrue(stats.getMax() - stats.getMin() < 1024) пройдет только в том случае, если останется один файл после вызова пары методов compact и close, что было верно для Stage 4, где compact  был как по диску, так и по памяти, но неверно для Stage 5, так как compact теперь только по диску и в конце будет 2 файла, один от compact и второй от close, в котором память будет записана в отдельный файл и упомянутая выше проверка пройдена не будет. Таким образом данный тест противоречит спецификации.

2022-05-12 20:29 UTC, atimofeyev requested changes
testHugeData: А Вас не смущает то что вы не переопределили дефолтный, очень не эффективный, метод dao.get(key), так как поиск по одному ключу сильно проще чем весь рейндж от ключа до null. Думаю если упростить запрос по ключу - будет все в порядке с тестом

overwrite можно пройти если попробовать подождать разумное время флаша
В условии же написано: Под "не блокирует" ниже понимается отсутствие блокировок длительностью более нескольких миллисекунд.

2022-05-12 20:57 UTC, LutsenkoDm commented
> testHugeData: А Вас не смущает то что вы не переопределили дефолтный, очень не эффективный, метод dao.get(key), так как поиск по одному ключу сильно проще чем весь рейндж от ключа до null. Думаю если упростить запрос по ключу - будет все в порядке с тестом
> 
> overwrite можно пройти если попробовать подождать разумное время флаша В условии же написано: Под "не блокирует" ниже понимается отсутствие блокировок длительностью более нескольких миллисекунд.

На лекциях говорили что его(get по ключу) не стоит переопределять, он остался с первых этапов, когда не было еще чтения range и это лишняя оптимизация и усложнение кода. Медленное чтения первого ключа в любом останется, так как бинарный поиск все равно надо будет выполнять и разницы практически не будет. Мне кажется что уложится в Timeout при использовании BufferedReader  невозможно и оптимальнее было бы переписать на чтение через что-то вроде MappedByteBuffer, но на это я пока не готов и в данном stage этого не требуется. 

По поводу overwrite: в спецификации сказано: "В случаях, когда flush не поспевает за вставкой данных (одна полная таблица всё ещё пишется на диск, в то время как заполнилась следующая таблица), параллельные upsert()ы должны бросать исключение -- тем самым мы сигнализируем клиенту о перегрузке и избегаем падения по OutOfMemory".  Ситуация когда не помещается во вторую таблицу соответствует OutOfMemory. Если ждать совсем немного, то пользы от этого не будет, при хоть немного длительном ожидании параллельно может прийти несколько больших entry и произойдет падение по OutOfMemory. Я реализовал как сказано в задании: если не помещается в вторую таблицу, то бросается исключение. Данные несколько миллисекунд у меня используется для синхронизации после выполнения flush, который выполняется асинхронно.

2022-05-13 19:31 UTC, atimofeyev approved these changes
18 баллов

2022-05-15 19:31 UTC, merged