Stage5: Lev Saskov
polis-vk/2022-nosql-lsm pull request #135
Opened 2022-04-17 21:16 UTC by levs2001

Пока ничего не проверял, сделал, как я это вижу.

2022-05-10 13:29 UTC, atimofeyev requested changes

2022-05-10 13:29 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/FlushExecutor.java
> +            throw new RuntimeException(e);
что будет если упадет поток, который обрабатывает флаши?

2022-05-10 20:51 UTC, atimofeyev commented
> Всё работает. Сделал для Линукс, хоть начинал на винде. Отключил CompactionTest.overwrite(), потому что там подряд идут флаши, из-за превышения порога в хипе и мой класс специально выбивает exception (сделано по ТЗ). Отключил CompactionTest.multiple(), так как некорректен для stage5, требует 1 файл, хотя мы при компакте не сохраняем в compactionFile memTable.

Я думаю что тест overwrite можно было бы и не отключать, ничто не запрещает какое-то время подождать флаша, в условии задачи сказано что пож блокировкой понимается блок на достаточно долгое время, так что я бы все же при вставках подождал какое-то время флаша, иначе совсем печальная картина и не вставить большие записи подряд

2022-05-12 09:38 UTC, levs2001 commented
> > Всё работает. Сделал для Линукс, хоть начинал на винде. Отключил CompactionTest.overwrite(), потому что там подряд идут флаши, из-за превышения порога в хипе и мой класс специально выбивает exception (сделано по ТЗ). Отключил CompactionTest.multiple(), так как некорректен для stage5, требует 1 файл, хотя мы при компакте не сохраняем в compactionFile memTable.
> 
> Я думаю что тест overwrite можно было бы и не отключать, ничто не запрещает какое-то время подождать флаша, в условии задачи сказано что пож блокировкой понимается блок на достаточно долгое время, так что я бы все же при вставках подождал какое-то время флаша, иначе совсем печальная картина и не вставить большие записи подряд

Сделал флаш блокирующим, вернул overwrite, он проходит.

2022-05-12 09:39 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        if (memTableByteSize.addAndGet(entrySize) > flushThresholdBytes) {
Исправил. Использовал паттерн "Блокировка с двойной проверкой"

2022-05-12 09:39 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/CompactExecutor.java
> +            throw new RuntimeException(e);
Исправил. Теперь в методе compact есть проверка на то, что поток не прерван

2022-05-12 09:40 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/FlushExecutor.java
> +            throw new RuntimeException(e);
Исправил. Теперь в методе flush есть проверка на то, что поток не прерван

2022-05-12 09:41 UTC, levs2001 commented
После исправлений не проходит только CompactionTest.multiple(), выше объяснял почему. Также я убрал нотацию @disabled, чтобы можно было замерджить

2022-05-12 20:46 UTC, atimofeyev requested changes

2022-05-12 20:46 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            synchronized (monitor) {
а для чего тут нужна сихронизация на мониторе?

2022-05-12 20:50 UTC, atimofeyev requested changes

2022-05-12 20:50 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +        flushCompactLock.lock();
для чего нам лок flushCompactLock, если флаш мы всегда делаем в одном потоке?

2022-05-13 16:03 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            synchronized (monitor) {
Чтобы дальше если потоки вошли в этот иф они уже стали в очередь прежде чем создать новый memtable. Это исправляет ваше замечание: "мы можем записать больше чем надо в мапу, так и создать новую memTable дважды". Возможно, не понял вопрос, могу сделать synchronized(this).

2022-05-13 16:10 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +        flushCompactLock.lock();
flushCompactLock нужен для того, чтобы flush (flush вызывает save, а там  flushCompactLock.lock()) и compact не происходили одновременно. У меня для флаша и компакта потоки разные (сначала думал, что надо будет сделать их не взаимоисключающими, потом уточнив требования просто добавил лок)

2022-05-13 19:36 UTC, atimofeyev requested changes

2022-05-13 19:36 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            synchronized (monitor) {
так это не решает проблему, много потоков могут не пройти проверку
memTableByteSize.get() + entrySize > flushThresholdBytes, потому что осталось места на 10 байт, а 10 потоков одновременно вставляют по 9
так что они даже не попадут в этот иф и напихают в память больше чем надо

2022-05-13 20:40 UTC, levs2001 commented
https://github.com/polis-vk/2022-nosql-lsm/pull/135#discussion_r872721328
Да, я ошибся забыл увеличение размера добавить. Сейчас исправил (в коммите [Fixed error with flush after big size](https://github.com/polis-vk/2022-nosql-lsm/pull/135/commits/74b9ca5080746e6be7fc5e51d9394c9f3a16051a))

Сейчас прогоняются тесты Артема Дроздова на CI, потому что он stage = 40 выставил, но я проверял результаты на локальной машине, они остались прежними.

2022-05-13 20:42 UTC, levs2001 commented
Я не уверен, что корректно сделал, но по крайней мере, этой двойной проверкой я решил проблему потери информации из-за возможного одновременного создания нескольких новых  memtable-ов

2022-05-26 12:02 UTC, atimofeyev approved these changes
9 баллов

2022-05-26 12:11 UTC, closed without merging