Stage5, Kiselyov Alexander
polis-vk/2022-nosql-lsm pull request #138
Opened 2022-04-19 19:57 UTC by AlexanderKiselyov

2022-04-19 20:35 UTC, AlexanderKiselyov commented
Тесты не проходят из-за того, что происходит вставка очень большого числа данных и мапы переполняются, а также из-за нарушения требований к методу compact.

2022-04-23 07:10 UTC, AlexanderKiselyov commented
Тесты diskCemetry, memoryCemetry и persistentPreventInMemoryStorage не проходят то таймлимиту, на локальной машине выполняются успешно за 15-20 секунд.

2022-04-24 16:49 UTC, incubos requested changes
Пока решение совсем не выглядит корректным.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private State state;
Работа с этим ключевым полем не является потокозащищённой.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private State state;
Работа с этим ключевым полем не является потокозащищённой.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        try {
Почему это всё под `lock.readLock()`, а не само чтение `this.state`?

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            return;
Просто тихо проигнорируем?

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            if (currentState.getSize() + delta >= maxThresholdBytes) {
Этот `getSize()` -- довольно тяжёлая операция...

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                pairNum.set(1 - pairNum.get());
Мы это делаем под read lock, верно? Т.е. разные потоки могут попереключать `pairNum` туда-сюда? Не выглядит корректным решением.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            currentState.fileOperations.flush(currentState.pairs);
Синхронный flush не соответствует спеке.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                    iterator = new TombstoneFilteringIterator(
На  текущем этапе мы не выбрасываем могилы.

2022-04-24 16:49 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            this.state = new State(getPairs(), fileOperations);
Зачем мы это делаем, если compact происходит асинхронно?

2022-04-29 08:28 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileIterator.java
> +        pos = from == VERY_FIRST_KEY ? 0 : fileOperations.getEntryIndex(channelTable, channelIndex, from, indexSize);
исправил

2022-04-29 08:28 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileIterator.java
> +        pos = from == VERY_FIRST_KEY ? 0 : fileOperations.getEntryIndex(channelTable, channelIndex, from, indexSize);
исправил

2022-04-29 08:28 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        private NavigableMap<byte[], BaseEntry<byte[]>> flushingPairs;
исправил

2022-04-29 08:28 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +            return;
исправил

2022-04-29 08:28 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        public synchronized void performCompact() {
исправил

2022-04-29 08:29 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        taskResults = new ArrayList<>();
исправил

2022-04-29 08:29 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private class State {
исправил

2022-04-29 08:29 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            service.shutdown();
исправил, вынес все такие методы из класса State

2022-04-29 08:29 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private State state;
исправил

2022-04-29 08:29 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private State state;
исправил

2022-04-29 08:30 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        try {
занес чтение state под lock

2022-04-29 08:30 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            return;
исправил

2022-04-29 08:30 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            if (currentState.getSize() + delta >= maxThresholdBytes) {
упростил вычисление данного метода

2022-04-29 08:31 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                pairNum.set(1 - pairNum.get());
убрал данную логику из решения

2022-04-29 08:31 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                    iterator = new TombstoneFilteringIterator(
исправил

2022-04-29 08:31 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            this.state = new State(getPairs(), fileOperations);
исправил

2022-04-30 11:23 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            currentState.fileOperations.flush(currentState.pairs);
При вызове `flush()` вызывается `currentState.fileOperations.flush()` и всё блокируется, пока мы не запишем последний байт.

2022-04-30 12:01 UTC, incubos requested changes
Решение всё ещё некорректно. Последняя попытка для исправления.

2022-04-30 12:01 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        isClosed.set(true);
Будет корректнее в первом `if` вызвать `getAndSet(true)` и проверить результат, чтобы отбросить параллельных закрывальщиков.

2022-04-30 12:01 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
>          flush();
Почему это не перед вызовом `closeService()`?

2022-05-04 09:49 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        currentState.fileOperations.flush(currentState.flushingPairs);
сделал каждый новый flush в отдельном потоке

2022-05-04 09:50 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        lock.writeLock().lock();
исправил

2022-05-04 09:50 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            currentState = new State(new ConcurrentSkipListMap<>(Arrays::compare), this.state.pairs, fileOperations);
добавил новый метод в State

2022-05-04 09:50 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            this.state = new State(new ConcurrentSkipListMap<>(Arrays::compare),
добавил новый метод в State

2022-05-04 09:50 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        currentState.flushingPairs.clear();
исправил

2022-05-04 09:50 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        lock.writeLock().lock();
исправил

2022-05-04 09:51 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    private volatile State state;
исправил

2022-05-04 09:51 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                isBackgroundFlushing.set(false);
перенес в finally

2022-05-04 09:52 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +                isBackgroundFlushing.set(true);
вынес флажок из нового потока и перенес до вызова `performBackgroundFlush()`

2022-05-04 09:52 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            lock.writeLock().lock();
исправил

2022-05-04 09:53 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            currentState.updateSize(delta);
исправил

2022-05-04 09:53 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        this.state.pairs.put(entry.key(), entry);
исправил на `currentState`

2022-05-04 09:53 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +    public synchronized void compact() throws IOException {
убрал

2022-05-04 09:55 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        isClosed.set(true);
оставил метод `get()`, поскольку далее вызывается метод `flush()`, а в нем проверка на то, что метод `close()` еще не был вызван. Эта проверка нужна для случая, когда после метода `close()` вызывается метод `flush()`

2022-05-04 09:55 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
>          flush();
перенес

2022-05-10 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        State currentState = this.state;
Работа с полем `state` никак не защищена. Оно даже не `volatile`.

2022-05-10 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        if (isBackgroundFlushing.get()) {
Эта операция должна быть атомарной, иначе возможны гонки. Можно было бы использовать `getAndSet()`.

2022-05-10 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        synchronized (object) {
Ещё одна блокировка?! Внутри `currentState` ведь уже прячется `AtomicInteger`.

2022-05-10 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        currentState.pairs.put(entry.key(), entry);
Если выше вызвали `startFlushing()`, то у нас недостача, потому что `updateSize()` для текущей записи мы не вызвали.

2022-05-10 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        isClosed.set(true);
Видимо, я непонятно объяснил. Здесь всё ещё возможна гонка, если вызовут несколько `close()` параллельно.

2022-05-10 10:59 UTC, incubos approved these changes
Решение стало лучше, но корректным его назвать трудно. Половина баллов.

2022-05-23 10:27 UTC, closed without merging