Stage 5 Galeev Artur
polis-vk/2022-nosql-lsm pull request #141
Opened 2022-04-19 20:23 UTC by coradead

2022-04-28 14:37 UTC, coradead commented
p.s. я не знаю почему build падает, если запускать тесты по отдельности, то все прекрано

2022-05-11 20:51 UTC, Artyomcool requested changes
Боюсь, решение скорее полностью некорректное.
1/4 * 1.5.

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/DBReader.java
> +        for (FileDBReader fileReader : fileReaders) {
для порядку можно было бы тут тоже под локом проделать операции

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +            addIterator(memory.get(), 3, iterators, from, to);
довольно очевидные гонки: вы можете взять "старые" flush-данные, а потом "новую" memory-таблицу.

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +            synchronized (memory) {
по хорошему лучше бы этого избегать для всех потоков, которые резко воткнулись, но это в целом приемлемо

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +        long size = currentByteSize.addAndGet(entrySize);
гонки

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +        needToCompact.set(true);
кажется, этого недостаточно по ТЗ: что если flush никогда не будет вызван? или будет вызван через неделю?

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +                while (!currentlyFlushing.isEmpty()) ;
всё-таки busy-loop для настолько медленных операций не делают.

2022-05-11 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/MemorySegmentDao.java
> +                threadPool.shutdown();
эта команда вообще говоря не прожидает результата операции

2022-05-11 20:51 UTC, Artyomcool commented
Пофиксите пожалуйста конфликты, чтобы можно было вмержить.

2022-05-26 14:39 UTC, Artyomcool commented
Фиксов конфликтов нет, оценка проставлена не будет.

2022-05-26 14:39 UTC, closed without merging