Zhidkov Denis, Stage 5
polis-vk/2022-nosql-lsm pull request #144
Opened 2022-04-20 09:51 UTC by DenZhid

2022-04-20 10:15 UTC, DenZhid commented
Постарался реализовать способ compact(), при котором файлы помечаются и удаляются в close(). Помимо тестов, про которые отписались в чате так же не проходят ещё некоторые тесты. ru.mail.polis.BasicTest.testHugeData по timeout здесь, а на локальной из-за переполнения очереди на flush. Возможно большое количество upsert заставляет flush'иться данные, из-за чего метод отработать не успевает. ru.mail.polis.lutsenkodmitrii.Stage4IdempotentTest.compact - на локальной падал на моменте ожидания прохождения compact в методе close(). Скорее всего тоже проблемы с timeout. Делал и проверял на Windows.

2022-04-20 19:26 UTC, DenZhid commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            throw new InterruptedIOException();
CodeClimate говорит, что нужно прокидывать исключение в catch либо делать Thread.interrupt(). С использованием ExecutorService вроде как второй вариант реализовать не получиться, а InterruptedException прокинуть не получиться из-за переопределения close(), который не кидает его. Как быть?

2022-04-20 19:29 UTC, DenZhid commented on src/main/java/ru/mail/polis/deniszhidkov/DaoReader.java
> +                    start = middle + 1;
Не понимаю, почему CodeClimate считает, что это присваивание и на строке 116 бесполезны и просит их удалить.

2022-04-24 19:07 UTC, incubos requested changes
Не годится.

2022-04-24 19:07 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/BlockingMergeIterator.java
> +    private static final AtomicBoolean isBlocked = new AtomicBoolean(false);
Глобальный `static`? Нет, всё.

2022-04-25 10:16 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            throw new InterruptedIOException();
Почему с `Thread.interrupt()` не получится?

2022-04-25 10:36 UTC, DenZhid commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            throw new InterruptedIOException();
Согласен, уже получиться, просто ещё не внёс поправки с лекции

2022-04-25 10:37 UTC, DenZhid commented on src/main/java/ru/mail/polis/deniszhidkov/BlockingMergeIterator.java
> +    private static final AtomicBoolean isBlocked = new AtomicBoolean(false);
Да, уже понял, что плохое решение. Хотел просто блокировать все выданные итераторы после закрытия БД, но, поскольку поведение неопределно, то лучше просто не буду их трогать.

2022-04-25 10:38 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/DaoReader.java
> +                    start = middle + 1;
Похоже на багу в анализаторе. Выключил проверку.

2022-04-28 11:35 UTC, DenZhid commented
Исправил некоторые недочёты, однако все равно ещё остались проблемы. Отключил hugeDataTest (не уверен проблема ли это моей реализации или вообще, но слишком много данных не успевают быстро записаться). Также присутствует проблема с compact, которую мне никак не удаётся решить, поэтому хотелось бы получить возможно подсказку. В режиме отладки этот тест иногда проходил, но при этом иногда  зависал на моменте awaitTermination() в close(), ожидая завершения compact() в background. Если выполнять программу однопоточно, то тесты проходят. Также решил отказаться от своего варианта решения на Windows, поскольку наверное он не пройдёт (вариант с удалением файлов в close, а в compact помечаем их, чтобы не читать потом). Пока предположительно сделал вариант с перевызовом get.

2022-04-30 12:37 UTC, incubos requested changes
Решение не является корректным. Требуются существенные доработки.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +    private final AtomicBoolean isClosed = new AtomicBoolean(true);
Почему не `false`?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            addIterators(iteratorsQueue, currentState, from, to);
А если и здесь вылетит `IllegalStateException`?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                get(key);
Рекурсия? Не стоит.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            upsertLock.writeLock().lock();
Возможна гонка, когда несколько потоков дойдут сюда. О последствиях думать не хочется.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                backgroundFlush();
Этот вызов является синхронным и он заблокирует `upsert()` до момента записи последнего байта, верно? В чём здесь "background"?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        if (isNotFlushed()) {
Здесь возможна гонка при параллельном вызове `flush()`, т.е. несколько потоков пройдут дальше. О последствия рассуждать не очень хочется.
Одним из решений является замена `flushResult` на очередь задач (в смысле `ConcurrentQueue`) и корректная обработка задач, когда делать ничего не надо.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        flushResult = executor.submit(() -> {
В случае гонки здесь мы запомним только хронологически последний `flushResult`.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        // Во время compact ничего сфлашиться не может, поэтому количество reader неизменно
Чем именно это гарантируется?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            this.state = currentState.afterCompact(readers, writer);
Разве это корректно **менять** `this.state` под `readLock()`?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +    private void finishCompact() throws IOException {
Не помешало бы порефакторить этот метод, а также `backgroundCompact()`, хотя бы разбив их на отдельные небольшие методы, потому что довольно сложно воспринимается сплошное полотно кода с кучей комментариев. Возможно, эту логику стоит вынести в отдельный небольшой класс.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                backgroundCompact();
Здесь возможна гонка при запуске нескольких параллельных `compact`, если мы решим расширить наш `ExecutorService`, чтобы параллельно флашить и компактить, верно?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                backgroundCompact();
Или один поток -- это фундаментальное ограничение подхода?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                backgroundCompact();
Вижу, что на `backgroundCompact()` стоит `synchronized`, но это всё равно позволит добавлять ненужные задачи на compact, верно?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        if (isClosed.get()) {
Нужен `getAndSet(true)` иначе возможна гонка.

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        if (!currentState.inMemory.isEmpty()) {
Возможна гонка, потому что сразу после этой строчки CPU мог переключиться на середину метода параллельного `upsert()`, который вернётся успешно. Это приведёт к потере данных, верно?

2022-04-30 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        if (currentState.storageMemoryUsage.get() >= flushThresholdBytes) {
Почему бы не использовать результат `currentState.storageMemoryUsage.addAndGet()` выше?

2022-05-10 11:05 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +                return null;
Т.е. сообщаем, что ничего не нашли?

2022-05-10 11:05 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        // Если закроются readers снова вызовем поиск по всем readers, дождавшись завершения compact
Это может занять довольно много времени и эффективно заблокирует `get()`.

2022-05-10 11:05 UTC, incubos commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            upsertLock.writeLock().lock();
Гонка никуда не делась.

2022-05-10 11:11 UTC, incubos approved these changes
Решение стало лучше, но его трудно назвать корректным. 12 баллов.

2022-05-12 10:19 UTC, incubos commented
Остались замечания от Codeclimate.

2022-05-23 10:27 UTC, closed without merging