Baidiya Rosan HW5
polis-vk/2022-nosql-lsm pull request #145
Opened 2022-04-20 11:57 UTC by AirBurn0

- [x] compaction работает корректно
- [ ] auto-flush работает корректно
- [ ] get/upsert работают корректно

очень сложный таск, отладить не смог

2022-04-24 20:02 UTC, incubos requested changes
Есть существенные замечания.

2022-04-24 20:02 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private void executeFlush() {
Насколько я понял, это может вызываться из параллельных потоков и совершенно не очевидно, что всё будет работать корректно.

2022-04-24 20:02 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            FileUtils.compact(new MergingIterator(getFilesCollection(files, fileIndexes, null, null)), path);
Блокирующее решение не принимается.

2022-04-26 20:50 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +        if (onFlushCollection != null) {
Еще никогда Штирлиц не был так близок к провалу
Поправил

2022-04-26 20:50 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +        closed.set(true);
Действительно
Поправил

2022-04-26 20:51 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            return;
Не знаю, потому убрал

2022-04-26 20:52 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            FileUtils.compact(new MergingIterator(getFilesCollection(files, fileIndexes, null, null)), path);
Убрал

2022-04-26 20:57 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private void executeFlush() {
все операции под write lock, потому я слабо понимаю что может работать не корректно

2022-04-30 12:45 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private void executeFlush() {
Проблема в **отдельных** критических секциях и возможны гонки при их interleaving. Например, два потока (последовательно) пройдут первый write lock, а затем запустят `FileUtils.flush()`, но на последнем значении `onFlushCollection`.

2022-04-30 14:07 UTC, incubos requested changes
Пока не доделано и наблюдается возможность гонок.

2022-04-30 14:07 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            FileUtils.compact(new MergingIterator(getFilesCollection(files, fileIndexes, null, null)), path);
Что именно было убрано? `compact()` остался блокирующим же.

2022-04-30 14:07 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                list.add(new PeekIterator<>(temp.iterator(), 0));
Ровно такой же `order` как и у `collection`?

2022-04-30 14:07 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            lock.writeLock().lock();
Или 2 потока могут дойти сюда (`collection` не пустая), один из них зафлашит, а затем второй пойдёт флашить пустую коллекцию.

2022-05-03 19:10 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    public synchronized void compact() throws IOException {
@Artyomcool во время 9 занятия сделал `compact()` `synchronized` "compact точно можно делать долго, мучительно, и наверное даже под локом, и наверное это будет даже хорошо", потому мне не ясно в данном моменте

2022-05-03 19:34 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                list.add(new PeekIterator<>(temp.iterator(), 0));
теперь нет

2022-05-03 19:34 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            lock.writeLock().lock();
изменил

2022-05-03 19:53 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private void executeFlush() {
Если справлять кейс, то можно создать локальную копию, и работать с ней,
но вспоминая, зачем я вообще завел `onFlushCollection`, я не поддерживаю такую ситуацию (т.к. на диск пишется одновременно две коллекции данных, а видно только одну), потому бросаю исключение

2022-05-10 11:44 UTC, incubos approved these changes
Решение не является до конца корректным. Половина баллов * 1.2.

2022-05-10 11:44 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +        if (!(filesCount.get() > 1 || (filesCount.get() == 1 && !FileUtils.isCompacted(path, 1)))) {
Почему это проверяется не в `executeCompact()`. Если пользователь несколько раз вызовет `compact()`, то все кроме первого будут работать вхолостую, верно?

2022-05-10 11:44 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +        executor.submit(this::executeFlush);
Здесь возможна гонка, которая выльется в несколько запусков flush, потому что `onFlushCollection` выставляется в `executeFlush()` в отдельном потоке.

2022-05-12 10:18 UTC, incubos commented
Что с замечаниями от Codeclimate?

2022-05-23 10:27 UTC, closed without merging