Trofimov Artyom | Stage 5
polis-vk/2022-nosql-lsm pull request #147
Opened 2022-04-20 17:25 UTC by artem24630

2022-05-12 19:51 UTC, atimofeyev requested changes

2022-05-12 19:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/Flusher.java
> +                continue;
по мне так тут можно сразу  break делать, этот continue только путает, как буд-то бы еще есть смысл продолжать цикл

2022-05-12 19:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
>              data.put(entry.key(), entry);
здесь при паралельных вставках мы можем очень сильно переполнить размер заданного порога, это уязвимое место

2022-05-12 19:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        flushExecutor.shutdownNow();
поему shutdownNow()? может дать доработать текущим потокам?

2022-05-12 19:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        if (queueToFlush.size() == 2) {
тут наверное надо сравнивать с 1?

2022-05-23 18:26 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        flushExecutor.shutdownNow();
для compaction сделал, а для flusher у меня крутится в цикле, поэтому его приходится прерывать для завершения, поэтому shutdown не завершит его

2022-05-23 18:29 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        if (queueToFlush.size() == 2) {
ну у меня одна таблица флашится, при этом остается в очереди, чтобы из нее можно было брать данные, а вторая ждет флаша, поэтому тут 2

2022-05-23 18:53 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
>              data.put(entry.key(), entry);
а как можно исправить? Сначала считать размер, потом вставлять запись, если хватает места?

2022-05-23 18:53 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/Flusher.java
> +                continue;
исправил

2022-05-26 11:56 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        flushExecutor.shutdownNow();
это можно сделать более гуманным способом, например в цикле проверять статус о том что стоит уже остановиться

2022-05-26 11:57 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
>              data.put(entry.key(), entry);
да, сначала посчитать размер

2022-05-26 11:58 UTC, atimofeyev approved these changes
9 баллов

2022-05-26 12:10 UTC, closed without merging