Dmitree Maximenko - Stage5
polis-vk/2022-nosql-lsm pull request #151
Opened 2022-04-21 14:57 UTC by Dmitree-Max

2022-05-12 20:12 UTC, atimofeyev requested changes

2022-05-12 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +        } else if (spaceLeft >= entry.value().byteSize()) {
здесь при паралельной вставке мы можем вставлять в мапу даже если она уже переполнилась

2022-05-12 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +    private long spaceLeft;
работа с этим полем происходит без всяких примитивов синхронизации, т/е/ в многопоточной среде тут будет рандом

2022-05-12 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/Flusher.java
> +        } catch (IOException | InterruptedException exception) {
что же делать если упал эксепшен и флашер поток помер?

2022-05-13 10:14 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +        } else if (spaceLeft >= entry.value().byteSize()) {
Да, у меня написана на 30ой строке

2022-05-13 10:22 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/Flusher.java
> +        } catch (IOException | InterruptedException exception) {
Я бросал exception
            // can't throw because of code style check
            // I want to throw something like IllegalThreadStateException
но проверка стиля кода не пропускает это
Есть вариант - попробовать перезапустить flusher, но мы не знаем в каком состоянии предыдущий оставил базу данных. Например, он мог взять очередную таблицу для флаша из очереди и затем упасть, так ее и не зафлашив.

2022-05-13 10:23 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +    private long spaceLeft;
Добавил volatile. Это поможет синхронизировать значение между потоками, но жесткого лимита конечно все равно не получится.

2022-05-13 10:23 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/Compactor.java
> +            memorySegmentDao.dbTablesLock.readLock().lock();
Исправил

2022-05-13 19:41 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +    private long spaceLeft;
Давай тогда лучше добваиам Атомик, чтобы точно считать, раз уж тут это достаточно важная метррика и стоит ее считать точнее

2022-05-13 19:42 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/Flusher.java
> +        } catch (IOException | InterruptedException exception) {
Стоит либо все уронить, чтобы была видна ошибка, либо научиться восстанавливать, в общем проще думаю уронить и основной процесс

2022-05-13 19:44 UTC, atimofeyev requested changes

2022-05-13 19:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +        } else if (spaceLeft >= entry.value().byteSize()) {
Понятно что 100-процентной гарантии дать тяжело, но тут мы можем путем не сильных вложений сделать более точно, например мы можем сначала проверить что будет с размером если вставим, предполодив что мы увеличиваем на это число, проверить это так же стоит в каком-нидь потокобезопасном варианте, например через те же атомики

2022-05-13 19:52 UTC, atimofeyev requested changes

2022-05-13 19:52 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentDao.java
> +        flushLock.writeLock().lock();
почему бы не зафлашить стандартным флаш потоком и тут просто не дождаться его результата, было бы кстати проще это делать если бы это были не потоки которые работают отдельно, а например запускаемые задачи в экзекутере

2022-05-17 20:55 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/Flusher.java
> +        } catch (IOException | InterruptedException exception) {
Кинуть IllegalThreadStateException это же и есть уронить, если никто не перехватит его? Или вы предлагаете exit(-1) сделать?

2022-05-17 22:07 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +        } else if (spaceLeft >= entry.value().byteSize()) {
Исправил. Теперь поток вычитает из атомика число байт необходимое ему для ключа и значения. Если останется не меньше нуля то вставляет новую запись и затем проверяет, ьыла ли уже запись с таким ключом. Если была, то добавляет к атомику сэкономленное место в размере ключа и прошлого значения.

Если два потока будут вставлять одновременно с одним ключом, то они оба сначала вычтут. И если обоим хватает места на запись, то будет гонка за "прошлое значение". Поскольку мы не хотим синхронизировать вставку в таблицу, то далее мы прибавляем значение к атомику через CompareAndSet, чтоозволяет нам частично решить эту проблему. Теперь места не может стать больше, чем есть на самом деле, но может стать меньше.

2022-05-17 22:08 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +    private long spaceLeft;
Так и сделал. Она не синхронизирует потоки (кроме блокировки шины на атомиках, что должно быть быстро). Мы можем начать флашить до истечения размера, но точно не перегрузим таблицу.

2022-05-17 22:09 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentDao.java
> +        flushLock.writeLock().lock();
Исправил.

2022-05-17 22:18 UTC, Dmitree-Max commented
Не проходят только тесты из 2 дз (по времени). Об этом говорили на занятии. Они периодически проходят, но я думаю, что не стоит 10 раз пушить пустой коммит, чтобы рано или поздно они прошли. На профайлере смотрел. Там почти все время здесь
    @Override
    public String toString(MemorySegment memorySegment) {
        return memorySegment == null ? null : new String(memorySegment.toCharArray());
    }

Что оптимизировать нельзя..память дважды копируется. Сначала из сегмента создается массив путем копирования его в Хип, а потом из массива создается строка, что тоже, как я понимаю требует копирования в памяти.

2022-05-26 11:34 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/Flusher.java
> +        } catch (IOException | InterruptedException exception) {
упадет только Flusher поток, а надо уронить наш главный майн тоток

2022-05-26 11:54 UTC, atimofeyev approved these changes
9 баллов

2022-05-26 11:54 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +            data.put(key, entry);
put  уже возвращает предыдущее значение, можно сэкономить один гет

2022-05-26 12:09 UTC, closed without merging

2022-05-26 12:28 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemTable.java
> +            data.put(key, entry);
> 9 баллов

а эти 9 баллов умножаются на 1.5 из-за того, что я использовал MemorySegment?