Egor Ovsyannikov, Stage 5
polis-vk/2022-nosql-lsm pull request #154
Opened 2022-04-28 01:04 UTC by eatler

2022-04-28 16:35 UTC, incubos commented
Уже после дедлайна, поэтому вторая неделя, верно?

2022-04-28 16:41 UTC, eatler commented
@incubos сначала дедлайн был 20-го, поэтому сделал вторую неделю. Но и это залил в ночь на 28-е, то есть возможно технически 3-я неделя

2022-04-28 21:32 UTC, eatler commented
Добавил фоновый flush и проверку flushThresholdBytes

2022-04-30 15:56 UTC, incubos commented
Есть большое количество замечаний от CodeClimate.

2022-04-30 16:09 UTC, incubos requested changes
Текущее решение не является корректным. Есть множество замечаний и вопросов.

2022-04-30 16:09 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        while (!isDoneCompacting.get() || !isDoneFlushing.get()) {
Крутимся и жжём ядро?

2022-04-30 16:09 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        flushExecutor.shutdownNow();
У `ExecutorService` есть методы `shutdown()` и `awaitTermination()`.

2022-04-30 16:09 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        flush();
Лучше внести под `if` выше, иначе выглядит не совсем идиоматично.

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +    private ConcurrentNavigableMap<String, BaseEntry<String>> stringConcurrentSkipListMapPointer =
Написал

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            filePeekIterator.setBoundaries(null, null);
Получилось видимо так, что у каждого потока свой экземпляр FilePeekIterator при выполнении тестов.

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/FilePeekIterator.java
> +    public FilePeekIterator(Iterator<BaseEntry<String>> delegate, int generation) {
Сделал

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        return listOfIterators.isEmpty() ? Collections.emptyIterator() : new MergeIterator(listOfIterators);
Тогда при удалении (добавлении null в value) будет возвращаться этот элемент, т.к. проверка на удаленные элементы в MergeIterator

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +    public Deque<FilePeekIterator> getFromMemory(String from, String to) {
Переименовал в getFromFiles

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            memoryMap.put(entry.key(), entry);
Нужно сделать так, чтобы каждый BaseEntry по подному записывался в файл сразу в этом цикле?

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            file.setToBeDeleted(!file.isCompact());
Исправил

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        while (!isDoneCompacting.get() || !isDoneFlushing.get()) {
Исправил, используя awaitTermination

2022-05-05 23:10 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        flushExecutor.shutdownNow();
Исправил

2022-05-05 23:11 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        flush();
Вынес

2022-05-07 12:51 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
>      public void upsert(BaseEntry<String> entry) {
Использовал readWriteLock

2022-05-07 12:52 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        if (stringConcurrentSkipListMap.values().size() > 10_000) {
BufferedOutputStream работает быстрее, чем RandomAccessFile, когда количество записей большое. RandomAcessFile быстрее справляет с данными, которые много весят (длинные строки). Поэтому взял эту константу.

2022-05-07 12:52 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                    getFiles();
Данная функция добавляет в список файлов файл, который только что сфлашился, чтобы данные в нем были доступны далее.

2022-05-07 12:52 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                    stringConcurrentSkipListMapPointer = stringConcurrentSkipListMap;
Да. Сделал сохранение скопированных данных из указателя

2022-05-07 12:52 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        save(
То есть тоже его в flushExecutor?

2022-05-07 12:52 UTC, eatler commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +    private void save(Path path, ConcurrentNavigableMap<String, BaseEntry<String>> map, boolean isCompact)
Разбил

2022-05-10 12:06 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            filePeekIterator.setBoundaries(null, null);
Но это же некорректно. Можно было бы создавать экземпляры-копии явно.

2022-05-10 12:07 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
>      public void upsert(BaseEntry<String> entry) {
Теперь из-за взятия `writeLock()` все вставки работают последовательно.

2022-05-10 12:08 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            stringConcurrentSkipListMap = new ConcurrentSkipListMap<>(String::compareTo);
`writeLock()` теперь от этого спасает, но см. предыдущее замечание.

2022-05-10 12:10 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        if (stringConcurrentSkipListMap.values().size() > 10_000) {
Но мы же не знаем, сколько занимают сами элементы, а проверяем только их количество. И подобных литералов в коде быть не должно -- нужно заводить именованные константы. Лучше оставлять один способ записи, чтобы не поддерживать две кодовые базы.

2022-05-10 12:12 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                    getFiles();
Видимо, я плохо описал проблему. После каждого флаша мы берём список файлов и добавляем в `listOfFiles`. Из раза в раз. Одни и те же файлы. И никогда не удаляем. Верно?

2022-05-10 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                    stringConcurrentSkipListMapPointer = stringConcurrentSkipListMap;
Здесь работа с полем `stringConcurrentSkipListMapPointer` происходит из разных потоков и она не защищена.

2022-05-10 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                throw new RuntimeException();
Теперь мы просто игнорируем ошибку? И даже не логгируем?

2022-05-10 12:17 UTC, incubos commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            memoryMap.put(entry.key(), entry);
Например, так. В общем случае у нас нет столько памяти, чтобы поднять все данные с диска.

2022-05-10 12:20 UTC, incubos approved these changes
Множество замечаний всё ещё в силе. Решение не выглядит корректным и эффективным. С учётом второй недели 6 баллов.

2022-05-12 10:18 UTC, incubos commented
Замечания от Codeclimate не поправлены.

2022-05-15 16:32 UTC, eatler commented
@incubos Т.к. в ОК жду принятие в друзья, продублирую здесь вопрос
"Здравствуйте! Есть еще возможность получить баллы за 5 лабу исправлениями, если ПР еще на закрыт и было одно исправление?"

2022-05-15 19:33 UTC, incubos commented
> @incubos Т.к. в ОК жду принятие в друзья, продублирую здесь вопрос "Здравствуйте! Есть еще возможность получить баллы за 5 лабу исправлениями, если ПР еще на закрыт и было одно исправление?"

Нет возможности. Баллы проставлены. Дальше только через бонусные этапы.

2022-05-23 10:27 UTC, closed without merging