Kovalenko Pavel, stage 1
polis-vk/2022-nosql-lsm pull request #16
Opened 2022-02-27 07:42 UTC by PaaavelZ

2022-02-27 07:45 UTC, PaaavelZ commented
Локально все тестики проходят
![image](https://user-images.githubusercontent.com/76079492/155873409-a50063a4-6af7-45a1-8eba-81b80bb462c0.png)

2022-02-27 10:18 UTC, Artyomcool requested changes

2022-02-27 10:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new BaseEntry<>(entry.getKey(), entry.getValue());
Аллокация на каждом шаге итератора - дорогое удовольствие. Возможно есть альтернативы?

2022-02-27 11:09 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new BaseEntry<>(entry.getKey(), entry.getValue());
С сетом будет смотреться не очень, да и у него нет Entry. Выбор остаётся на мапе, у мапы нет такой цепочки методов, которые позволяют прийти к Entry<ByteBuffer>. А энтри нужен встроенный, чтобы мы его не создавали каждый раз. Возможно встроить этот энтри в мапу, то есть Map/<BB, Entry/<BB/>/>, но это затраты по памяти, или они не такие существенные?

2022-02-27 11:13 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new BaseEntry<>(entry.getKey(), entry.getValue());
Переделал

2022-02-28 14:23 UTC, Artyomcool requested changes

2022-02-28 14:23 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new DataIterator(data.headMap(to).entrySet().iterator());
Или можно просто values()

2022-02-28 14:24 UTC, Artyomcool requested changes

2022-02-28 14:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/pavelkovalenko/ByteBufferDaoFactory.java
> +        return data == null ? null : ByteBuffer.wrap(data.getBytes(Charset.defaultCharset()));
defaultCharset плохой выбор, лучше указывать конкретную кодировку

2022-02-28 19:13 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new DataIterator(data.headMap(to).entrySet().iterator());
Удивительно! И своего итератора не надо!

2022-02-28 19:18 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return new DataIterator(data.headMap(to).entrySet().iterator());
Исправлено

2022-02-28 19:18 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/test/pavelkovalenko/ByteBufferDaoFactory.java
> +        return data == null ? null : ByteBuffer.wrap(data.getBytes(Charset.defaultCharset()));
Исправлено

2022-03-03 17:14 UTC, merged