Kondraev Dmitry, Stage 1
polis-vk/2022-nosql-lsm pull request #18
Opened 2022-02-27 18:44 UTC by mariohuq

Кондраев Дмитрий. Вариант с MemorySegment, не проходит тест с 10 000 R/W операций по времени

2022-02-28 14:28 UTC, Artyomcool requested changes

2022-02-28 14:28 UTC, Artyomcool commented on build.gradle
> +tasks.withType(Test) { jvmArgs += incubatorArguments }
лучше оставлять пустую строку

2022-02-28 14:28 UTC, Artyomcool commented on build.gradle
> +tasks.withType(AbstractCompile) { options.compilerArgs += incubatorArguments }
лучше JavaCompile

2022-02-28 14:28 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +                .map(e -> new BaseEntry<>(e.getKey(), e.getValue()))
Аллокция на каждой итерации не лучшая идея.

2022-02-28 14:31 UTC, mariohuq commented on build.gradle
> +tasks.withType(Test) { jvmArgs += incubatorArguments }
OK

2022-02-28 14:31 UTC, mariohuq commented on build.gradle
> +tasks.withType(AbstractCompile) { options.compilerArgs += incubatorArguments }
OK

2022-02-28 14:42 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +                .map(e -> new BaseEntry<>(e.getKey(), e.getValue()))
Можно ли изменить требования к `Dao`, чтобы вместо `Entry<D>` просить `java.util.Map.Entry<D, D>`?
Существенная разница ведь только в том, что в `java.util.Map.Entry` есть метод `setValue`, но он же необязательный.
А если изменить, то отпадет необходимость оборачивать ключ и значение с помощью Entry.

2022-03-02 18:57 UTC, mariohuq commented on src/main/java/ru/mail/polis/test/dmitrykondraev/MemorySegmentDaoFactory.java
> +        return new String(data.toByteArray(), StandardCharsets.UTF_8);
Насколько я понимаю, узкое место по производительности здесь, но я слабо представляю себе, как можно здесь не аллоцировать массив байт, и потом не копировать его при создании строки. На ум приходят вещи типа C string, если что-то подобное есть в Java

2022-03-02 19:18 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +    private final ConcurrentNavigableMap<MemorySegment, BaseEntry<MemorySegment>> map =
Хранить пару ключ-значение в качестве значения мапы простое, но, мне кажется не самое элегантное решение проблемы с аллокациями. Но переписывать ConcurrentSkipListMap, Map,..., чтобы они использовали определенную нами Entry вместо java.util.Map.Entry тоже не хочется.

2022-03-05 10:25 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +    private final ConcurrentNavigableMap<MemorySegment, BaseEntry<MemorySegment>> map =
Исправил в bf4f1bc811ff09ac2d917b6d37027810658ae521

2022-03-05 10:25 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +                .map(e -> new BaseEntry<>(e.getKey(), e.getValue()))
Исправил в bf4f1bc811ff09ac2d917b6d37027810658ae521

2022-03-06 18:45 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +    private final ConcurrentNavigableMap<MemorySegment, BaseEntry<MemorySegment>> map =
Это решение вполне адекватно. Более того, ConcurrentSkipListMap внутри для entrySet действительно аллоцирует каждый раз новый объект-обёртку для каждого элемента, а вот для values() - нет.
И иногда это работает вменяемо, или даже бесплатно, если escape analyze после inline'а горячего куска кода смог выявить, что объект "расформировывается" и перестаёт использоваться сразу после аллокации, но я бы слишком сильно не расчитывал на это в такой глубокой иерархии вызовов.

2022-03-06 18:55 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/dmitrykondraev/MemorySegmentDaoFactory.java
> +        return new String(data.toByteArray(), StandardCharsets.UTF_8);
Тут есть опции ускориться, хотя я без детального профилирования не скажу, почему именно другой вариант работает настолько значительно быстрее.

2022-03-06 19:03 UTC, Artyomcool requested changes
Уберите удаление из build.gradle, после чего полный балл * 1.5 + 2 за RFC.

2022-03-06 19:03 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/InMemoryDao.java
> +                // (https://www.rfc-editor.org/rfc/rfc3629.txt, page 2)
+2 балла за ссылку на RFC, @incubos может ещё от себя докинет ;)

2022-03-06 23:25 UTC, mariohuq commented on build.gradle
> -
Эти строки дублируются: сравните с [:30](https://github.com/polis-vk/2022-nosql-lsm/blob/main/build.gradle#L30), [:34](https://github.com/polis-vk/2022-nosql-lsm/blob/main/build.gradle#L34), [:40](https://github.com/polis-vk/2022-nosql-lsm/blob/main/build.gradle#L40)

2022-03-07 14:45 UTC, mariohuq commented on build.gradle
> -
Я убрал изменение build.gradle в 359b6b244ff2b01edf7db2ec2b9d2b49c4cd80e8, вынес в #44

2022-03-10 12:18 UTC, Artyomcool commented
Полный балл, +2 за ссылку на RFC.

2022-03-10 12:18 UTC, merged

2022-03-10 13:14 UTC, mariohuq commented
> Полный балл, +2 за ссылку на RFC.

Не "полный балл * 1.5"?