Lutsenko Dmitrii Stage1
polis-vk/2022-nosql-lsm pull request #19
Opened 2022-02-28 11:07 UTC by LutsenkoDm

2022-02-28 14:29 UTC, Artyomcool requested changes

2022-02-28 14:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return new BaseEntry<>(tempEntry.getKey(), tempEntry.getValue());
Аллокация на каждой итерации не лучшая идея.

2022-02-28 15:58 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return new BaseEntry<>(tempEntry.getKey(), tempEntry.getValue());
Исправил

2022-03-03 17:15 UTC, Artyomcool approved these changes
Полный балл

2022-03-03 17:15 UTC, merged