All tasks are done. All tests pass. Dmitree Maximenko.
polis-vk/2022-nosql-lsm pull request #20
Opened 2022-02-28 20:53 UTC by Dmitree-Max

Stage 1, Maximenko Dmitree

2022-03-03 16:54 UTC, Artyomcool requested changes

2022-03-03 16:54 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        data.add(entry);
Если вставить два entry с одним ключом, но с разными значениями - будет дублирование

2022-03-06 19:24 UTC, Artyomcool requested changes

2022-03-06 19:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            new ConcurrentSkipListSet<>(new RecordNaturalOrderComparator());
Посмотрите внутрь реализации ConcurrentSkipListSet, возможно вы найдёте там для себя более элегантные решения.

2022-03-06 19:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +    static class BorderedIterator implements Iterator<BaseEntry<byte[]>> {
Дело в том, что это всё не решает основную проблему.
У вас копятся дубликаты. А при вставке двух элементов с разными значениями "последним" будет не тот, кто был вставлен последним, а кто-то случайный.

2022-03-06 19:35 UTC, Artyomcool commented
Не забудьте проставить week = 2

2022-03-08 19:55 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        data.add(entry);
Решил эту проблему удалением значения перед вставкой, к сожалению у множеств нету флага для метода add(overwrite=true). 

Изначально я выбирал между словарем и множеством и выбрал множество только из-за того, что подумал, что все остальные сделают через словарь:)

2022-03-08 19:57 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            new ConcurrentSkipListSet<>(new RecordNaturalOrderComparator());
Как я понял вы намекаете на это..
```
    /**
     * The underlying map. Uses Boolean.TRUE as value for each
     * element.  This field is declared final for the sake of thread
     * safety, which entails some ugliness in clone().
     */
    @SuppressWarnings("serial") // Conditionally serializable
    private final ConcurrentNavigableMap<E,Object> m;
```

согласен, получается что множество - обертка над словарем и проще просто было бы использовать его.

2022-03-08 20:01 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +    static class BorderedIterator implements Iterator<BaseEntry<byte[]>> {
Я бы даже сказал, что последним будет именно "первый". Решил проблему удалением перед вставкой. 

Тут также стоит отметить, что "гонки" между процессами не произойдет, потому что да, оба процесса могут удалить, а потом вставлять, и произойдет вставка с уже существующим значением, но поскольку мы изначально не имели никаких гарантий, какое из значений должно быть зафиксированно в DAO, то гонкой это не являетя.

2022-03-10 12:33 UTC, Artyomcool approved these changes
Полный балл за вычетом:
2 балла за переусложнение и гонку (считаю это одной общей проблемой).

2022-03-10 12:33 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            byte[] key1 = e1.key();
Arrays.compare

2022-03-10 12:33 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        data.add(entry);
> все остальные сделают через словарь

"Назло соседу отморожу уши?")

Не понял, о каком add(overwrite) вы говорите, множество - это та структура, которая всегда "overwrite".
Сейчас кстати смотрю, и не понимаю, откуда я ожидал увидеть дублирование, возможно изменился компаратор? Или возможно дублирования и не было.

И гонка у вас тут есть, несмотря на то, что вам хотелось бы, чтобы её не было:
1. поток А удалил и вставил данные
2. поток В удалил данные
3. поток С начал чтение данных - и не увидел их (а должен был увидеть либо значение от потока А, либо будущее значение от потока В)
4. поток В вставил данные

Как разобраться есть ли гонка: если между двумя операциями существует видимое состояние, отличное от начального и конечного, гонка есть.

2022-03-10 12:33 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +    static class BorderedIterator implements Iterator<BaseEntry<byte[]>> {
Вы выбрали сложный путь, который в итоге запутает и ревьюера, и вас. Не надо так делать.

2022-03-10 12:37 UTC, merged

2022-03-10 15:49 UTC, incubos commented
Не нашёл студента в ведомости.