Домашнее задание 1
polis-vk/2022-nosql-lsm pull request #3
Opened 2022-02-24 23:04 UTC by Sanerins

Косницкий Александр
Все тесты в проходят

2022-02-24 23:50 UTC, Artyomcool commented
Я всё поправил!
Больше тесты не проходят!

2022-02-24 23:51 UTC, Artyomcool commented
Напомните поставить +балл за аватарку

2022-02-25 00:16 UTC, Sanerins commented
Меня так просто не остановить, теперь все снова проходит!

2022-02-25 00:30 UTC, Artyomcool commented
Ещё немного поправил. Снова не проходит.

2022-02-25 00:33 UTC, Artyomcool requested changes

2022-02-25 00:33 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/InMemoryDao.java
> +            return storage.tailSet(new BaseEntry<>(from, null), true).iterator();
В целом это не страшно, но есть способы обойтись без аллокации new BaseEntry.

2022-02-25 00:33 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/InMemoryDao.java
> +        return storage.subSet(new BaseEntry<>(from, null), true, new BaseEntry<>(to, null), false)
Вернусь к тезису: можно обойтись без аллокации new BaseEntry.
Использование null в качестве значения явно намекает, что что-то идёт не так. Возможно есть другие опции? Например, более подходящая коллекция для поиска по ключу.

2022-02-25 00:34 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/InMemoryDao.java
> +        return storage.subSet(new BaseEntry<>(from, null), true, new BaseEntry<>(to, null), false)
Рекомендую подсмотреть внутрь реализации ConcurrentSkipListSet.

2022-02-25 01:33 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/InMemoryDao.java
> +            return storage.tailSet(new BaseEntry<>(from, null), true).iterator();
Теперь мы используем `map` вместо `set`, поэтому стало покрасивее

2022-02-25 01:37 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/InMemoryDao.java
> +        return storage.subSet(new BaseEntry<>(from, null), true, new BaseEntry<>(to, null), false)
Да, я сейчас посмотрел - `set` действительно не имел никакого смысла, ведь оказывается он просто юзал внутри себя мапу, заполняя ёё поле `value` просто напросто `true`
Теперь БД стало выглядить более логично, но так как нам нужна `BaseEntry`, а не `Map.Entry` пришлось немного повозиться с итератором, дабы сделать для него "обертку". Возможно это не самое эффективное решение, но вроде как работу свою делает

2022-02-25 06:09 UTC, Artyomcool approved these changes

2022-02-25 06:10 UTC, merged

2022-02-25 06:15 UTC, Artyomcool commented
На занятии покажу, как можно улучшить.
Полный балл + 20% за ByteBuffer + 002 за аватарку (на самом деле за оперативность).

2022-02-25 07:30 UTC, Sanerins commented
Понял вас, большое спасибо! Особенно за такое глубокое уважение к аниме!)