Egor Ovsyannikov, Stage1
polis-vk/2022-nosql-lsm pull request #30
Opened 2022-03-02 20:40 UTC by eatler

2022-03-02 20:45 UTC, eatler commented
Ругается на пустые методы в пакете другого человека. Не стал исправлять и комитить в его пакет на всякий случай.

2022-03-06 20:02 UTC, Artyomcool commented
Разрешите пожалуйста конфликты, выглядит, что у вас какие-то лишние изменения в ветке.

2022-03-06 20:12 UTC, Artyomcool approved these changes
Полный балл, после того как разберетесь с конфликтами и проставите week = 2

2022-03-08 17:27 UTC, eatler commented
> 

Исправил

2022-03-10 12:46 UTC, Artyomcool requested changes

2022-03-10 12:46 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/alexanderkiselyov/ByteArrayDaoFactory.java
> -@DaoFactory
изменения не выглядят полезными

2022-03-10 12:46 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/alexanderkosnitskiy/ByteBufferDaoFactory.java
> -@DaoFactory
изменения не выглядят полезными

2022-03-10 13:18 UTC, Artyomcool requested changes

2022-03-10 13:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/alexanderkosnitskiy/ByteBufferDaoFactory.java
> +    public Dao<ByteBuffer, BaseEntry<ByteBuffer>> createDao() {
Опять неполезные изменения в чужих файлах)

2022-03-11 13:42 UTC, Artyomcool approved these changes

2022-03-11 13:42 UTC, merged

2022-03-11 13:43 UTC, Artyomcool commented
Полный балл * 1.2

2022-03-11 13:59 UTC, incubos commented
Не нашёл автора в ведомости.