Kovalenko Pavel, stage 2
polis-vk/2022-nosql-lsm pull request #32
Opened 2022-03-04 14:40 UTC by PaaavelZ

2022-03-04 16:11 UTC, PaaavelZ commented
Ко мне в сборку попадают варнинги от других людей, поэтому не собирается
![image](https://user-images.githubusercontent.com/76079492/156798865-b8c1cf0c-020c-4f91-b6b3-c645402e563f.png)

2022-03-04 16:17 UTC, PaaavelZ commented
Но тесты проходят
![image](https://user-images.githubusercontent.com/76079492/156799661-dd3bfc9d-0bb8-4edf-8743-f2bb495fbe21.png)

2022-03-05 11:40 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/pavelkovalenko/ByteBufferDaoFactory.java
> +    public Config extractConfig(Dao<ByteBuffer, BaseEntry<ByteBuffer>> dao) {
не надо определять эти методы

2022-03-05 12:16 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/test/pavelkovalenko/ByteBufferDaoFactory.java
> +    public Config extractConfig(Dao<ByteBuffer, BaseEntry<ByteBuffer>> dao) {
Удалил всё лишнее, спасибо!

2022-03-05 12:29 UTC, Artyomcool requested changes

2022-03-05 12:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
лучше выбрасывать исключение дальше

2022-03-05 12:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
лучше выбрасывать исключеине дальше

2022-03-05 12:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        this.pathToFile = config.basePath().toString() + FileSystems.getDefault().getSeparator() + "file1.txt";
path.resolve(subpath) делает именно это, только надёжно

2022-03-05 12:33 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
побоялся, что тесты рухнут

2022-03-05 12:33 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
аналогично, сейчас исправлю

2022-03-05 12:36 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
+ нарушение сигнатуры метода и всех остальных override'нных

2022-03-05 12:37 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
![image](https://user-images.githubusercontent.com/2193076/156883302-08eed8cd-600f-46d9-b101-c0a5abe33667.png)

2022-03-05 12:46 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        } catch (IOException e) {
А что скажете про этот кач? Оставить? Или тоже снести? Просто если сносить, то придётся эксепшн во всю иерархию наследования вносить. Наверно, это плохо, да?
![image](https://user-images.githubusercontent.com/76079492/156883638-b7a222ba-758b-4005-b0c5-cbd6acd7e2b0.png)

2022-03-05 12:54 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
Eсли сносить, то придётся эксепшн во всю иерархию наследования вносить 
![image](https://user-images.githubusercontent.com/76079492/156883937-19760e36-2bc1-4b66-bc0e-8a057f155dd5.png)
![image](https://user-images.githubusercontent.com/76079492/156883952-189c6060-aea5-4f4d-8620-a456e8e4aa47.png)

2022-03-05 12:56 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
На данный момент конструктор родительский, судя по сигнатуре, не кидает исключения IOException
![image](https://user-images.githubusercontent.com/76079492/156884038-b74f468d-8b4a-4f46-bd7c-96a2fdc1460b.png)

2022-03-08 12:45 UTC, PaaavelZ commented
Этот PR переехал по адресу https://github.com/polis-vk/2022-nosql-lsm/pull/48

2022-03-08 12:46 UTC, closed without merging