Kosnitskiy Alexander, Stage 2
polis-vk/2022-nosql-lsm pull request #33
Opened 2022-03-04 16:06 UTC by Sanerins

Вроде как работает и все тесты проходит!

2022-03-06 20:51 UTC, Artyomcool approved these changes
Реализация максимально далека от того, что мы хотим увидеть тут позже, но для этого этапа будет зачтено.
Рекомендую сразу заняться переходом в файловую структуру, в которой вы сможете читать только то, что нужно, иначе будут сложности вложиться в дедлайн на следующих этапах.

2022-03-06 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        Iterator<BaseEntry<ByteBuffer>> iterator = get(key, null);
или просто memory.get(key)

2022-03-06 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        } catch (FileNotFoundException | ClassNotFoundException e) {
ClassNotFoundException оО

2022-03-06 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +            e.printStackTrace();
Не надо съедать исключения

2022-03-06 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        if (memory.size() >= 50000) {
мы действительно позже будем использовать такую логику, но не сейчас и не в таком формате

2022-03-06 20:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +            currentFile = str.length;
все костыли со временем падают

2022-03-06 23:12 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        Iterator<BaseEntry<ByteBuffer>> iterator = get(key, null);
А ведь действительно...
Засмотрелся на изначальную имплементацию в `Dao` и не заметил очевидного упращения)

2022-03-06 23:13 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        } catch (FileNotFoundException | ClassNotFoundException e) {
Больше такого нет)

2022-03-06 23:13 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +            e.printStackTrace();
Код сел на диету по исключениям, но в паре мест все же кушает, но не так радикально

2022-03-06 23:14 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        if (memory.size() >= 50000) {
Буду исправлять

2022-03-06 23:14 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +            currentFile = str.length;
Буду исправлять

2022-03-06 23:27 UTC, Sanerins commented
Сделал ряд улучшений, продолжу улучшения чуть позже:
1) Написал собственные `Reader` и `Writer` для БД
2) Оптимизировал `InMemory` часть с учетом нашего разговора на уроке насчет того, что хранение `BaseEntry` как `value` не повышает количество потр. памяти, однако повышает производительность, ибо не надо выделять память для создания `BaseEntry` в итераторах

2022-03-07 02:19 UTC, Sanerins commented
Реализовал систему бинарного поиска по около ~2000(зависит от настроек и количества элементов) отсортированным `.seg` файлам, в которых содержится по 100 отсортированных entries в каждом

2022-03-07 02:32 UTC, Sanerins commented
Так же выделил константы, чтобы было легче играться с базой
`IN_MEMORY_SIZE` - определяет сколько элементов в целом будет в каждой из подпапок, в которую мы будем сгружать все маленькие файлы
`CHUNK_SIZE` - определяет размер каждого из маленьких файлов
`FILE_EXTENSION` - у каждой уважающей себя датабазы должно быть свое собственное проприетарное расширение у файлов, здесь можно его задать

При создании я изначально прочитал, что во многих датабазах каждый файлик вообще представляет лишь одно единственное `entry` в базе, поэтому решил реализовать что-то похожее, ибо настоящий бинарных поиск по самому файлу сделать очень сложно и получается лишь с зафиксированными размерами каждой их записей, чтобы можно быо предугадать куда прыгать. Зато настоящий бинарный поиск по файлам с маленьким количеством информации внутри сделать получилось

2022-03-08 17:33 UTC, Sanerins commented
Теперь бинарный поиск идет по файлу, а файл лишь только один
Код намного чище и понятнее, не глотаю исключения
ByteBuffer читается как ByteBuffer, а не массив байтов

2022-03-10 12:59 UTC, Artyomcool requested changes
Идея похвальная, но:
1. При наличиии 0x1e в ключе/значении, будет грустно.
2. Как уже было сказано, если вы используете ByteBuffer в качестве хранилища массива байт, повышающего коэффициента не будет.

2022-03-10 12:59 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoWriter.java
> +    private static final char DELIMITER = 0x1e;
Не вижу, что вы каким-то образом escape'ите последовательность, а значит, если в ключе/значении будет 0x1e, то мы приехали.

2022-03-10 12:59 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        try (DaoWriter out = new DaoWriter(config.basePath() + File.separator + FILE)) {
basePath().resolve(FILE)

2022-03-10 12:59 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoReader.java
> +                return 404;
рекомендую обойтись без волшебных констант, у меня нет желания угадывать их назначение.

2022-03-10 14:27 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoWriter.java
> +    private static final char DELIMITER = 0x1e;
Решу проблему, наверное перейду на индексы, ибо данный способ был предложен в беседе и при этом он не имеет данного  недостатка, ибо экранирование, наверное, займет довольно много времени на чтении/записи, а это уж точно не будет приятно

2022-03-10 14:27 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/PersistenceDao.java
> +        try (DaoWriter out = new DaoWriter(config.basePath() + File.separator + FILE)) {
Исправлю данную оплошность

2022-03-10 14:28 UTC, Sanerins commented on src/main/java/ru/mail/polis/alexanderkosnitskiy/DaoReader.java
> +                return 404;
Это старенький метод, он уже не используется - использовал его для бинарного поиска среди файлов - прошлый вариант реализации

2022-03-10 15:31 UTC, Sanerins commented
Исправил бинарный поиск, теперь он на индексах, успел до пары)

2022-03-14 15:09 UTC, Artyomcool approved these changes
Полный балл + 30% за бинарный поиск

2022-03-18 12:24 UTC, merged