stage 2 first try
polis-vk/2022-nosql-lsm pull request #35
Opened 2022-03-05 10:13 UTC by VladislavFetisov

2022-03-10 13:35 UTC, Artyomcool requested changes
Очень хорошая и достойная работа, но не надо использовать ByteBuffer, если работаете с MemorySegment.
Поправьте, и будет возможность получить максимальный балл * 1.8 (1.5 за MS, 0.3 за бинарный поиск раньше срока).

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/InMemoryDao.java
> +        try (FileChannel channel = FileChannel.open(table);
Files.size(path)

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/InMemoryDao.java
> +            throw new UncheckedIOException(e);
Не надо так делать: добавьте исключение в сигнатуру конструктора.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/InMemoryDao.java
> +        Files.deleteIfExists(indexTemp);
Вот это опасное решение: вы теряете данные между двумя моментами времени. Если после удаления файла произойдет сбой любого рода, включая потерю питания, то данные утрачены.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/InMemoryDao.java
> +        Files.deleteIfExists(indexTemp);
Прямо сейчас за это никаких штрафов не полагается, обратите внимание в будущем.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/InMemoryDao.java
> +        channel.write(value.asByteBuffer());
Если пользуетесь MemorySegment как хранилищем ByteBuffer, то множителя 1.5 не будет. Даже 1.2 не будет, потому что жирноватая аллокация происходит, причем очень часто.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/Utils.java
> +            long middle = l + r >>> 1;
тут, кажется, что-то странное.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/Utils.java
> +            long middle = l + r >>> 1;
нет, это, оказывается, работает корретно, но я бы рекомендовал взять l + r в скобки, чтобы не приходилось проверять порядок операторов.

2022-03-10 13:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/vladislavfetisov/Utils.java
> +        return valueLengthSegment.asByteBuffer().getLong();
Очень много мусора.

2022-03-10 13:35 UTC, Artyomcool commented on src/test/java/ru/mail/polis/PersistentTest.java
> +
что-то не полезное

2022-03-10 14:34 UTC, VladislavFetisov commented on src/test/java/ru/mail/polis/PersistentTest.java
> +
Случайно вышло

2022-03-14 15:14 UTC, Artyomcool approved these changes
Полный балл * 1.8 (30% за бинарный поиск раньше срока, 50% за MS)

2022-03-18 12:31 UTC, Artyomcool requested changes

2022-03-18 12:31 UTC, Artyomcool commented on src/test/java/ru/mail/polis/PersistentTest.java
> +
Ну так надо прибрать?

2022-03-20 15:56 UTC, merged