Saskov Lev: Stage 2
polis-vk/2022-nosql-lsm pull request #36
Opened 2022-03-05 11:30 UTC by levs2001

Тесты проходит

2022-03-07 09:43 UTC, Artyomcool requested changes

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            for (int i = 0; i < ENTRYS_PORTION && stream.available() >= BYTES_IN_INT; i++) {
А зачем вы поднимаете в память данные, которые с высокой вероятностью вам не потребуются?

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            e.printStackTrace();
Не проглатывайте исключения

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            ByteBuffer bufferToWrite = ByteBuffer.allocate(ALLOC_SIZE);
А если данных будет больше, чем 2кб?

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        return new BaseEntry<>(ByteBuffer.wrap(key), ByteBuffer.wrap(value));
Побайтовое чтение из файла не будет засчитано за ByteBuffer.

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        }
Не глотайте исключения

2022-03-07 09:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        if (entrys.containsKey(key)) {
Так делать принципиально нельзя.
1. Вы два раза осуществляете поиск ключа
2. Можно получить состояние гонки, если между этими операциями сущность будет удалена из entries.
Прямо сейчас пункт 2 невозможен, но в будущем будут проблемы.

get возвращает null, если запись не найдена, этим и нужно пользоваться

2022-03-08 20:25 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            for (int i = 0; i < ENTRYS_PORTION && stream.available() >= BYTES_IN_INT; i++) {
Исправил

2022-03-08 20:25 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +            e.printStackTrace();
Исправил

2022-03-08 20:26 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        if (entrys.containsKey(key)) {
Исправил

2022-03-08 20:28 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        }
Исправил

2022-03-09 14:18 UTC, levs2001 commented
Сделал нормальное чтение из файла (как положено на ByteBuffer),  добавил файл индексации и сделал бинарный поиск

2022-03-09 14:18 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        return new BaseEntry<>(ByteBuffer.wrap(key), ByteBuffer.wrap(value));
Переделал

2022-03-18 12:44 UTC, Artyomcool approved these changes
Полный балл, надбавка за 20% за дихотомию (а не 30%, т.к. не оптимально).

2022-03-18 12:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +    public InMemoryDao() {
возможно он просто не нужен?

2022-03-18 12:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +                entryStartPos += bytesC;
нет, переполнение не возможно, у вас раньше кончатся все диски мира

2022-03-18 12:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        return new BaseEntry<>(ByteBuffer.wrap(key), ByteBuffer.wrap(value));
не вижу, всё ещё всё загружено в память

2022-03-18 12:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/levsaskov/InMemoryDao.java
> +        while ((!curEntry.key().equals(key))
два сравнения за круг, вместо одного, compareTo уже даёт корректный результат

2022-03-18 12:46 UTC, merged