Kiselyov Alexander, Stage 2
polis-vk/2022-nosql-lsm pull request #37
Opened 2022-03-05 11:52 UTC by AlexanderKiselyov

2022-03-07 09:56 UTC, Artyomcool requested changes

2022-03-07 09:56 UTC, Artyomcool commented on build.gradle
> -    options.compilerArgs += ["--add-modules", "jdk.incubator.foreign"]
Изменения не выглядят полезными

2022-03-07 09:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            e.printStackTrace();
Не проглатывайте исключения

2022-03-07 09:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            e.printStackTrace();
Не проглатывайте исключения

2022-03-07 09:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(config.basePath().resolve(FILE_NAME)));
Кажется я всё сделал для того, чтобы данные физически не могли поместиться в память. Посмотрю как улучшить тесты, но пока ещё раз скажу: данные целиком в память поднимать запрещено.

2022-03-07 09:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        Iterator<BaseEntry<byte[]>> iterator = get(key, null);
Или просто pairs.get(key)

2022-03-10 13:38 UTC, Artyomcool requested changes
Поправьте замечания, после чего полный балл.

2022-03-10 13:38 UTC, Artyomcool commented on build.gradle
> -    options.compilerArgs += ["--add-modules", "jdk.incubator.foreign"]
Всё ещё не выглядят полезными.

2022-03-10 13:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        File[] files = config.basePath().toFile().listFiles();
Обычно, если вы пользуетесь Path, File вам не нужен.

2022-03-10 13:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            upsert(entryFound);
Интересное решение, но так делать напрямую, к сожалению нельзя: возникают гонки.
Если новое значение с таким же ключом будет вставляться, пока вы производите поиск в файле, вы его перезапишите.

2022-03-10 15:37 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +        File[] files = config.basePath().toFile().listFiles();
Исправил

2022-03-10 15:37 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/InMemoryDao.java
> +            upsert(entryFound);
Исправил

2022-03-11 07:12 UTC, AlexanderKiselyov commented on build.gradle
> -compileJava {
Эти настройки не нужны в моей работе, но при запуске тестов возникают ошибки из-за того, что данная библиотека используется в других работах

2022-03-18 12:48 UTC, Artyomcool requested changes

2022-03-18 12:48 UTC, Artyomcool commented on build.gradle
> -compileJava {
Эти изменения не приносят пользы, но приносят вред. Не понимаю, зачем вы это коммитите.

2022-03-18 12:48 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/alexanderkiselyov/ByteArrayDaoFactory.java
> +@DaoFactory(stage = 2, week = 1)
Поднимите week до 3

2022-03-18 12:50 UTC, AlexanderKiselyov commented on build.gradle
> -compileJava {
Это какой-то баг, наверное, потому что данные команды должны быть написаны дважды в этом файле, чтобы не было изменений

2022-03-18 12:54 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/test/alexanderkiselyov/ByteArrayDaoFactory.java
> +@DaoFactory(stage = 2, week = 1)
Исправил

2022-03-18 13:00 UTC, Artyomcool requested changes

2022-03-18 13:00 UTC, Artyomcool commented on build.gradle
> -compileJava {
Нет, это не баг.
Это лишние изменения.
Пока это будет в PR, он не будет вмёржен.

2022-03-18 13:04 UTC, Artyomcool requested changes

2022-03-18 13:04 UTC, Artyomcool commented on build.gradle
> +    checkstyleTest.enabled = true
и это

2022-03-18 13:04 UTC, Artyomcool commented on build.gradle
> -
и это

2022-03-18 13:10 UTC, AlexanderKiselyov commented on build.gradle
> -
Можете подсказать, что не так с этой строкой?

2022-03-18 13:11 UTC, Artyomcool requested changes

2022-03-18 13:11 UTC, Artyomcool commented on build.gradle
> -
Не так не со строкой, а с тем, что нужно просто отревертить изменения в файле. Возможно, вам стоит ознакомиться с тем, как работать с GIT.

2022-03-18 16:41 UTC, Artyomcool approved these changes

2022-03-18 16:41 UTC, Artyomcool commented
Полный балл

2022-03-18 16:42 UTC, merged