Lutsenko Dmitrii Stage 2
polis-vk/2022-nosql-lsm pull request #38
Opened 2022-03-05 12:12 UTC by LutsenkoDm

2022-03-07 10:10 UTC, Artyomcool requested changes
В целом решение для данного этапа рабочее.
Но вы зря так усложнили многие вещи, особенно с многопоточностью (я даже не стал проверять её корректность), т.к. для дальнейших этапов такой подход просто не будет работать.

2022-03-07 10:10 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        }
Не нужно выплёвывать исключения в стандартный поток

2022-03-07 10:10 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            e.printStackTrace();
Не надо проглатывать исключения

2022-03-07 10:10 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        try (BufferedReader bufferedReader = Files.newBufferedReader(keyRangesPath, UTF_8)) {
Ну в теории это-то можно и в память поднять.

2022-03-07 10:10 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        List<BaseEntry<String>> dataList = data.values().parallelStream().toList();
new Arraylist(data.values) намного быстрее и понятнее

2022-03-08 14:43 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        }
Все исключения теперь логируются

2022-03-08 14:43 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            e.printStackTrace();
Все исключения теперь логируются

2022-03-08 14:44 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        List<BaseEntry<String>> dataList = data.values().parallelStream().toList();
Исправил

2022-03-08 14:47 UTC, LutsenkoDm commented
> В целом решение для данного этапа рабочее. Но вы зря так усложнили многие вещи, особенно с многопоточностью (я даже не стал проверять её корректность), т.к. для дальнейших этапов такой подход просто не будет работать.

В чем проблема многопоточности конкретно, я ее использовал только для того чтобы разбить на файлы и записывать в одном потоке маленький файл. То есть на один dao должен быть 1 файл или нет?

2022-03-10 13:47 UTC, Artyomcool requested changes

2022-03-10 13:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +    }
это очень вредные строчки

2022-03-10 13:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        }
Намного лучше пробрасывать исключения туда, где им место

2022-03-10 13:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return objectInputStream.readObject();
Стандартные средства сериализации Java ОЧЕНЬ медленные. Не нужно ими пользоваться.

2022-03-10 20:21 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return objectInputStream.readObject();
Сделал без этого

2022-03-10 20:22 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +    }
убрал

2022-03-18 12:58 UTC, Artyomcool approved these changes
Переусложненный код, поэтому наполнен ошибками и неоптимальностью.
-4 балла от максимума.

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/lutsenkodmitrii/StringDaoFactory.java
> +@DaoFactory(stage = 2, week = 1)
Поднимите week до 3

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            throw new RuntimeException("Load Key Ranges map fail", e);
Такими оборачиваниями вы теряете возможность обрабатывать ошибки там, где им место, соответственно их типу.

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            int currentKeyLength;
а зачем выносить эти декларации?
это не упрощает код, т.к. приходится смотреть сразу в два места.

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            logger.log(Level.SEVERE,
Вы оставляете залогированную ошибку и код в непонятном состоянии, вместо того, чтобы пробрасывать ошибку дальше.

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            countDownLatch.countDown();
Таким образом, если возникает исключение, вы не делаете countDown, а значит повисаете в неконсистентном состоянии.

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                stingToWrite = baseEntry.key() + baseEntry.value() + '\n';
Аллоцирует мусор

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                    bufferedFileWriter.flush();
Зачем?

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            bufferedFileWriter.write(intToCharArray(subList.size()));
аллоцирует мусор

2022-03-18 12:58 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            // В следующей версии эту многопоточку уберу скорее всего поэтому и это уйдет
поэтому за эту версию вы получите снижение баллов

2022-03-18 12:59 UTC, merged