Baidiya Rosan HW2
polis-vk/2022-nosql-lsm pull request #39
Opened 2022-03-05 17:04 UTC by AirBurn0

О нет мое heap memory

2022-03-10 13:51 UTC, Artyomcool requested changes
При текущем подходе множитель 1.2 не предусмотрен.

2022-03-10 13:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
> +    }
Оно конечно non-heap, но пользы нет.

2022-03-10 13:51 UTC, Artyomcool commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
> +        byte[] array = buffer.array();
Ну и вы всё ещё продолжаете обращаться с ByteBuffer'ом как с массивом байт.

2022-03-12 14:15 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
> +        byte[] array = buffer.array();
> Ну и вы всё ещё продолжаете обращаться с ByteBuffer'ом как с массивом байт.

Изменил подход

2022-03-12 14:20 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
> +    }
Переписал эту часть

2022-03-14 15:27 UTC, Artyomcool approved these changes
Полный балл

2022-03-14 15:27 UTC, Artyomcool commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
> +                    buffer = ByteBuffer.allocate(size);
ну можно ведь хотя бы если capacity < size?

2022-03-18 13:05 UTC, merged