Pobedonostsev Kirill, stage 1
polis-vk/2022-nosql-lsm pull request #4
Opened 2022-02-25 02:26 UTC by Pobedos

2022-02-25 06:12 UTC, Artyomcool requested changes

2022-02-25 06:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            temp = set.headSet(new BaseEntry<>(to, null), false);
Можно обойтись без new BaseEntry, посмотрите внутрь ConcurrentSkipListSet - это поможет выбрать альтернативную коллекцию.

2022-02-25 07:35 UTC, Artyomcool commented
Тесты перестали проходить не по вашей вине, я разберусь.

2022-02-25 08:29 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            temp = set.headSet(new BaseEntry<>(to, null), false);
Хм, спасибо. Не знал, что ConcurrentSkipListSet работает внутри на мапе, честно сказать даже удивился

2022-02-25 20:08 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            temp = set.headSet(new BaseEntry<>(to, null), false);
Предлагаю посмотреть идею: [ConcurrentSkipList](https://en.wikipedia.org/wiki/Skip_list)
Если понять её достаточно глубоко, то станет довольно очевидно, что нет никакого смысла не хранить дополнительно ссылку на значение по ключу - экономии нет. А значит нет смысла в двух реализациях.

2022-02-26 01:13 UTC, Artyomcool approved these changes

2022-02-26 12:43 UTC, Pobedos commented
Пробовал использовать и компаратор для массива байт и для буффера, и даже свой пробовал написать. А в итоге убрал банально сохранение ссылки после получения рейнжа и помогло( Однако на Винде работает без проблем

2022-02-27 09:37 UTC, Artyomcool requested changes

2022-02-27 09:37 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
Аллокация на каждом сравнении - это дорого.

2022-02-27 09:38 UTC, Artyomcool commented
> Однако на Винде работает без проблем

У MemorySegment не должно быть проблем с виндой, в теории.

2022-02-27 09:45 UTC, Artyomcool requested changes

2022-02-27 09:45 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
Именно поэтому сейчас тесты на тестовом сервере проходят раз через раз.

2022-02-27 09:48 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
Понял, буду пробовать

2022-02-27 09:50 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
Ошибочка, не поэтому, кажется просто нагрузка слишком близка к границе таймаута, улучшил тест.
Но всё равно так делать не нужно.

2022-02-28 20:16 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
Ну вроде переписал с использованием `mismatch`. Все еще недостаточно оптимально?

2022-03-01 13:10 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/InMemoryDao.java
> +            new ConcurrentSkipListMap<>((m1, m2) -> Arrays.compare(m1.toByteArray(), m2.toByteArray()));
@Artyomcool

2022-03-03 16:30 UTC, Artyomcool approved these changes

2022-03-03 17:06 UTC, Artyomcool commented
Почему вы решили отказаться от MemorySegment?

2022-03-03 17:16 UTC, Pobedos commented
> Почему вы решили отказаться от MemorySegment?

Ну я попытался, написал свой компаратор, но, к сожелению, не удалось пройти тесты на 2_500

2022-03-04 03:26 UTC, Pobedos commented
@Artyomcool. Вернул обратно Memory segment. Вроде даже прошли тесты на 2500, но почему-то сейчас появились тесты на persistent, хотя не мержил даже

2022-03-06 18:29 UTC, Artyomcool commented
>  но почему-то сейчас появились тесты на persistent, хотя не мержил даже

При наличии настроения иногда сам подмёрживаю, они стерильны - не запускаются, пока вы не поднимете свой stage.

2022-03-06 18:31 UTC, Artyomcool approved these changes
Полный балл * 1.5

2022-03-06 18:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MemorySegmentComparator.java
> +        } else if (offset == m2.byteSize()) {
Наконец-то у кого-то корректная реализация)

2022-03-06 19:11 UTC, merged