Trofimov Artyom, stage 2
polis-vk/2022-nosql-lsm pull request #41
Opened 2022-03-06 10:48 UTC by artem24630

2022-03-10 14:32 UTC, Artyomcool requested changes

2022-03-10 14:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            Files.createFile(path);
Проверить и создать - два syscall'а.
Создать если не существует - 1.

2022-03-10 14:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        if (!data.containsKey(key)) {
Два раза искать в дереве нет смысла - contains делает поиск и get делает поиск, возвращая null, если не найдено.

2022-03-10 16:47 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +    private long loadFromFile() throws IOException {
убрал

2022-03-10 16:47 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            Files.createFile(path);
переделал без проверок

2022-03-10 16:48 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        if (!data.containsKey(key)) {
переделал

2022-03-10 16:48 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                int delimiterIndex = line.indexOf(' ');
переделал с помощью записи длины ключа в начале

2022-03-14 21:07 UTC, Artyomcool approved these changes
Полный балл

2022-03-14 21:07 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                data.put(entry.key(), entry);
вот так делать нельзя
если возникнет гонка с upsert вы перетрёте новые данные старыми

2022-03-14 21:07 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                line = input.readUTF();
ну так может проще сделать два readUTF а не парсить строку?

2022-03-16 18:50 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                line = input.readUTF();
да, пробовал так, но показалось, что медленнее, чем текущая реализация, хотя не так значительно

2022-03-17 18:52 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                line = input.readUTF();
поправил в stage 3 
[link](https://github.com/polis-vk/2022-nosql-lsm/pull/79/files#diff-303c591a3545c23a1f40a86554a1062074b055d05646361fe0f7991982d6b477R157)

2022-03-18 13:21 UTC, Artyomcool approved these changes
Полный балл -1

2022-03-18 13:21 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                data.put(entry.key(), entry);
Нет, это техническая ошибка, откладывать такие изменения нельзя, за это балл будет снижен.

2022-03-18 13:21 UTC, merged