Artem Yasevich, Stage 2
polis-vk/2022-nosql-lsm pull request #46
Opened 2022-03-07 09:52 UTC by a-yasevich

2022-03-10 14:39 UTC, Artyomcool requested changes
Исправьте замечания и получите 30% надбавки за бинарный поиск

2022-03-10 14:39 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java
> +                e.printStackTrace();
Буду снижать баллы в 10 раз за проглатывание исключений.

2022-03-10 14:39 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java
> +                String line = entry.key() + " " + entry.value() + "\n";
Много лишних аллокаций, разваливается при наличии пробела в ключе.

2022-03-18 13:37 UTC, Artyomcool approved these changes
Полный балл + 30%, -2 балла за лишние аллокации

2022-03-18 13:37 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java
> +                currentOffset += entry.key().getBytes(StandardCharsets.UTF_8).length
аллоцировать новый массив только для того чтобы посчитать размер?

2022-03-18 13:37 UTC, Artyomcool commented on src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java
> +                                - entryKey.getBytes(StandardCharsets.UTF_8).length - 2;
снова аллокция для подсчета размера

2022-03-18 13:37 UTC, merged

2022-03-18 21:11 UTC, a-yasevich commented on src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java
> +                currentOffset += entry.key().getBytes(StandardCharsets.UTF_8).length
А если я это исправил в третьем задании?)
https://github.com/a-yasevich/2022-nosql-lsm/blob/a0d01adfcf5df392d1d6d38d3f885892219185ae/src/main/java/ru/mail/polis/artemyasevich/InMemoryDao.java#L163