Kondraev Dmitry, Stage 2
polis-vk/2022-nosql-lsm pull request #47
Opened 2022-03-07 20:11 UTC by mariohuq

2022-03-09 20:53 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/LongArrayOutput.java
> +    public void write(long[] array) throws IOException {
Здесь CodeClimate ругается на. Предлагаю [убрать эту проверку](https://codeclimate.com/repos/621798c4007c6701a3014651/modified_configs?check_name=UseVarargs&engine_name=pmd&type=disable_check).

2022-03-10 14:20 UTC, mariohuq commented
Добавленные сейчас коммиты устраняют конфликт слияния и обеспечивают прохождение тестов.

Насколько я понял, на тестах `BasicConcurrentTest::test_10_000` и `BasicConcurrentTest::testConcurrentRW_2_500` узкое место это создание строки из `MemorySegment`, так как там происходит выделение памяти + копирование, во-первых, на пути `MemorySegment -> byte[]`, во-вторых, при `byte[] -> String`. По данным Async Profiler, ~60% всего времени занимает как раз [метод toString](https://github.com/polis-vk/2022-nosql-lsm/pull/47/files#diff-ecd53f044daec47c6dd33c16c88a749611d52b1f18789f093716d3b7b0802772R31).

* ~60% времени выполнения toString занимает путь `MemorySegment -> byte[]`
* ~30% -- путь `byte[] -> String`.

2022-03-10 17:50 UTC, mariohuq commented
[Код](https://github.com/mariohuq/2022-nosql-lsm/tree/66b0193bbb4396de12cfa5092837d8cc66cdb1ee) с char[] и Entry

* [BasicConcurrentTest_testConcurrentRW_2_500__1__2022_03_10_204314.zip](https://github.com/polis-vk/2022-nosql-lsm/files/8225801/BasicConcurrentTest_testConcurrentRW_2_500__1__2022_03_10_204314.zip)
  + ![BasicConcurrentTest_testConcurrentRW_2_500__1__2022_03_10_204314](https://user-images.githubusercontent.com/15021607/157724133-bfa9d738-ee21-48c7-a9e4-a7f533b0313e.png)
* [BasicConcurrentTest_testConcurrentRead_8_000__1__2022_03_10_204705.zip](https://github.com/polis-vk/2022-nosql-lsm/files/8225811/BasicConcurrentTest_testConcurrentRead_8_000__1__2022_03_10_204705.zip)
  + ![BasicConcurrentTest_testConcurrentRead_8_000__1__2022_03_10_204705](https://user-images.githubusercontent.com/15021607/157724227-703b3548-43fc-49a1-b61b-b968c097060b.png)

2022-03-12 09:18 UTC, Artyomcool requested changes

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +    private static final Comparator<MemorySegment> lexicographically = new MemorySegmentComparator();
для статических переменных используют ВОТ_ТАКОЙ_СПОСОБ_ИМЕНОВАНИЯ

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +            return null;
Опять проглатываете исключение.

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/LongArrayInput.java
> +    public long[] readLongArray() throws IOException {
не очень понятна потребность вычитывать всё в память

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/MemorySegmentAllocator.java
> +public interface MemorySegmentAllocator {
количество абстракций не упрощает код, а усложняет

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +                .unload();
эта операция приносит больше вреда, чем пользы

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/SortedStringTable.java
> +        dataSegment.unload();
unload делает не то что вы думаете

2022-03-12 09:18 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/SortedStringTable.java
> +        ).toArray();
есть очень большие вопросы как к производительности, так и к читаемости

2022-03-12 09:58 UTC, incubos commented on src/main/java/ru/mail/polis/dmitrykondraev/LongArrayOutput.java
> +    public void write(long[] array) throws IOException {
DONE

2022-03-17 08:38 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +    private static final Comparator<MemorySegment> lexicographically = new MemorySegmentComparator();
ок

2022-03-17 20:03 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/SortedStringTable.java
> +        ).toArray();
Переписал, см. [SortedStringTable::writeIndex](https://github.com/polis-vk/2022-nosql-lsm/pull/47/files#diff-51675aef8f708def13a7ea0d10b0d3ca88da32fdf88a22cfe60919347535795bR172-R192)

2022-03-17 20:04 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/MemorySegmentAllocator.java
> +public interface MemorySegmentAllocator {
Согласен

2022-03-17 20:06 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/LongArrayInput.java
> +    public long[] readLongArray() throws IOException {
Справедливо, см. [keyOffset, valueOffset](https://github.com/polis-vk/2022-nosql-lsm/pull/47/files#diff-51675aef8f708def13a7ea0d10b0d3ca88da32fdf88a22cfe60919347535795bR131-R137)

2022-03-17 20:06 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +            return null;
OK

2022-03-18 13:46 UTC, Artyomcool commented
Полный балл * 1.5 + 30%, -2 балла за гонку

2022-03-18 13:47 UTC, Artyomcool approved these changes

2022-03-18 13:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/FileBackedDao.java
> +        if (sortedStringTable == null) {
1. можно множество раз прочитать таблицу, пока не будет присвоение
2. вообще вся операция не потокобезопасна, так в принципе нельзя делать в многопоточном коде

Лучше избегать "ленивости" в многопоточном коде, если в этом нет прямой потребности.

2022-03-18 13:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitrykondraev/SortedStringTable.java
> +        return MemoryAccess.getLongAtOffset(indexSegment, Integer.BYTES + (i << 1) * Long.BYTES);
лучше использовать понятные операции, чем битовые сдвиги, компилятор это сам сделает за вас

2022-03-18 13:47 UTC, merged

2022-03-18 13:48 UTC, mariohuq commented
@Artyomcool +30% это за бинарный поиск?