Kovalenko Pavel, stage 2. Relapse
polis-vk/2022-nosql-lsm pull request #48
Opened 2022-03-07 20:34 UTC by PaaavelZ

2022-03-10 14:47 UTC, Artyomcool requested changes
Исправьте замечания и получите полный балл +30% за бинарный поиск.
Баллы за ByteBuffer не будут добавлены, т.к. вы используете его просто в качестве обертки над массивом байт.

2022-03-10 14:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
Буду снижать баллы в 10 раз.

2022-03-10 14:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        pathToDataFile = config.basePath().resolve("data.txt").toString();
Не понимаю зачем сначала переводить Path в строку, а потом обратно. Два раза.

2022-03-10 14:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return null;
Если у вас отказал диск, то значение не не найдено. У вас отказал диск

2022-03-10 14:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        while (b - a > Utils.minSizeOfElem) {
Данная магия мне совершенно непонятно.
Использование глобальных мутабельных переменных, кажется, запрещено женевской конвенцией.

2022-03-10 14:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        return ch == Utils.PAIR_SEPARATOR;
А если \n есть в ключе или значении?

2022-03-10 15:12 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        while (b - a > Utils.minSizeOfElem) {
Про магию и про \n проблема одна и та же - в методике бинарного поиска. Переделаю так, чтобы был ещё файлик, где указаны смещения каждой пары, чтобы по нему бегать и смотреть.

2022-03-10 21:57 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        return ch == Utils.PAIR_SEPARATOR;
Теперь такая проблема не стоит - записываем в файлик indexes.txt смещения каждой пары в байтах относительно начала нашей базы data.txt, в паре в ключе и значении может стоять АБСОЛЮТНО ЛЮБОЙ символ.

2022-03-10 21:58 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            return null;
Больше не ем исключение

2022-03-10 21:58 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        pathToDataFile = config.basePath().resolve("data.txt").toString();
Сохраняю теперь Path и использую его метод toString при необходимости

2022-03-10 21:58 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +            e.printStackTrace();
Больше не ем исключение

2022-03-10 21:59 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/InMemoryDao.java
> +        while (b - a > Utils.minSizeOfElem) {
Исправлено

2022-03-18 13:55 UTC, merged

2022-03-18 13:55 UTC, Artyomcool commented
полный балл +30% за бинарный поиск