Stage 2 - Ilchenko Andrey
polis-vk/2022-nosql-lsm pull request #49
Opened 2022-03-08 13:00 UTC by sorgeligt

2022-03-10 22:46 UTC, sorgeligt commented
@Artyomcool 
После дедлайна (опоздал на пару часов) был полностью переписан код на другой подход, без разделителей. Возможна ли проверка с откатом до коммита до дедлайна (он прошел все тесты, но, был не идеален в реализации)?

2022-03-11 13:05 UTC, Artyomcool requested changes
Поправьте замечания, +30% за бинарный поиск, +2 балла за тесты.

2022-03-11 13:05 UTC, Artyomcool commented on src/main/java/ru/mail/polis/andreyilchenko/PersistentDao.java
> +                }
тут некорректно: можно получить бесконечный цикл:
startIndex = 0;
endIndex = 1;

midIndex = (0 + 1) / 2 = 0;
compareResult < 0 -> startIndex = 0; endIndex = 1;

2022-03-11 13:17 UTC, sorgeligt commented on src/main/java/ru/mail/polis/andreyilchenko/PersistentDao.java
> +                }
Пофиксил

2022-03-11 13:19 UTC, sorgeligt commented on src/main/java/ru/mail/polis/andreyilchenko/PersistentDao.java
> +                }
Относительно ByteBuffer надбавка по баллам полагается?

2022-03-18 13:57 UTC, Artyomcool commented on src/main/java/ru/mail/polis/andreyilchenko/PersistentDao.java
> +                }
нет, потому что вы используете его просто как обёртку над массивом байт

2022-03-18 13:57 UTC, merged