Stage 2 | Medvedev Alexey
polis-vk/2022-nosql-lsm pull request #51
Opened 2022-03-08 18:33 UTC by MedAlexey

2022-03-10 14:57 UTC, Artyomcool requested changes
Исправьте замечания для получения полного балла

2022-03-10 14:57 UTC, Artyomcool commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +                        .append(KEY_VALUE_SEPARATOR)
А если пробел или новая строка встретятся в ключе или в значении?

2022-03-12 14:32 UTC, MedAlexey commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +                        .append(KEY_VALUE_SEPARATOR)
изменил реализацию

2022-03-12 14:33 UTC, MedAlexey commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +                LOGGER.log(Level.SEVERE, e.toString());
изменил логирование

2022-03-18 17:12 UTC, Artyomcool approved these changes
Полный балл -1 за помарки.

2022-03-18 17:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +                flush();
в итоге вы блокируете вставки на время флаша.

2022-03-18 17:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +        byte[] key;
Это не помогает читаемости, наоборот, чтобы понять тип, приходится смотреть куда-то ещё

2022-03-18 17:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/medvedevalexey/InMemoryDao.java
> +        File[] files = path.toFile().listFiles();
не нужно переходить из Path к File.

2022-03-18 17:13 UTC, merged