Stage2
polis-vk/2022-nosql-lsm pull request #52
Opened 2022-03-08 19:29 UTC by step-ponomarev

2022-03-09 03:44 UTC, step-ponomarev commented
<img width="813" alt="Screenshot 2022-03-09 at 06 43 46" src="https://user-images.githubusercontent.com/49997776/157368669-51dad7f2-7a45-43ce-8daf-8c66b8207465.png">

Кажется он запутался, либо я.

2022-03-10 22:12 UTC, Artyomcool requested changes
Глобально - очень неплохо, кажется тут выполнено и stage 3 тоже, но надо поработать над качеством кода.

2022-03-10 22:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +                ResourceScope.globalScope()
Похоже таки утекает

2022-03-10 22:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final Collection<Long> positions = flushAndAndGetPositions(file, data, size);
flush в конструкторе - выглядит немного странновато

2022-03-10 22:50 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/OSXMemorySegment.java
> +public class OSXMemorySegment implements Comparable<OSXMemorySegment> {
Все так. Назначение класса - костыль чтобы работало на моей операционной системе.
У меня не работает операций equals для двух эквивалетных мемори сегментов.

Локальные тесты не работают, на машине тут, наверное, пройдут - не проверял еще.
Мб придумаю что-то другое, но пока так.

2022-03-11 00:14 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final Collection<Long> positions = flushAndAndGetPositions(file, data, size);
Да...

2022-03-11 00:42 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/LsmDao.java
> +    private volatile long memTableSize;
Почему?

2022-03-12 20:02 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/MergedIterator.java
> +        );
> 

Ну, я как бы это уже делал....
Второгодник же
https://github.com/step-ponomarev/2021-nosql-lsm/blob/task4/src/main/java/ru/mail/polis/lsm/DAO.java#L49

2022-03-16 22:53 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/OSXMemorySegment.java
> +public class OSXMemorySegment implements Comparable<OSXMemorySegment> {
Убрал его в следующем стейдже

2022-03-18 17:30 UTC, Artyomcool approved these changes
Полный балл * 1.5 + 30% - 2 балла за помарки в коде.

2022-03-18 17:30 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/LsmDao.java
> +                    .count();
проделаем кучу аллокаций для подсчета числа?

2022-03-18 17:30 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/MemTable.java
> +                    + (value == null ? 0 : value.value().size());
Очень сложно читать

2022-03-18 17:30 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/MemTable.java
> +        synchronized (this) {
syncrhonized - жирно

2022-03-18 17:30 UTC, Artyomcool commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final long[] positions = flushAndAndGetPositions(file, data, fileSize, dataAmount);
выглядит что поднимать в память нет необходимости

2022-03-18 17:30 UTC, merged