Stage2 Maximenko Dmitree
polis-vk/2022-nosql-lsm pull request #53
Opened 2022-03-08 23:18 UTC by Dmitree-Max

Did all tasks

2022-03-10 22:31 UTC, Artyomcool requested changes

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            Path logPath = Path.of(config.basePath() + System.getProperty("file.separator") + LOG_NAME);
basePath().resolve

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        Iterator<BaseEntry<byte[]>> iterator = get(key, null);
data.get(key)?

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            this.last = last == null ? null : Arrays.copyOf(last, last.length);
Должен отметить, что в данном случае копия - хорошее решение.

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            return next != null && !Arrays.equals(next.key(), last);
Проверять на каждом hasNext равенство ключей может быть не лучшей идеей. Что если ключи будут по несколько килобайт с отличием в последних байтах?

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            for (int i = 0; i < Math.min(key1.length, key2.length); ++i) {
не надо делать ++i , i++ в Java не хуже (при нагрузках), но более общепринято

2022-03-10 22:31 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            super.write(System.getProperty("line.separator"));
а если line.separator содержится в ключе или значении?

2022-03-15 21:07 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            for (int i = 0; i < Math.min(key1.length, key2.length); ++i) {
исправил

2022-03-15 21:18 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        Iterator<BaseEntry<byte[]>> iterator = get(key, null);
Я не могу так сделать, Data у меня все еще Set. С домашки 3 будет уже Map с MemorySegment

2022-03-15 22:01 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            Path logPath = Path.of(config.basePath() + System.getProperty("file.separator") + LOG_NAME);
исправил

2022-03-15 22:02 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            super.write(System.getProperty("line.separator"));
тогда будем бросать исключение. Исправил

2022-03-15 22:23 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            return next != null && !Arrays.equals(next.key(), last);
согласен, теперь считаем простой хэш: сумму первого, среднего и последнего байта. Проверям равенство хэша и только, если они совпали, то идем сравнивать ключи целиком.

2022-03-18 18:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            return next != null && !Arrays.equals(next.key(), last);
нет, идея была в том, чтобы делать это единожды.
прыгать по байтам может быть даже хуже, чем проверять целиком в некоторых случаях.

2022-03-18 18:47 UTC, Artyomcool requested changes

2022-03-18 18:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        private static Integer simpleHashCode(byte[] last) {
аллоцировать Integer много хуже, чем прошлый вариант

2022-03-18 18:47 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +                throw new IllegalArgumentException("Line separator in the entry");
Нет, ключ и значения могут быть произвольными.

2022-03-23 12:59 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +                throw new IllegalArgumentException("Line separator in the entry");
Но в таком случае мы никогда не можем быть уверены, читаем ли мы key-separator-value или просто key.

2022-03-23 13:01 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            return next != null && !Arrays.equals(next.key(), last);
Я не оченб понялл, сто значит "делать это единожды". 

Я согласен тактика хэширования первый-средний-последний байт может быть не самой эффективной, но мне кажется выбор тактики должен основаться на проведении некоторых испытаний. Потому что в любом случае есть трейд-офф между "тяжелым" хэширование и колизиях хэша.

2022-03-23 15:08 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +                throw new IllegalArgumentException("Line separator in the entry");
Можно использовать подход: размер ключа - ключ - размер значения - значение

2022-03-24 12:13 UTC, Artyomcool approved these changes
Критически замечания проигнорированы, полный балл -4 балла.

2022-03-24 12:13 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +        private static Integer simpleHashCode(byte[] last) {
Теоретически может, но чем больше таких завязок, тем быстрее они посыпятся.

2022-03-24 12:13 UTC, Artyomcool commented on src/main/java/ru/mail/polis/dmitreemaximenko/InMemoryDao.java
> +            try (Scanner scanner = new Scanner(logPath, StandardCharsets.UTF_8)) {
Scanner основан на regex, работает очень неповоротливо

2022-03-24 12:13 UTC, merged