Egor Ovsyannikov, Stage2
polis-vk/2022-nosql-lsm pull request #54
Opened 2022-03-09 00:25 UTC by eatler

2022-03-10 22:35 UTC, Artyomcool requested changes

2022-03-10 22:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                String[] stringEntry = line
Очень грустно по производительности

2022-03-10 22:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        if (stringConcurrentSkipListMap.containsKey(key)) {
не нужно два раза искать
get возвращает null, если ключ не найден

2022-03-10 22:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +        if (!Files.exists(path)) {
npe, если будет вызван конструктор без параметров
кажется, отличный повод удалить лишний конструктор

2022-03-10 22:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +            e.printStackTrace();
flush() throws IOException

2022-03-10 22:35 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/alexanderkosnitskiy/ByteBufferDaoFactory.java
> -@DaoFactory
Кажется тут что-то лишнее

2022-03-15 18:52 UTC, eatler commented
Исправил. Производительность повысил за счет хранения ключа и значения на разных строках в файле

2022-03-18 18:50 UTC, Artyomcool requested changes
Если используете разделители, то их придется экранировать.

2022-03-18 18:50 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                .map(entry -> entry.key() + NEW_LINE + entry.value())
что если ключ или значение содержать \n?

кроме того, в этом коде происходит огромное количество аллокаций строк, после которого следует аллокация потенциально большого списка.

2022-03-21 00:37 UTC, eatler commented
Исправления

2022-03-24 12:15 UTC, Artyomcool approved these changes
Полный балл

2022-03-24 12:15 UTC, Artyomcool commented on src/main/java/ru/mail/polis/egorovsyannikov/InMemoryDao.java
> +                BaseEntry<String> entry = new BaseEntry<>(reader.readUTF(), reader.readUTF());
Нет смысла аллоцировать BaseEntry, если оно не будет использовано

2022-03-24 12:15 UTC, merged