Denis Zhidkov, stage 2
polis-vk/2022-nosql-lsm pull request #55
Opened 2022-03-09 08:16 UTC by DenZhid

2022-03-10 22:38 UTC, Artyomcool requested changes

2022-03-10 22:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/deniszhidkov/DaoReader.java
> +                String[] entry = line.split(": ");
Перформанс грустит.
А что если в ключе/значении есть эта последовательность байт?

2022-03-10 22:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            Files.createDirectories(config.basePath());
можно не проверять на exists

2022-03-10 22:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        if (storage.containsKey(key)) {
не нужно два раза искать key, get возвращает null, если key не найден

2022-03-14 10:46 UTC, DenZhid commented
Исправлены замечания и добавлены некоторые дополнения, показанные на занятии (ReadWriteLock)

2022-03-18 18:55 UTC, Artyomcool approved these changes
Полный балл -1 за ошибки.

2022-03-18 18:55 UTC, Artyomcool commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +        lock.readLock().lock();
зачем брать лок, если value != null?

2022-03-18 18:55 UTC, Artyomcool commented on src/main/java/ru/mail/polis/deniszhidkov/InMemoryDao.java
> +            return null;
Не понимаю. То, что файла нет, ещё не значит, что его нет в памяти.

2022-03-18 18:55 UTC, merged