Alina Shestakova, Stage 2
polis-vk/2022-nosql-lsm pull request #56
Opened 2022-03-09 10:56 UTC by Anilochka

2022-03-10 15:40 UTC, Anilochka commented
После дедлайна только убрала изменения в build.gradle

2022-03-10 22:41 UTC, Artyomcool requested changes
MemorySegment используется как обёртка над byte[], дополнительных баллов не будет.

2022-03-10 22:41 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +        this.files = path.toFile().listFiles();
Не нужно переходить к File API, когда у вас уже в руках Path.

2022-03-10 22:41 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +            try (InputStream input = Files.newInputStream(this.files[i].toPath())) {
я бы всё-таки фильтровал файлы по именам

2022-03-10 22:41 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +                    int size = input.read();
кажется 255 байт - слишком маленькое ограничение для размера ключа и значения, в идеале - 8 байт, хотя бы 4.

2022-03-11 14:59 UTC, Anilochka commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +        this.files = path.toFile().listFiles();
Исправила

2022-03-11 15:00 UTC, Anilochka commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +            try (InputStream input = Files.newInputStream(this.files[i].toPath())) {
Поменяла

2022-03-18 18:56 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +        this.files = path.toFile().listFiles();
Не вижу исправления

2022-03-18 19:01 UTC, Artyomcool requested changes

2022-03-18 19:01 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +                    if (Arrays.equals(rkey, key.toByteArray())) {
На каждой итерации аллоцируется новый массив байт

2022-03-18 19:01 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +                buffer.write(memorySegmentBaseEntry.key().toByteArray());
аллоцируется новый массив байт на каждой итерации

2022-03-18 19:01 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +             BufferedOutputStream buffer = new BufferedOutputStream(output, 128)) {
128 - это очень маленький размер буфера, стоит выбирать что-то от 4кб, возможно ближе к 100кб.

2022-03-18 19:02 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +            try (InputStream input = Files.newInputStream(this.files[i].toPath())) {
Не увидел

2022-03-18 19:02 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alinashestakova/InMemoryDao.java
> +                    int size = input.read();
Не вижу исправления

2022-03-18 19:02 UTC, Artyomcool commented
Вообще не увидел исправлений замечаний.

2022-03-20 15:59 UTC, Artyomcool requested changes
полный балл, -2 за ограничение размера ключа, которое не исправляется.

2022-03-20 15:59 UTC, merged