Stage 2. Komissarov Gleb
polis-vk/2022-nosql-lsm pull request #57
Opened 2022-03-09 11:15 UTC by RalerCulte

WIP - w/o binary search

2022-03-10 22:45 UTC, Artyomcool requested changes
Пожалуйста, избавьтесь от мутабельных статических полей в Converter, чтобы я мог продолжить ревью.

2022-03-10 22:45 UTC, Artyomcool commented on build.gradle
> -plugins {
Удалить build.gradle - кажется не самое нужное изменение

2022-03-10 22:45 UTC, Artyomcool commented on src/main/java/ru/mail/polis/glebkomissarov/Converter.java
> +    private static Path pathToOffsets;
мутабельные статические переменные - путь в ад

2022-03-11 00:20 UTC, closed without merging

2022-03-11 00:20 UTC, RalerCulte commented
Всё испортил :(