Alexandra Tkachenko. Stage_2
polis-vk/2022-nosql-lsm pull request #61
Opened 2022-03-09 20:51 UTC by Alexandra-Tkachenko

2022-03-18 19:12 UTC, Artyomcool requested changes
Поправьте замечания для получения полного балла.
За ByteBuffer дополнительных баллов не будет, т.к. работа с ним идёт как с массивом байт.

2022-03-18 19:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexandratkachenko/InMemoryDao.java
> +        Objects.requireNonNull(config, "Invalid argument in constructor.\n");
\n излишне

2022-03-18 19:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexandratkachenko/InMemoryDao.java
> +        if (Files.exists(dataPath)) {
проверять на exists каждый раз не очень хорошая идея

2022-03-18 19:12 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexandratkachenko/InMemoryDao.java
> +            try (FileChannel channel = FileChannel.open(dataPath)) {
открывать файл заново каждый раз не очень хорошая идея

2022-03-23 20:39 UTC, Alexandra-Tkachenko commented on src/main/java/ru/mail/polis/alexandratkachenko/InMemoryDao.java
> +        if (Files.exists(dataPath)) {
действительно

2022-03-24 12:17 UTC, Artyomcool approved these changes
Полный -2 балла за неисправление замечания, но +1 балл за Objects.requireNonNull.

2022-03-24 12:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexandratkachenko/InMemoryDao.java
> +        try (FileChannel channel = FileChannel.open(dataPath, StandardOpenOption.READ,
всё ещё продолжаете открывать файл на каждом get

2022-03-24 12:17 UTC, merged