Change readme to contain stage 3
polis-vk/2022-nosql-lsm pull request #62
Opened 2022-03-10 21:01 UTC by Sanerins

Выполнил Косницкий Александр. 
Жду ваших правок и комментариев!

2022-03-11 10:29 UTC, incubos requested changes
Есть ряд замечаний.

2022-03-11 10:29 UTC, incubos commented on README.md
> +## Этап 3. Merge Iterator (deadline 2022-03-17 00:00:00 MSK)
`deadline 2022-03-23 23:59:59 MSK`.

2022-03-11 10:29 UTC, incubos commented on README.md
> +* За один тест метод `close` у DAO может быть вызван сразу несколько раз. Следовательно, должна поддерживаться возможность создания неограниченного количества файлов, содержащих данные нашей БД - по
Не совсем так: `close()` у каждого экземпляра `DAO` вызывается не больше одного раза, но раньше мы переоткрывали `DAO` и только читали из него, а теперь будем и **писать** после переоткрытия.

2022-03-11 13:34 UTC, Sanerins commented on README.md
> +* За один тест метод `close` у DAO может быть вызван сразу несколько раз. Следовательно, должна поддерживаться возможность создания неограниченного количества файлов, содержащих данные нашей БД - по
Попробовал переписать максимально подробно, понятно и правильно

2022-03-11 13:38 UTC, Artyomcool requested changes

2022-03-11 13:38 UTC, Artyomcool commented on README.md
> +* Стоит учитывать, что в диапазоне от `from` до `to`, некая часть данных может уже находиться в файле на диске, в то время, как другая часть будет все еще `InMemory`. Несмотря на это, необходимо умет
термина merge-итератор не существует, поэтому не понятно, что тут имеется ввиду, предлагаю как-то переформулировать

2022-03-11 13:38 UTC, Artyomcool commented on README.md
> +* За один тест метод `close` у конкретного инстанса DAO может быть вызван только один раз, однако после этого имеется возможность создать новый инстанс DAO с тем же `config`(т.е будет произведено пер
переоткрытое -> переоткрытие

2022-03-11 13:38 UTC, Artyomcool commented on README.md
> +* За один тест метод `close` у конкретного инстанса DAO может быть вызван только один раз, однако после этого имеется возможность создать новый инстанс DAO с тем же `config`(т.е будет произведено пер
"из которого будет вестись чтение, а так же производиться запись"

"из которого" должно относиться только к первой части перечисления, но в такой конструкции относиться к обеим частям. Ну и -тся/ться.

2022-03-11 13:38 UTC, Artyomcool commented on README.md
> +* После использования метода `close`, `Entry` с тем же значением ключа может быть добавлено в последующие DAO еще несколько раз, база данных должна выдавать самое свежее значение при поиске, игнориру
Я бы хотел исключить двоякость прочтения: игнорирование должно быть только значений по одному ключу, в случае наличия более свежего.

2022-03-11 13:38 UTC, Artyomcool commented on README.md
> +* Считаем, что метод `flush` вызывается только из метода `close`. Таким образом `flush` будет гарантированно выполняться однопоточно, однако `get` и `upsert` могут работать в многопоточном режиме - с
Я бы добавил, что можно расчитывать (на этом этапе), что get/upsert не будут вызываться в процессе flush.

2022-03-11 13:40 UTC, Sanerins commented on README.md
> +Когда всё будет готово, присылайте pull request в ветку `stage3` со своей реализацией на review. Не забывайте **отвечать на комментарии в PR** и **исправлять замечания**!
Это уже устаревшая поправка, данная помарка была поправлена в коммите: [1a1b634](https://github.com/polis-vk/2022-nosql-lsm/pull/62/commits/1a1b6349afe7f1e060f934ebecf9a3ac61a64ffb)

2022-03-11 13:48 UTC, Sanerins commented on README.md
> +* Стоит учитывать, что в диапазоне от `from` до `to`, некая часть данных может уже находиться в файле на диске, в то время, как другая часть будет все еще `InMemory`. Несмотря на это, необходимо умет
Постарался расписать что имеется ввиду под термином merge-iterator максимально подробно

2022-03-11 13:49 UTC, Artyomcool commented on README.md
> +* Стоит учитывать, что в диапазоне от `from` до `to`, некая часть данных может уже находиться в файле на диске, в то время, как другая часть будет все еще `InMemory`. Несмотря на это, необходимо умет
Лучше не вводить новых терминов.

2022-03-11 13:52 UTC, Sanerins commented on README.md
> +* За один тест метод `close` у конкретного инстанса DAO может быть вызван только один раз, однако после этого имеется возможность создать новый инстанс DAO с тем же `config`(т.е будет произведено пер
Ой, извините, idea сама вот так вот с переоткрытие на переоктрытое исправила)

2022-03-11 14:11 UTC, incubos commented on README.md
> +## Этап 3. Merge Iterator (deadline 2022-03-17 00:00:00 MSK)
Это как раз hard deadline :) На этот этап даётся 2 недели + 1 неделя за половину баллов. На занятии мы неверно выразились.

2022-03-11 14:11 UTC, Sanerins commented on README.md
> +* Считаем, что метод `flush` вызывается только из метода `close`. Таким образом `flush` будет гарантированно выполняться однопоточно, однако `get` и `upsert` могут работать в многопоточном режиме - с
Добавил данное уточнение

2022-03-11 14:12 UTC, Sanerins commented on README.md
> +* После использования метода `close`, `Entry` с тем же значением ключа может быть добавлено в последующие DAO еще несколько раз, база данных должна выдавать самое свежее значение при поиске, игнориру
Попробовал сформулировать более четко

2022-03-11 14:12 UTC, Sanerins commented on README.md
> +* За один тест метод `close` у конкретного инстанса DAO может быть вызван только один раз, однако после этого имеется возможность создать новый инстанс DAO с тем же `config`(т.е будет произведено пер
А ведь когда-то 98 баллов за ЕГЭ по русскому было...

2022-03-11 14:16 UTC, incubos requested changes

2022-03-11 14:16 UTC, incubos commented on README.md
> +* Стоит учитывать, что в диапазоне от `from` до `to`, некая часть данных может уже находиться в файле на диске, в то время, как другая часть будет все еще `InMemory`. Несмотря на это, необходимо умет
Может, просто убрать фразу "реализовав свой `merge` итератор"?

2022-03-11 14:16 UTC, incubos commented on README.md
> +* После использования метода `close`, `Entry` с тем же значением ключа может быть добавлено в последующие DAO еще несколько раз, база данных должна выдавать самое свежее значение при поиске, игнориру
Возможно, было бы понятнее как-то так: значения по одному и тому же ключу могут перезаписываться и разные версии значений могут находиться в файлах на диске, а также в памяти -- необходимо возвращать самое свежее значение для каждого ключа.

2022-03-11 14:16 UTC, incubos commented on README.md
> +* Считаем, что метод `flush` вызывается только из метода `close`. Таким образом `flush` будет гарантированно выполняться однопоточно, однако `get` и `upsert` могут работать в многопоточном режиме - с
Не хватает запятой после "Таким образом".

2022-03-11 14:37 UTC, Sanerins commented
Стоит учитывать, что в диапазоне от `from` до `to`, некая часть данных может уже находиться в файле на диске, в то время, как другая часть будет все еще `InMemory`. Несмотря на это, необходимо уметь последовательно отдавать все данные в правильно отсортированном виде, реализовав итератор, способный выдавать следующее по порядку `entry`, анализируя информацию сразу из многих источников(все созданные на данный момент файлы + `InMemory` часть).

Так звучит пункт про итератор в данный момент, сейчас уберу описание итератора полностью, чтобы можно было решить, как лучше

2022-03-12 10:00 UTC, incubos approved these changes

2022-03-12 10:04 UTC, Artyomcool approved these changes

2022-03-12 10:05 UTC, incubos commented
4 балла.

2022-03-12 10:05 UTC, merged