Reopen stage 2, Komissarov Gleb
polis-vk/2022-nosql-lsm pull request #65
Opened 2022-03-11 12:05 UTC by RalerCulte

<img width="682" alt="image" src="https://user-images.githubusercontent.com/72687636/157863762-3e28268d-06bf-4fd5-8209-2c0b5565480a.png">

2022-03-11 13:29 UTC, Artyomcool requested changes
Поправьте замечания и можно расчитывать на полный балл * 1.5 за memory segment.

2022-03-11 13:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/glebkomissarov/Converter.java
> +        offsets = new long[(int) (dataCount * 2 + 1)];
тут сложный момент: в теории может быть очень много мелких записей, но, например, касандра делает так же

2022-03-11 13:29 UTC, Artyomcool commented on src/main/java/ru/mail/polis/glebkomissarov/Converter.java
> +        offsets = mappedSegmentOffsets.toLongArray();
Вот эта процедура кажется напрасной тратой как памяти, так и времени. Можно/нужно работать сразу в mappedSegmentOffsets, без копирования в память массивом.

2022-03-11 16:07 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/Converter.java
> +        offsets = new long[(int) (dataCount * 2 + 1)];
А какой тут может быть альтернативный подход?

2022-03-18 19:17 UTC, Artyomcool approved these changes
Полный балл * 1.5

2022-03-18 19:17 UTC, Artyomcool commented on src/main/java/ru/mail/polis/glebkomissarov/Converter.java
> +        long nextLong;
а зачем это выносится отдельно? чем локальней скоуп, тем проще следить за переменной.

2022-03-18 19:17 UTC, merged