Implement range from files tests
polis-vk/2022-nosql-lsm pull request #66
Opened 2022-03-11 22:01 UTC by Pobedos

Написал немного тестов

2022-03-17 13:30 UTC, incubos requested changes
Есть ряд вопросов/замечаний.

2022-03-17 16:19 UTC, Pobedos commented on src/test/java/ru/mail/polis/ReopenRangeTest.java
> +        entries = entries(numberOfFiles * (entriesPerFile - offsetIncrease) + offsetIncrease, 0, offsetIncrease);
Сделал попроще, надеюсь

2022-03-17 16:19 UTC, Pobedos commented on src/test/java/ru/mail/polis/ReopenRangeTest.java
> +                String value = String.format("%010d", index);
Ну в этом смысл теста был, но согласен, тест неочевидный

2022-03-24 09:26 UTC, incubos commented
8 баллов. Спасибо за contribution!

2022-03-24 09:27 UTC, merged