Pobedonostsev Kirill, stage 3
polis-vk/2022-nosql-lsm pull request #67
Opened 2022-03-11 22:06 UTC by Pobedos

2022-03-19 13:45 UTC, incubos requested changes
Есть большое количество замечаний, в т.ч. критичных.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +            offset = readIndexPage.getInt();
Почему не `int getInt(int index)` вместо `position()` + `getInt()`?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +            mid = (high + low) / 2;
Возможно переполнение.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +    public static int floorOffset(MappedByteBuffer readDataPage, MappedByteBuffer readIndexPage, ByteBuffer to) {
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +    public static int ceilOffset(MappedByteBuffer readDataPage, MappedByteBuffer readIndexPage, ByteBuffer from) {
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +    }
Необходимо порефакторить и избавиться от трёх практически идентичных методов, вдохновившись возвращаемым значением и реализацией метода `Arrays.binarySearch()`. Можно свести все вариации к одному бинарному поиску.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +            if (compareResult >= 0) {
Почему нет `break`/`return` при равенстве?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            Files.createDirectories(config.basePath());
Здесь нужно кидать исключение, ибо гарантируется, что каталог существует.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +        try (RandomAccessFile file = new RandomAccessFile(elementsPath.toFile(), "rw")) {
Почему не `"r"`?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                iteratorsList.add(getFileIterator(from, to, getFilePath(DATA_PREFIX, i), getFilePath(INDEX_PREFIX, i)));
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +    private FileIterator getFileIterator(ByteBuffer from, ByteBuffer to, Path dataPath, Path indexPath)
Почему не передавать вместо `dataPath`/`indexPath` номер файла?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            MappedByteBuffer mappedDataFile = dataChannel.map(FileChannel.MapMode.READ_ONLY, 0, dataChannel.size());
Открывать и `mmap`ить два файла на каждый `get()` очень дорого.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            MappedByteBuffer mappedDataFile = dataChannel.map(FileChannel.MapMode.READ_ONLY, 0, dataChannel.size());
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            MappedByteBuffer mappedIndexFile = indexChannel.map(FileChannel.MapMode.READ_ONLY, 0, indexChannel.size());
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            fileRange = dataChannel.map(FileChannel.MapMode.READ_ONLY, fromOffset, toOffset - fromOffset);
Зачем ещё один `mmap`, а не `mappedDataFile.slice()`?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
>      public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Чем не устраивает дефолтная реализация `Dao.get(D key)` после полноценной реализации `Iterator<E> get(D from, D to)`? Можно (и нужно) всё сильно упростить и удалить кучу кода.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                    StandardOpenOption.TRUNCATE_EXISTING);
Для чего `StandardOpenOption.TRUNCATE_EXISTING`? Разве это не ошибка, если файл уже существует?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                    StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.READ,
Для чего здесь `StandardOpenOption.READ`?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                         StandardOpenOption.TRUNCATE_EXISTING)) {
Зачем `StandardOpenOption.READ` и `StandardOpenOption.TRUNCATE_EXISTING`?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                dataPage.putInt(entry.value().remaining());
Теперь `value` у нас nullable...

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            fileNumber++;
Не хватает `MappedByteBuffer.force()` на обоих буферах, потому что мы собираемся объявить всему миру, что появился новый файл.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PeekingIterator.java
> +public class PeekingIterator implements Iterator<BaseEntry<ByteBuffer>> {
Может, generic для упрощения понимания?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +    private static final Comparator<BaseEntry<ByteBuffer>> entryComparator = Comparator.comparing(BaseEntry::key);
Длинная строка.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +                comparator.thenComparing(PeekingIterator::getPriority));
Почему бы не вынести `thenComparing()` в `comparator`? Зачем каждый раз создавать новый `Comparator`.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +            Iterator<BaseEntry<ByteBuffer>> iterator = iterators.get(i);
Лучше for-each вместо for, потому что мы не знаем, является ли `iterators` random access (`ArrayList`).

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +                queue.add(new PeekingIterator(iterator, i));
Здесь есть неявный контракт: последние файлы менее приоритетные -- верно?

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        PeekingIterator nextIter = queue.remove();
`hasNext()` могут вообще не вызывать (контракт `Iterator` этого не требует) -- в таком случае всё сломается, потому текущая реализация `next()` полагается на предварительный вызов `hasNext()`.

2022-03-19 13:45 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        while (prev != null && nextIter.hasNext() && entryComparator.compare(nextIter.peek(), prev) == 0) {
Этот цикл отбрасывает более старые версии `prev.key`, верно? Выглядит логичным делать это в `next()` и убрать поле `prev` в принципе.

2022-03-19 14:11 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        PeekingIterator nextIter = queue.remove();
Но у меня же в next предварительно идет вызов `hasNext()`

2022-03-19 14:14 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                dataPage.putInt(entry.value().remaining());
Я понимаю, еще не поменял просто

2022-03-19 14:55 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +                queue.add(new PeekingIterator(iterator, i));
Согласе, вынес в другой слой логики

2022-03-19 15:00 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            Files.createDirectories(config.basePath());
Не совсем, в тесте cleanup удаляется директория и затем переоткрывается

2022-03-19 15:29 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
>      public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
И правда, спасибо

2022-03-19 15:36 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +                    StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.READ,
Потому что `FileChannel.MapMode` стоит `READ_WRITE`

2022-03-19 18:09 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            Files.createDirectories(config.basePath());
Понятно. В данном случае правильно было бы обсудить проблему в общем чате, пофиксить тест и получить дополнительные баллы, вместо реализации workaround. Попробуйте вспомнить, многие ли утилиты автоматом создают каталоги, если их нет.

2022-03-19 19:50 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/SearchUtility.java
> +    }
Переделал. Стало действительно лучше, спасибо за совет

2022-03-19 19:54 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PeekingIterator.java
> +public class PeekingIterator implements Iterator<BaseEntry<ByteBuffer>> {
Заменил на дженерик

2022-03-19 20:57 UTC, Pobedos commented
Пофиксил большинство замечаний. Единственное не совсем понял, почему нужно избавляться от устаревших значений именно в next(), а не hasNext(), учитывая, что у меня в next() идет сначала проверка на hasNext()

2022-03-24 10:24 UTC, incubos requested changes
Решение хорошее, но всё ещё есть ряд вопросов и замечаний.

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        while (same) {
Чтобы не повторять код перед циклом и в конце цикла, лучше отрефакторить:
```
while (entryComparator.compare(iter.peek(), current) == 0) {
...
}
```

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        if (!same) {
Усложнённый control flow. Давайте упростим?

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        if (!same) {
`if (iter.hasNext())`?

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        boolean same = entryComparator.compare(iter.peek(), current) == 0;
Нужен ли нам `entryComparator()`? Эффективнее сравнивать ключи по `equals()`.

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +        if ((readIndexPage.capacity() >> 2) <= indexOffset) {
Что это за "коррекция"? Нужны объяснения.

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +    private static int binarySearch(MappedByteBuffer readDataPage, MappedByteBuffer readIndexPage,
Возможно, было бы более читаемо, если бы мы возвращали **индекс** записи, а не смещение в байтах.

2022-03-24 10:24 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            int keySize = readDataPage.getInt();
Есть метод `getInt(int index)`, который позволяет не трогать `position`.

2022-03-24 12:29 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +    private static int binarySearch(MappedByteBuffer readDataPage, MappedByteBuffer readIndexPage,
Но ведь этот метод и так возвращает именно порядковый номер записи в файле с индексами

2022-03-24 12:31 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +        if ((readIndexPage.capacity() >> 2) <= indexOffset) {
Тут я проверял, что пришедший индекс не больше, чем количество индексов в файле. На самом деле глупость сделал, нужно было сдвигать как раз индекс

2022-03-24 12:32 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +    private static int binarySearch(MappedByteBuffer readDataPage, MappedByteBuffer readIndexPage,
У меня тут плохой нейминг, переделаю на более очевидный

2022-03-24 12:32 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            int keySize = readDataPage.getInt();
Согласен, это сделаю

2022-03-24 12:33 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        if (!same) {
К сожалению этого недостаточно

2022-03-24 12:33 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        while (same) {
Вся эта каша была как раз сделана из-за условия после цикла, чтобы дважды не проверять

2022-03-24 12:35 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +    private final List<BaseEntry<MappedByteBuffer>> filesList;
Действительно, добавил новый record

2022-03-24 12:35 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/PersistenceDao.java
> +            fileNumber = 0;
Изменил исключение

2022-03-24 14:38 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        boolean same = entryComparator.compare(iter.peek(), current) == 0;
Действительно

2022-03-24 14:48 UTC, Pobedos commented
Пока не смог придумать, как переписать тот странный цикл в итераторе

2022-03-25 08:11 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/MergeIterator.java
> +        if (!same) {
Вчера на лекции увидел и вспомнил, что есть `peek()` у очереди, убрал лишнее

2022-03-27 17:43 UTC, incubos approved these changes
Принято с небольшим замечанием. 1.2х за mmap.

2022-03-27 17:43 UTC, incubos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/FilePair.java
> +public record FilePair(MappedByteBuffer indexFile, MappedByteBuffer dataFile) {
Здесь и по всему коду вместо `MappedByteBuffer` лучше использовать `ByteBuffer`, как более абстрактный класс без изменения семантики.

2022-03-28 15:24 UTC, Pobedos commented on src/main/java/ru/mail/polis/kirillpobedonostsev/FilePair.java
> +public record FilePair(MappedByteBuffer indexFile, MappedByteBuffer dataFile) {
Спасибо

2022-03-31 14:51 UTC, merged