Stage 3 | Ponomarev Stepan
polis-vk/2022-nosql-lsm pull request #68
Opened 2022-03-11 22:47 UTC by step-ponomarev

2022-03-19 13:46 UTC, incubos commented
Необходимо разрулить конфликты.

2022-03-19 14:28 UTC, incubos commented
> Необходимо разрулить конфликты.

Локально не проходят тесты:
```
PersistentRangeTest > concat(Dao) > ru.mail.polis.PersistentRangeTest.concat(Dao)[1] FAILED
    java.lang.IndexOutOfBoundsException at PersistentRangeTest.java:184

28 tests completed, 1 failed
```

2022-03-19 14:49 UTC, incubos requested changes
Сформулировано множество замечаний и их список далеко не полон.
В этом PR очень много не относящихся к делу изменений, которые будут рассматриваться в других этапах или являются бонусными заданиям.
Отрежьте всё лишнее (log, autoflush, concurrency) ASAP, соберите из оставшегося корректную реализацию функциональности 3 этапа и тогда можно будет доревьюить.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/Utils.java
> +        long writeOffset = offset;
`offset` изменяемый -- можно не заводить ещё одну переменную.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/Utils.java
> +    public static Iterator<TimestampEntry> slice(
Этот метод используется больше одного раза и достоин жить в `Utils`?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/log/CommitLog.java
> +package ru.mail.polis.stepanponomarev.log;
Если речь про WAL, то это лучше вынести в отдельный PR (в конце курса как бонусный этап), а пока сконцентрируемся на текущем этапе.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/log/LoggerAhead.java
> +package ru.mail.polis.stepanponomarev.log;
В отдельный PR в конце курса.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +            throw new IllegalArgumentException("Path: " + path + "is not exist");
Не хватает пробела перед `is`.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +        return store.get(key);
Чем не устраивает default реализация в `Dao`?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +        if (store.getSizeBytes() >= MAX_MEMTABLE_SIZE_BYTES) {
Автоматический flush нужно вынести в отдельный PR -- там будем ревьюить и обсуждать, потому что есть ряд своих нюансов.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +        final long timestamp = System.nanoTime();
`nanoTime()` не годится.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/iterator/MergedIterator.java
> +        firstIter = right;
Почему first/second и right/left, а не что-то одно? И почему first это right? Выглядит запутанно.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/iterator/MergedIterator.java
> +        this.comparator = comparator;
Либо везде с `this.` (обычно так), либо везде без.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/iterator/MergedIterator.java
> +            throw new NoSuchElementException("No Such Element");
Ничего не говорящая строка -- нужно ли её передавать?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/Store.java
> +        atomicStore.get().close();
`getAndSet(null)`?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/FlushData.java
> +        this.timeNs = System.nanoTime();
`nanoTime()` не годится.

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/FlushData.java
> +        return Utils.slice(store, null, null);
Почему не `store.values().iterator()`?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +                    new ConcurrentSkipListMap<>(flushStore.memTable)
Зачем это копирование?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +            flushingData.put(entry.key(), entry);
Для чего это копирование?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/FlushData.java
> +    public final int count;
Для чего нужно это поле, если есть `store.size()`?

2022-03-19 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +                filterByTimestamp(flushStore.memTable, timestamp)
Это же неатомарно происходит: пока мы фильтруем (с копированием!), кто-то добавляет новые записи, которые не попадут в копию. Thread safety мы займёмся на отдельном этапе. Не нужно всё пихать в одну кучу -- это невозможно ревьюить. Кроме того, до дедлайна вы не успеете, если мы выложим тесты на concurrency.
Цель каждого этапа/PR -- добавить корректную реализацию одной конкретной функциональности.

2022-03-19 15:36 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/FlushData.java
> +        this.timeNs = System.nanoTime();
Убрал

2022-03-19 15:37 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/FlushData.java
> +    public final int count;
Осталось со времен когда я сохранял тут итератор, а не мапу. Спасибо

2022-03-19 15:41 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +                    new ConcurrentSkipListMap<>(flushStore.memTable)
Вот тут точно не припомню, но кажется при автофлаше на 1 байте у меня без этого вылетала ошибка какая-то в канкаренси тестах, уже не помню. Метод тыка в общем

Убрал, вроде норм все

2022-03-19 15:45 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +            flushingData.put(entry.key(), entry);
Создаю неизменяемый объект для дальнейшего флаша.
Идея была в том, что при флаше я пополняю список флашей, из которого буду брать и лепить SSTablы

Т.е. эти данные для флаша будут висеть, блокировки добавления данных не будет. Когда-нибудь мы их точно зафлашим, пока не зафлашили сможем брать из списка флашей при запросе get

2022-03-19 15:48 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +                filterByTimestamp(flushStore.memTable, timestamp)
Да, есть косяки.

>Кроме того, до дедлайна вы не успеете, если мы выложим тесты на concurrency.
Понавешаю синхронайзы на крайняе

2022-03-19 15:51 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/TimestampEntry.java
> +    public boolean equals(Object o) {
Это более не нужно, осталось от старых реализаций, спасибо

2022-03-19 15:57 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/test/stepanponomarev/LsmDaoFactory.java
> +            Files.createDirectory(path);
Тогда на PersistentTest.cleanup у меня всегда тут будет выбрасываться исключение, тест я не пройду.

2022-03-19 16:02 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/TimestampEntry.java
> +        this.timestamp = System.nanoTime();
+

2022-03-19 16:57 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/AtomicStore.java
> +            flushingData.put(entry.key(), entry);
Убрал список флашей, оставил один

2022-03-19 17:23 UTC, step-ponomarev commented
Все понял, принял. Поудалял велосипеды с квадратыми колесами (кажется)

2022-03-19 17:28 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/Utils.java
> +    public static SortedMap<MemorySegment, TimestampEntry> createMap() {
\+

2022-03-19 17:41 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/Utils.java
> +        long writeOffset = offset;
Мне не нравится изменять аргументы

2022-03-19 17:41 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/Utils.java
> +    public static Iterator<TimestampEntry> slice(
Убрал

2022-03-19 17:41 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/iterator/MergedIterator.java
> +        this.comparator = comparator;
ок

2022-03-19 17:42 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/iterator/MergedIterator.java
> +    public static <T, E extends Entry<T>> Iterator<E> instanceOf(List<Iterator<E>> iterators,
есть такое)

2022-03-24 10:38 UTC, incubos commented on src/main/java/ru/mail/polis/test/stepanponomarev/LsmDaoFactory.java
> +            Files.createDirectory(path);
Пофиксили в `upstream`.

2022-03-24 12:29 UTC, incubos requested changes
Есть ряд замечаний и вопросов.

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
>          final MemorySegment memorySegment = MemorySegment.mapFile(file,
Почему не закрываем после записи?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +    public long findKeyPosition(MemorySegment key) {
Зачем проверка этих граничных случаев? Нельзя положиться на `findKeyPosition()` ниже?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +    private long findKeyPosition(MemorySegment key, long left, long right) {
Рекурсивный бинарный поиск это не production решение. С инженерной точки зрения эффективнее циклом.

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +        final long keySize = MemoryAccess.getLongAtOffset(tableMemorySegment, keyPosition);
Почему бы не использовать `getKeyByIndexOrderPosition()`?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +            return keyPosition;
Что это за случай не точного равенства?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +        if (left == right) {
Почему снова повторяется условие `left == right`?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +            return mid == lastIndexOrderPosition
Снова непонятное условие. Помним, что комментарии к неочевидным местам значительно ускоряют и повышают шансы прохождения review.

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +    private long findKeyPosition(MemorySegment key, long left, long right) {
Эта реализация совсем не идиоматичная. Предлагаю подумать и упростить. Можете вдохновиться стандартным `Arrays.binarySearch()` (см. на возвращаемое значение в случае отсутствия совпадения).

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final Path sstableDir = path.resolve(SSTABLE_DIR_NAME + timestamp + System.nanoTime());
Зачем здесь `nanoTime()`?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final Path sstableDir = path.resolve(SSTABLE_DIR_NAME + timestamp + System.nanoTime());
Мы явно полагаемся на то, что `timestamp` в строковом представлении будет одинаковой длины, чтобы не сломалась сортировка по именам файлов, верно?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +    public TimestampEntry get(MemorySegment key) throws IOException {
Чем не устраивает default реализация в `Dao`?

2022-03-24 12:29 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +    public TimestampEntry get(MemorySegment key) throws IOException {
Давайте выпилим кастомную реализацию и разберёмся, почему ломаются тесты?

2022-03-24 20:33 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/TombstoneSkipIterator.java
> +            throw new NoSuchElementException("No such element");
\+

2022-03-24 20:33 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/TombstoneSkipIterator.java
> +        return current != null || delegate.hasNext();
\+

2022-03-24 20:34 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/MergeIterator.java
> +        this.firstEntry = getElement(oldDataIterator);
\+

Вообще не нравятся нейминги текущие. Если есть идеи - буду благодарен :)

2022-03-26 10:57 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +    public TimestampEntry get(MemorySegment key) throws IOException {
ломаются потому что MemorySegments сравниваются EQUALS в некоторых тестах.
С ними так не работает, вроде как от "кастомной" реализации get не должно быть никаких проблем.

2022-03-26 10:57 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final Path sstableDir = path.resolve(SSTABLE_DIR_NAME + timestamp + System.nanoTime());
убреру пока что System.nanoTime())

2022-03-26 10:57 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        final Path sstableDir = path.resolve(SSTABLE_DIR_NAME + timestamp + System.nanoTime());
Сейчас незачем. 
А так тестил большое количество канкаренси флашей timestamp не вывозит

2022-03-26 10:58 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +            return mid == lastIndexOrderPosition
Переписал тут все

2022-03-26 10:58 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/Index.java
> +        if (left == right) {
Переписал тут все

2022-03-26 10:58 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +    private static long flush(TimestampEntry entry, MemorySegment memorySegment, long offset) {
Окей)

2022-03-26 10:58 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final long[] positions = flushAndAndGetPositions(file, data, fileSize, count);
Переписал тут все

2022-03-26 11:30 UTC, step-ponomarev commented
Локально все тесты работают.
Тут то таймаут, то файл уже существуют (wut?)

2022-03-27 17:49 UTC, incubos commented
> Локально все тесты работают. Тут то таймаут, то файл уже существуют (wut?)
> 
> ![Screenshot 2022-03-26 at 14 39 38](https://user-images.githubusercontent.com/49997776/160237753-d5a6b245-307e-4f81-8f61-ead3f99ffa52.png)

Да, пока тоже не разобрался, откуда это.

2022-03-27 17:51 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/MergeIterator.java
> +        this.firstEntry = getElement(oldDataIterator);
Без разницы, лишь бы консистентно :)

2022-03-27 17:53 UTC, incubos commented
> Локально все тесты работают. Тут то таймаут, то файл уже существуют (wut?)
> 
> ![Screenshot 2022-03-26 at 14 39 38](https://user-images.githubusercontent.com/49997776/160237753-d5a6b245-307e-4f81-8f61-ead3f99ffa52.png)

При локальном прогоне тестов некоторые из них ломаются с `java.nio.file.FileAlreadyExistsException`. Нужно пофиксить. Возможно, коллизия в именах файлов из-за короткого `HASH_SIZE`.

2022-03-27 18:25 UTC, incubos requested changes
Необходимо починить тесты. Кроме того, имеется ряд замечаний/вопросов/предложений.

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/TimestampEntry.java
> +        return key.byteSize() + (value == null ? 0 : value.byteSize()) + Long.BYTES;
`Long.BYTES` это длина ключа или значения? Почему только одного из них?

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/LSMDao.java
> +    public TimestampEntry get(MemorySegment key) throws IOException {
Да, понял, справедливо.

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +            return new MappedIterator(tableMemorySegment.asSlice(0, size));
Зачем здесь `asSlice()`?

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final long fromPosition = fromIndex > max ? size : MemoryAccess.getLongAtIndex(indexMemorySegment, fromIndex);
В случае `fromIndex > max` можно сразу возвращать пустой `Iterator`, разве нет?

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final int toIndex = to == null ? max + 1 : Math.abs(findIndexOfKey(to));
И здесь можно оптимизнуть крайний случай, когда `to` меньше всех элементов, верно?

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +            final MemorySegment foundKey = tableMemorySegment.asSlice(keyPosition + Long.BYTES, keySize);
Чуть лучше будет `current` или `candidate` вместо `foundKey`, согласны?

2022-03-27 18:25 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        while (data.hasNext()) {
Почему здесь `while`? Если такого ключа нет, то мы будем итерироваться до конца данных и проверять его наличие, верно?

2022-03-27 21:35 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/TimestampEntry.java
> +        return key.byteSize() + (value == null ? 0 : value.byteSize()) + Long.BYTES;
Это длина timestamp

2022-03-27 21:36 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +            return new MappedIterator(tableMemorySegment.asSlice(0, size));
копипаста 😊

2022-03-27 21:41 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final long fromPosition = fromIndex > max ? size : MemoryAccess.getLongAtIndex(indexMemorySegment, fromIndex);
\+

2022-03-27 21:42 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +        final int toIndex = to == null ? max + 1 : Math.abs(findIndexOfKey(to));
Тут как более-мене често сделать что-то не могу придумать, да и оно будет 0 и дальше будет срез от 0, до 0 например и по факту пустой итератор.

2022-03-27 21:42 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/sstable/SSTable.java
> +            final MemorySegment foundKey = tableMemorySegment.asSlice(keyPosition + Long.BYTES, keySize);
\+

2022-03-27 21:47 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        while (data.hasNext()) {
Оставил while просто добавил проверку, что ключ не больше того, что ищем 🤔

2022-03-27 21:52 UTC, step-ponomarev commented
Ура, только таймауты остались)

2022-03-30 10:58 UTC, incubos commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        while (data.hasNext()) {
Зачем так? В текущем виде, если искомого `key` нет (но есть бОльший), всегда будет 2 вызова `compare()`.

2022-03-30 11:01 UTC, incubos requested changes
Осталось одно замечание. После исправления будет 1.5х за этап.

2022-03-30 20:22 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/stepanponomarev/store/Storage.java
> +        while (data.hasNext()) {
поменял их местами 👍🏻

2022-04-01 09:36 UTC, incubos approved these changes
1.5x - 2 балла за оставшийся `while`.

2022-04-01 09:36 UTC, merged