Nikita_Zadorotskas_Stage_3
polis-vk/2022-nosql-lsm pull request #69
Opened 2022-03-13 10:16 UTC by zadorotskas

2022-03-20 16:14 UTC, Artyomcool requested changes
Полный балл * 1.5, поправьте замечания.

2022-03-20 16:14 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/MergedIterator.java
> +            if (iterators.get(i).getNumber() > maxNumber) {
Вот это можно внести в comparator, иначе в худшем случае у вас O(N)

2022-03-20 16:14 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/PersistentDao.java
> +            return (int) Files.list(config.basePath()).count() / 2;
очень сложно гарантировать, что в директории нет ни одного лишнего файла, их лучше бы фильтровать по имени.

2022-03-20 16:14 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/PersistentDao.java
> +            utils.createFilesIfNotExist(numberOfFiles);
вот тут выглядит несколько странным: кажется нужно гарантировать, что файл новый/пустой.

2022-03-24 12:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/MemorySegmentReader.java
> +        return low + ((high - low) / 2);
(low + high) >>> 1 тоже без переполнения, т.к. знаковый бит успешно утилизируется

2022-03-24 12:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/MergedIterator.java
> +            List<PeekIterator> iterators = getIteratorsWithSameKeys(result);
Довольно много аллокаций

2022-03-24 12:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/PersistentDao.java
> +        lock.readLock().lock();
В этом на текущий момент потребности нет

2022-03-24 12:38 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/MergedIterator.java
> +        next = result;
hasNext кажется вернет false, если checkIfWasDeleted вернёт null?

2022-03-24 14:44 UTC, zadorotskas commented on src/main/java/ru/mail/polis/nikitazadorotskas/MergedIterator.java
> +        next = result;
Не всегда, если checkIfWasDeleted вернет null, то мы дальше ищем, пока либо не встретим не null, либо пока куча не станет пустой (но тогда hasNext и должен вернуть null)

2022-03-24 14:54 UTC, Artyomcool commented
Да, согласен. Это корректно.

чт, 24 мар. 2022 г., 17:44 Nikita Zadorotskas ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/java/ru/mail/polis/nikitazadorotskas/MergedIterator.java
> <https://github.com/polis-vk/2022-nosql-lsm/pull/69#discussion_r834388452>
> :
>
> > +
>
> +    private void updateNext() {
>
> +        BaseEntry<MemorySegment> result = null;
>
> +
>
> +        while (result == null && minHeap.size() > 0) {
>
> +            PeekIterator iterator = minHeap.poll();
>
> +            result = iterator.current();
>
> +
>
> +            List<PeekIterator> iterators = getIteratorsWithSameKeys(result);
>
> +            iterators.add(iterator);
>
> +
>
> +            result = utils.checkIfWasDeleted(result);
>
> +            addIteratorsToHeap(iterators);
>
> +        }
>
> +
>
> +        next = result;
>
>
> Не всегда, если checkIfWasDeleted вернет null, то мы дальше ищем, пока
> либо не встретим не null, либо пока куча не станет пустой (но тогда hasNext
> и должен вернуть null)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/polis-vk/2022-nosql-lsm/pull/69#discussion_r834388452>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQXNNCKYHMMIAE6YJPKF6TVBR5UDANCNFSM5QTEPWNQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-03-31 12:54 UTC, Artyomcool approved these changes
полный балл * 1.5

2022-03-31 12:54 UTC, Artyomcool commented on src/main/java/ru/mail/polis/nikitazadorotskas/MemorySegmentReader.java
> +    private long countMid(long low, long high) {
Стоимость вызова (если не сработал inline во время JIT):
0. отсутствие вызова.
1. static-методы - очень дешево.
2. private - дороже чем static на "размещение" 1 аргумента (this).
3. package private/protected/public - дороже чем private, т.к. требуется дополнительно косвенная адресация.
4. interface - совсем дорого.

Исходя из этой таблички, предпочитайте 0 или 1 по возможности)

2022-03-31 12:54 UTC, merged