Lutsenko Dmitrii Stage3
polis-vk/2022-nosql-lsm pull request #71
Opened 2022-03-13 21:12 UTC by LutsenkoDm

2022-03-19 18:29 UTC, incubos commented
Нужно зарезолвить конфликты и подмёрджить `upstream/main`.

2022-03-19 19:00 UTC, incubos requested changes
Есть ряд критичных замечаний. В первую очередь нужно отрефакторить и **существенно упростить**.

2022-03-20 13:30 UTC, incubos commented
Нужно разрулить конфликты и подмёрджить `upstream/main` -- подъехали новые тесты.

2022-03-24 10:50 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        return new MergeIterator(from, to);
Исправил

2022-03-24 10:51 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            if (tempData.isEmpty() || (!isToNull && tempData.firstKey().compareTo(to) >= 0)) {
Сделал через implement AutoClosable

2022-03-24 10:52 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            mid = (left + right) / 2;
Описал данный момент в java doc

2022-03-24 10:52 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                    bufferedFileWriter.flush();
убрал

2022-03-24 10:52 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
>  public class InMemoryDao implements Dao<String, BaseEntry<String>> {
Переименовал

2022-03-24 10:52 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +    public class MergeIterator implements Iterator<BaseEntry<String>> {
Сделал отдельным

2022-03-24 10:53 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +    private static final Map<Config, Integer> configs = new HashMap<>();
сделал без static

2022-03-24 10:53 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            isFromNull = from == null;
Сделал через this

2022-03-24 10:54 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        boolean isFromNull;
Теперь final

2022-03-24 10:56 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        char[] writeBuffer = new char[Integer.BYTES];
Переделал на 16 битную, изначально делал по подобию byte, даже не обратил внимания, спасибо

2022-03-24 10:58 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            return -1;
конец файла по подобию всех методов BufferedReader. Описал подробнее в комментах

2022-03-24 10:58 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        return (ch1 << 24) + (ch2 << 16) + (ch3 << 8) + (ch4) - 1;
Убрал

2022-03-24 10:59 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            return null;
комментарии  написал

2022-03-24 10:59 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        bufferedReader.skip(Integer.BYTES);
Длину предыдущей строки

2022-03-24 11:00 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        return new BaseEntry<>(new String(keyChars), bufferedReader.readLine());
Обработал данный случай

2022-03-24 11:18 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                BufferedReader bufferedReader;
Да, исправил, отголоски прошлого

2022-03-24 11:18 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                bufferedReader = Files.newBufferedReader(path);
Сделал через implements autoclosable

2022-03-24 11:20 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                String fileMinKey = DaoUtils.readKey(bufferedReader);
Добавил

2022-03-24 11:21 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +    public static BaseEntry<String> ceilKey(Path path, BufferedReader bufferedReader,
Порефакторил

2022-03-24 11:21 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            int readBytes = bufferedReader.readLine().length();
Теперь проходит

2022-03-24 11:22 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            if (mid + prevEntryLength + readBytes >= right) {
Описал и формат и java doc для метода

2022-03-24 11:22 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +    public static BaseEntry<String> searchInFile(Path path, String key) throws IOException {
Убрал

2022-03-24 11:22 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return data.headMap(to, false).values().iterator();
Убрал лишнее

2022-03-24 11:22 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            return data.tailMap(from, true).values().iterator();
Убрал лишнее

2022-03-24 11:23 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        return data.subMap(from, true, to, false).values().iterator();
Убрал лишнее

2022-03-24 11:23 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +        if (data.isEmpty() || config == null) {
Убрал лишнее

2022-03-24 11:27 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +            bufferedFileWriter.write(DaoUtils.intToCharArray(0));
Длина предыдущей строки, так как это первая строка, то 0 для предыдущей. Описал в комментах еще

2022-03-24 11:27 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                bufferedFileWriter.write(baseEntry.value() + '\n');
Так как длина value не нужна

2022-03-24 11:28 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/InMemoryDao.java
> +                bufferedFileWriter.write(DaoUtils.intToCharArray(
Да, это необходимо для бинарного поиска. При чем именно на след строке

2022-03-24 12:37 UTC, incubos commented
Есть issue от CodeClimate.

2022-03-24 13:03 UTC, LutsenkoDm commented
> Есть issue от CodeClimate.Исправил. Дело в том что он завис, не мог посмотреть результат

2022-03-24 13:03 UTC, LutsenkoDm commented
> Есть issue от CodeClimate.

Исправил. Дело в том что он завис, не мог посмотреть результат

2022-03-24 13:08 UTC, LutsenkoDm commented
> Есть issue от CodeClimate.

Там было 2 issue, что я инициализировал boolean переменные и все

2022-03-24 13:25 UTC, incubos requested changes
Есть существенные замечания. PR не досмотрел. Передаю @Artyomcool .

2022-03-24 13:25 UTC, incubos commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +     * при этом не храня индексы для сдвигов ключей вовсе.
Если я правильно понимаю весь этот текст, вы пытаетесь обойтись без индекса, т.е. прыгать по файлу и пытаться выровняться по границе записи. В общем случае это невозможно. Такой подход изредка используют, но полагаются на контрольные суммы для каждой записи, чтобы снизить вероятность ложного обнаружения её границы до 0.
Предлагаю перестать мучаться и завести индекс (номер записи на смещение в файле) в любом удобном для вас виде.

2022-03-24 13:48 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/MergeIterator.java
> +            BufferedReader bufferedReader = Files.newBufferedReader(path, UTF_8);
Я сделал implements AutoClosable и в переопределенном методе close прописал логику закрытия дескрипторов. Мне кажется это наиболее подходящий вариант. Так как не очень понятно в каком моменте будет происходить закрытие, добежим мы до конца или нет, может вообще не будет вызваны next и  hasNext ни разу.

2022-03-24 14:04 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        return str.replace(NEXT_LINE_REPLACEMENT, NEXT_LINE_IN_STRING);
Все упирается в логику моего бинарного поиска. Мне кажется, что благодаря запрету какого-либо лишь одного символа можно было бы спокойно использовать мой подход к бинарному поиску или какой-то другой, что дало бы выигрыш как по памяти так и по производительности.

В текущей реализации все символы валидны, так как в теории если ключ содержит \\n, то будет замена на  \\\n, а при чтении обратно и все сработает?

Ведь в поиске с индексами надо еще сначала индекс найти и где-то хранить их все и так для каждого файла. Ведь если у нас 1_000_000 записей в файле, то будет ведь 1_000_000 индексов для сдвигов для каждого ключа? Я думал хранить диапазоны индексов, но это во-первых уже не бинарный поиск, да на прошлой лекции говорили что так можно, но ведь до этого требование было именно на бинарный поиск,  а во вторых их тоже надо дополнительно хранить и еще думать о выборе оптимальной длины диапазона и так далее.

2022-03-24 14:12 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        return postprocess(new String(keyChars));
Описал в ответе выше про это

2022-03-24 14:12 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +                ? postprocess(bufferedReader.readLine())
Описал в ответе выше про это

2022-03-24 14:17 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +     * offset нужен, чтобы пропустить к примеру минимальный и максимальный ключи в начале (См. Описание формата файла)
Можно и без них обойтись, но две записи только ключей позволяют не добавлять дескриптор файлов, которые не содержат наш range, в мапы в MergeIterator и как следствие потом не итерироваться по ненужным файлам при этом не выполняя бинарный поиск вовсе. Мне кажется такая оптимизация оправданной

2022-03-24 14:20 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        bufferedReader.read(keyChars);
Не очень понимаю зачем здесь менять на цикл если есть перегруженный метод read для записи в массив сразу. Или я не очень понял что имелось в виду.

2022-03-24 14:35 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +     * при этом не храня индексы для сдвигов ключей вовсе.
Размер кода все-таки почти в 1.5 раза больше 45 строк против 33.
Да идея в том, чтобы прыгнуть куда-угодно, сделать readline(), а на след строке будет длина этой записи и следующая гарантированно с начала. '\n' мешает конечно, но я сделал экранирование, про это и индексы в ответе выше. Моя логика была в том что такой подход лучше по памяти и производительности, а также он показался мне интереснее и не тривиальнее. Ложного обнаружения конца записи при экранировании '\n' или полном его отсутствии быть не может. И скажем такая жертва '\n' или любым другим символом, ведь тогда '\n' можно просто менять на символ, который точно не встретиться в ключе / значении может быть оправдана. Возникает вопрос: можно ли как-то гарантировать такой символ?

Но даже в текущей реализации все символы валидны, так как в теории если ключ содержит \\n, то будет замена на \\\n, а при чтении обратно и все сработает?

2022-03-24 14:37 UTC, LutsenkoDm commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +     * при этом не храня индексы для сдвигов ключей вовсе.
> Размер кода все-таки почти в 1.5 раза больше 45 строк против 33. 
Плюс это все-таки утильный метод и здесь некая сложность кода в пользу оптимизации должна допускаться. 
Да идея в том, чтобы прыгнуть куда-угодно, сделать readline(), а на след строке будет длина этой записи и следующая гарантированно с начала. '\n' мешает конечно, но я сделал экранирование, про это и индексы в ответе выше. Моя логика была в том что такой подход лучше по памяти и производительности, а также он показался мне интереснее и не тривиальнее. Ложного обнаружения конца записи при экранировании '\n' или полном его отсутствии быть не может. И скажем такая жертва '\n' или любым другим символом, ведь тогда '\n' можно просто менять на символ, который точно не встретиться в ключе / значении может быть оправдана. Возникает вопрос: можно ли как-то гарантировать такой символ?
> 
> Но даже в текущей реализации все символы валидны, так как в теории если ключ содержит \n, то будет замена на \\n, а при чтении обратно и все сработает?

2022-03-25 10:17 UTC, incubos commented
Предлагаю перейти в week 2 и продолжать биться, но уже за половину баллов, потому что вы не проблему чините, а втыкаете костыли.

2022-03-25 10:19 UTC, incubos requested changes
Если вы настаиваете на решении с escaping, реализуйте его корректно.

2022-03-25 10:20 UTC, incubos commented
> Предлагаю перейти в week 2 и продолжать биться, но уже за половину баллов, потому что вы не проблему чините, а втыкаете костыли.

Если будете продолжать практиковать такие фиксы, не вижу смысла в продолжении курса для вас.

2022-03-25 10:28 UTC, LutsenkoDm commented
> > Предлагаю перейти в week 2 и продолжать биться, но уже за половину баллов, потому что вы не проблему чините, а втыкаете костыли.
> 
> Если будете продолжать практиковать такие фиксы, не вижу смысла в продолжении курса для вас.

После вчерашней лекции в итоге все-таки хочу перейти на индексы, то что сейчас это неудачное временное решение, так как немного не дооценил экранирование + это не то чем хочется заниматься. Если изменения будут касаться только бинарного поиска и формата файла, но при этом логика в MergeIterator будет прежней, то это все равно половина баллов. На сколько я понимаю критический момент именно в '\n' символах?

2022-03-25 11:13 UTC, incubos commented
> > > Предлагаю перейти в week 2 и продолжать биться, но уже за половину баллов, потому что вы не проблему чините, а втыкаете костыли.
> > 
> > 
> > Если будете продолжать практиковать такие фиксы, не вижу смысла в продолжении курса для вас.
> 
> После вчерашней лекции в итоге все-таки хочу перейти на индексы, то что сейчас это неудачное временное решение, так как немного не дооценил экранирование + это не то чем хочется заниматься. Если изменения будут касаться только бинарного поиска и формата файла, но при этом логика в MergeIterator будет прежней, то это все равно половина баллов. На сколько я понимаю критический момент именно в '\n' символах?

К сожалению, не больше половины баллов. Текущая реализация самобытная, но не является корректной даже после нескольких итераций ревью до дедлайна. У нас нет запрещённых символов в ключах/значениях по постановке задачи. Либо нужно поднажать и сделать работу с delimiter корректной, либо перейти на явные индексы, либо что-то ещё корректное.

2022-03-25 11:56 UTC, LutsenkoDm commented
> > > > Предлагаю перейти в week 2 и продолжать биться, но уже за половину баллов, потому что вы не проблему чините, а втыкаете костыли.
> > > 
> > > 
> > > Если будете продолжать практиковать такие фиксы, не вижу смысла в продолжении курса для вас.
> > 
> > 
> > После вчерашней лекции в итоге все-таки хочу перейти на индексы, то что сейчас это неудачное временное решение, так как немного не дооценил экранирование + это не то чем хочется заниматься. Если изменения будут касаться только бинарного поиска и формата файла, но при этом логика в MergeIterator будет прежней, то это все равно половина баллов. На сколько я понимаю критический момент именно в '\n' символах?
> 
> К сожалению, не больше половины баллов. Текущая реализация самобытная, но не является корректной даже после нескольких итераций ревью до дедлайна. У нас нет запрещённых символов в ключах/значениях по постановке задачи. Либо нужно поднажать и сделать работу с delimiter корректной, либо перейти на явные индексы, либо что-то ещё корректное.

Если все-таки делать работу с delimiter корректной, то можете подсказать ресурсы или примеры корректного экранирования,  чтобы быть уверенным в отсутствии workaround? Не хотелось бы чтобы фиксы касающиеся delimiter были восприняты как костыли в отсутствии такого замысла.

2022-03-25 13:48 UTC, incubos commented
> Если все-таки делать работу с delimiter корректной, то можете подсказать ресурсы или примеры корректного экранирования, чтобы быть уверенным в отсутствии workaround? Не хотелось бы чтобы фиксы касающиеся delimiter были восприняты как костыли в отсутствии такого замысла.

Я переназначил PR на @Artyomcool . Может быть, он что-то подскажет. К сожалению, никаких годных ресурсов на эту тему я не встречал.

Если следовать этому подходу, то необходимо обеспечить, чтобы `unescape(escape(text)) == text` для любого `text`. В текущей реализации `\n` просто заменяется на `\\n` (и обратно), но если в исходном тексте уже есть `\\n`, то он превращается в `\n` в результате `unescape()`, т.е. сам `\\n` нужно экранировать в `escape()`.

2022-03-25 14:10 UTC, LutsenkoDm commented
> Если следовать этому подходу, то необходимо обеспечить, чтобы `unescape(escape(text)) == text` для любого `text`. В текущей реализации `\n` просто заменяется на `\\n` (и обратно), но если в исходном тексте уже есть `\\n`, то он превращается в `\n` в результате `unescape()`, т.е. сам `\\n` нужно экранировать в `escape()`.

Ок. У меня пока только идея, если каким-то образом можно было бы читать '\n' как два символа слэш и n, то удвоение слэшов и потом обратно решило бы проблему. Но как технически прочитать '\n' двумя символами я не знаю и не уверен возможно ли это вообще

2022-03-27 13:02 UTC, LutsenkoDm commented
В итоге из того что после дедлайна (до дедлайна тесты проходили, экранирование было некорректным, но тесты не ругались): поменял только методы отвечающие за экранирование так как решил все-таки попробовать сделать его корректно. Написал еще тестов с escape символами и '\n', тесты в текущем pull request. Надеюсь что текущая реализация не является workaround, если что заранее извиняюсь.

2022-03-31 13:03 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        bufferedWriter.write((k + '0') >>> 16);
Нет, ключ не может быть длинной 2^1000, предлагаю вам самостоятельно понять, почему.

2022-03-31 13:04 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        bufferedReader.read(keyChars);
Вы не только не поняли почему, вы даже не стали пытаться понять. Например, прочитать документацию по методу.

2022-03-31 13:04 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +            return null;
Более изящный способ - переписать код так, чтобы этот способ появился.

2022-03-31 13:05 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +     * offset нужен, чтобы пропустить к примеру минимальный и максимальный ключи в начале (См. Описание формата файла)
Вероятность, что такие файлы вообще будут, около 0.

2022-03-31 13:06 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        char[] charArray = str.toCharArray();
две огромных аллокации (можно было обойтись одной).

2022-03-31 13:06 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/DaoUtils.java
> +        if (!str.contains("\n") && !str.contains("\\")) {
каждый раз 3 прохода по строке.

2022-03-31 13:09 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/MergeIterator.java
> +        lastElementWithFilesMap.remove(polledEntry.key());
утекает дескриптор

2022-03-31 13:11 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lutsenkodmitrii/MergeIterator.java
> +            BufferedReader bufferedReader = Files.newBufferedReader(path, UTF_8);
Открывать файл на каждое чтение - дорого.
AutoCloseable не делает никакой магии. У MergeIterator'а close нигде не вызывается, а значит дескрипторы утекают.

2022-03-31 13:13 UTC, merged