Saskov Lev: Stage 3
polis-vk/2022-nosql-lsm pull request #74
Opened 2022-03-16 14:22 UTC by levs2001

2022-03-19 12:22 UTC, atimofeyev requested changes

2022-03-20 13:30 UTC, incubos commented
Нужно разрулить конфликты и подмёрджить `upstream/main` -- подъехали новые тесты.

2022-03-24 11:06 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            for (int partN = dataBasePartsC - 1; partN >= 0; partN--) {
Поправлю, просто ели успел попасть в дедлайн по последним тестам (добавил кучу и итераторы), поэтому руки не дошли.

2022-03-24 11:07 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            for (int partN = dataBasePartsC - 1; partN >= 0; partN--) {
Я бы и сейчас поправил, но я не понимаю, могу ли я сейчас вносить изменения, не получив 0 из-за работы после дедлайна.

2022-03-28 16:08 UTC, levs2001 commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +            for (int partN = dataBasePartsC - 1; partN >= 0; partN--) {
Поправил это в ветки для stage 4, над которой сейчас работаю на локальной машине.

2022-03-31 20:58 UTC, atimofeyev requested changes

2022-03-31 20:58 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/BinaryHeap.java
> +    public void add(PeekIterator iterator) {
В Java есть PriorityQueue, которая уже представляет из себя кучу

2022-03-31 20:58 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/StorageSystem.java
> +        addStoragePart(storagePartsC);
можно просто написать
addStoragePart(storagePartsC++);

2022-03-31 20:59 UTC, atimofeyev commented on src/main/java/ru/mail/polis/levsaskov/BinaryHeap.java
> +    public void add(PeekIterator iterator) {
можно на нее перейти в ветке stage4

2022-04-01 10:11 UTC, incubos commented
1.2x за MBB.

2022-04-01 10:11 UTC, merged