Lutsenko Dmitrii Stage 3 tests
polis-vk/2022-nosql-lsm pull request #76
Opened 2022-03-16 15:48 UTC by LutsenkoDm

2022-03-17 13:55 UTC, incubos requested changes
Есть ряд вопросов/предложений. Тесты должны быть максимально понятными, чтобы можно было разобраться, не приходя в сознание.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Есть же утильные методы типа `entryAt()` в `BaseTest` (здесь и ниже тоже). Давайте сделаем тесты более читаемыми?

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(dao.get(keyAt(5), null).next(), entryAt(5));
Более специфичный `allFrom()` вместо `get(..., null)` будет более читаемым (здесь и ниже).

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(dao.get(keyAt(5), null).next(), entryAt(5));
Так мы не проверяем, что внезапно нет ещё и других значений -- см. перегруженные методы `assertSame()`.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(entryIterator.next(), new BaseEntry<>(keyAt(46), longString));
Опять же не хватает проверки, что `entryIterator` больше ничего не содержит -- см. перегруженные `assertSame()` (здесь и ниже).

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Этот блок кода можно сделать более читаемым, если завести `new int[]{5, 8, ..., 41}` и цикл.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Применимы замечания из тестов выше.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        Iterator<Entry<String>> allIterator = dao.get(null, null);
Лучше `all()` вместо `get(null, null)` -- будет более читаемым.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Применимы замечания из тестов выше.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        Iterator<Entry<String>> entryIteratorFromEqualsFirsKey = dao.get(null, keyAt(8));
`allTo()`?

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
См. замечания к тестам выше.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +
Лишние пустые строки.

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertEmpty(dao.get(null, null));
`all()`/`allFrom()`/`allTo()`?

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +    void emptyCloses(Dao<String, Entry<String>> dao) throws IOException {
Хороший тест!

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(
Нужно ли это?

2022-03-17 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertValueAt(DaoFactory.Factory.reopen(dao), entityIndex1);
Может быть, проверить множество значений с каким-то шагом? Тест будет более глубоким.

2022-03-24 12:31 UTC, incubos commented
Здесь ожидаются исправления или оценивать по минимуму без merge?

2022-03-24 13:04 UTC, LutsenkoDm commented
> Здесь ожидаются исправления или оценивать по минимуму без merge?

Да, планируются исправления в ближайшем времени

2022-03-24 15:46 UTC, LutsenkoDm commented
> Здесь ожидаются исправления или оценивать по минимуму без merge?



> 



> Здесь ожидаются исправления или оценивать по минимуму без merge?

Изменения сделал. Добавил тесты на delete

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(dao.get(keyAt(5), null).next(), entryAt(5));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(dao.get(keyAt(5), null).next(), entryAt(5));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        Iterator<Entry<String>> allIterator = dao.get(null, null);
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Исправил

2022-03-24 15:47 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        Iterator<Entry<String>> entryIteratorFromEqualsFirsKey = dao.get(null, keyAt(8));
Исправил

2022-03-24 15:48 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        dao.upsert(new BaseEntry<>(keyAt(5), valueAt(5)));
Исправил

2022-03-24 15:48 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertEmpty(dao.get(null, null));
Исправил

2022-03-24 15:48 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +    void emptyCloses(Dao<String, Entry<String>> dao) throws IOException {
Исправил

2022-03-24 15:49 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertSame(
Убрал этот тест

2022-03-24 15:49 UTC, LutsenkoDm commented on src/test/java/ru/mail/polis/lutsenkodmitrii/Stage3Test.java
> +        assertValueAt(DaoFactory.Factory.reopen(dao), entityIndex1);
Убрал этот тест

2022-03-25 16:06 UTC, merged