Trofimov Artyom, Stage3
polis-vk/2022-nosql-lsm pull request #77
Opened 2022-03-16 16:08 UTC by artem24630

2022-03-19 14:14 UTC, atimofeyev requested changes

2022-03-19 14:14 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                input.seek(index & 0x7fffffff);
нужен тест на пустое значение, очень странных механизм убирания знака

2022-03-19 14:14 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/FileIterator.java
> +                raf.seek(pointer & 0x7fffffff);
здесь тот же странный механизм обнуления знакового бита, нужен тест с пустыми значениями

2022-03-19 14:37 UTC, atimofeyev requested changes

2022-03-19 14:37 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        while (queue.peek().hasNext() && queue.peek().peek().key().equals(nextEntry.key())) {
здесь нарушится порядок дочерних итераторов после первого вытаскивания, и мы уже потеряем порядок (по задумке же было что первый итератор всегда последний файл?)

2022-03-20 11:29 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                input.seek(index & 0x7fffffff);
да, наверное, такой механизм убирания знака здесь не требуется, притом что я ошибся и написал для инта,  а не для лонга. 
И не очень понял, что за тест на пустое значение. То есть чтобы ключ был пустым?

2022-03-20 11:38 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +        String name = generateString();
поправил

2022-03-20 11:38 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/FileIterator.java
> +                raf.seek(pointer & 0x7fffffff);
переделал с помощью Math.abs

2022-03-20 11:43 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        while (queue.peek().hasNext() && queue.peek().peek().key().equals(nextEntry.key())) {
да, задумка такая. Думаю, для решение этой проблемы можно добавить поле в PeekingIterator, которое отвечает за приоритет

2022-03-21 12:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                input.seek(index & 0x7fffffff);
строго говоря просто сбросить бит - это не есть взять число по модулю, отрицательные числа представляются в дополнительном коде, в общем в данном случае я бы так и написал Math.abs(index)

2022-03-21 12:54 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        while (queue.peek().hasNext() && queue.peek().peek().key().equals(nextEntry.key())) {
да, оно может помочь, нам надо чтобы каждый раз при пересортировке у нас было знанием какой файл более риоритетный

2022-03-21 13:07 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        while (queue.peek().hasNext() && queue.peek().peek().key().equals(nextEntry.key())) {
сделал

2022-03-23 20:12 UTC, atimofeyev requested changes

2022-03-23 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            //it is ok
it is ok только в случае FileNotFoundException
кстати откуда тут кидается NoSuchFileException?

ну и в случае EOFException точно не ок

2022-03-23 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        if (queue.size() == 1) {
без этой ветки можно было проще сделать, если проверять на queue.size() == 1 и в updateIterators делать более простую ветку

2022-03-23 20:34 UTC, atimofeyev requested changes

2022-03-23 20:34 UTC, atimofeyev commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                if (entry != null) {
а если мы последний апдейтом удалили запись (вставили null), то тут ты вернешь старую невалидную запись

2022-03-23 21:11 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/FileIterator.java
> +                byte tombstone = raf.readByte();
у меня тогда бы не работало, потому что там могилка ставилась только в файле индексов, а он читается только один раз при создании FileIterator, а затем я просто иду по файлику и не могу определять, удален элемент или нет

2022-03-23 21:15 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                if (entry != null) {
не, у нас же value = null при удалении, а не сама Entry, так что мне вернется свежая запись, где будет value = null, и потом я это проверю и верну уже просто null вместо entry

2022-03-23 22:15 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                if (entry != null) {
на это тесты есть

2022-03-23 22:15 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/MergeIterator.java
> +        if (queue.size() == 1) {
переделал

2022-03-23 22:16 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +            //it is ok
убрал NoSuchFileException и EOFException

2022-03-23 22:16 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/InMemoryDao.java
> +                mid = left + (right - left) / 2;
убрал повторы кода

2022-03-25 19:01 UTC, atimofeyev requested changes

2022-03-26 07:31 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/Utils.java
> +            return null;
поправил

2022-03-26 07:31 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/FileIterator.java
> +            nextEntry = null;
поправил

2022-03-26 07:31 UTC, artem24630 commented on src/main/java/ru/mail/polis/artyomtrofimov/FileIterator.java
> +            nextEntry = null;
готово

2022-03-27 11:41 UTC, atimofeyev approved these changes
18 баллов

2022-04-01 10:19 UTC, merged