Stage 3 Scheredin Artyom
polis-vk/2022-nosql-lsm pull request #80
Opened 2022-03-17 09:56 UTC by ArtyomScheredin

2022-03-19 19:50 UTC, incubos commented
Нужно зарезолвить конфликты и подмёрджить `upstream/main`.

2022-03-19 20:27 UTC, incubos requested changes
Есть ряд замечаний/вопросов.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        try (FileChannel infoChannel = FileChannel.open(pathToReadMetaInfo,
Есть множество полезных утилитных методов в стандартном классе `Files`, чтобы прочитать всё содержимое файла за один вызов.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        Collections.reverse(iterators);
Модифицировать коллекции, которые передают в качестве аргументов, не очень популярная практика. Обычно делают defensive copy и потом её модифицируют.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +                buffer.add(null);
Может быть, такие итераторы просто выбрасывать?

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +            if (buffer.get(i) != null) {
Проверка становится относительно дорогой, когда у нас все итераторы (из большого количества) кроме одного из последних исчерпались. Надо соптимизировать.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +    public MergeIterator(List<Iterator<BaseEntry<ByteBuffer>>> iterators) {
Т.е. у нас есть неявный контракт, что у последних итераторов в списке наибольший приоритет, верно? Надо бы его зафиксировать в JavaDoc.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        refreshBuffer(minKey);
У нас тут 3 линейных сканирования по всем итераторам, верно? Хотелось бы оптимальнее. Представьте, что у нас тысячи крошечных итераторов.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +                while (it.hasNext()) {
Зачем здесь цикл? Разве в отдельно взятом итераторе ключи могут быть одними и теми же?

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                iteratorsList.add(new FileIterator(path, from, to));
Открывать файлы на каждый запрос совсем неэффективно. Надо соптимизировать.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +    public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Чем не устраивает дефолтный `Dao.get()`?

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        return inMemoryData.subMap(from, to).values().iterator();
Почему не в `else`? Выбивается стилистически.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                BaseEntry<ByteBuffer> entry = getEntryIfExists(path, key);
Неэффективно переоткрывать все файлы на каждый `get()`.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        dataBuffer.rewind();
Зачем эти вызовы `rewind()`?

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                     StandardOpenOption.TRUNCATE_EXISTING);) {
Лишняя `;`.

2022-03-19 20:27 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +            ByteBuffer writeIndexBuffer = mapChannelIndex(indexChannel);
Довольно неожиданно, что вызов `mapChannelData()` вызывает итерацию по всем данным. Лучше проитерироваться явно и передать размер файла, который нужно отмапить.

2022-03-20 09:52 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/Utils.java
> +        ByteBuffer curValue = dataBuffer.slice(offset, valueSize);
Пока что никак. В следующем коммите реализую. Планирую записывать valueSize = -1

2022-03-20 09:52 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/test/artyomscheredin/DaoFactoryMemorySegment.java
> -public class DaoFactoryMemorySegment implements DaoFactory.Factory<MemorySegment, BaseEntry<MemorySegment>> {
Тяжело писать под мемори сегмент, много ошибок, про которые почти нет информации в гугле. Решил понизить уровень сложности. Тем более байтбуффер повсеместно используется и навыки работы с ним будут полезны в будущем

2022-03-20 10:06 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/Utils.java
> +    public record Pair<E>(E dataPath, E indexPath) {
Получается, использование рекордов лучше всегда избегать? Здесь Pair используется исключительно для инкапсуляции двух переменных и не содержит никакой внутренней логики. Разве для этого рекорд не подходит идеально?

2022-03-20 10:14 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        try (FileChannel infoChannel = FileChannel.open(pathToReadMetaInfo,
переписал

2022-03-20 10:17 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        try (FileChannel infoChannel = FileChannel.open(pathToReadMetaInfo,
Думал, что если пишу вариант на байтбуффере, то всё взаимодействие с данными на диски нужно через маппинг файлов делать

2022-03-20 10:39 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        Collections.reverse(iterators);
переделал

2022-03-20 10:39 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +                buffer.add(null);
исправил

2022-03-20 10:41 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +                while (it.hasNext()) {
вы правы

2022-03-20 11:21 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +    public MergeIterator(List<Iterator<BaseEntry<ByteBuffer>>> iterators) {
зафиксировал

2022-03-20 12:07 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +            if (buffer.get(i) != null) {
Теперь из буффера удаляются закончившиеся итераторы. Нужно всегда контролировать, чтобы индексы в буффере соответствовали индексам итераторов в списке. Пришёл к тому, что вместо использования буффера со след значениями, храню пик-итераторы в списке в порядке убывания приоритета.

2022-03-20 12:45 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +    public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Всем устраивает. Эта реализация осталась с прошлого stage. Удалю

2022-03-20 12:46 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        return inMemoryData.subMap(from, to).values().iterator();
добавил else

2022-03-20 12:46 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                iteratorsList.add(new FileIterator(path, from, to));
Теперь маплю файлы в конструкторе дао

2022-03-20 12:48 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                     StandardOpenOption.TRUNCATE_EXISTING);) {
убрал

2022-03-20 12:53 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +            ByteBuffer writeIndexBuffer = mapChannelIndex(indexChannel);
Я не буду выносить маппинг каналов в отдельные функции, потому что, если подсчитывать размер в функции store, то mapChannelData() и mapChannelIndex() получаются по одной строке

2022-03-20 13:29 UTC, incubos commented
Нужно разрулить конфликты и подмёрджить `upstream/main` -- подъехали новые тесты.

2022-03-20 13:54 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/Utils.java
> +    public record Pair<E>(E dataPath, E indexPath) {
Речь лишь про название: `Pair` слишком абстрактно, при этом его поля вполне конкретные.

2022-03-20 13:54 UTC, incubos commented on src/main/java/ru/mail/polis/test/artyomscheredin/DaoFactoryMemorySegment.java
> -public class DaoFactoryMemorySegment implements DaoFactory.Factory<MemorySegment, BaseEntry<MemorySegment>> {
Понятно.

2022-03-20 16:49 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/Utils.java
> +    public record Pair<E>(E dataPath, E indexPath) {
Понятно, спасибо

2022-03-21 14:52 UTC, incubos requested changes
Есть ряд замечаний/вопросов.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/FileIterator.java
> +        dataBuffer.rewind();
Зачем эти вызовы `rewind()`? Вы же всегда работаете с буферами по абсолютному смещению и не модифицируете `position`.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/FileIterator.java
> +        return Utils.readEntry(dataBuffer, indexBuffer.getInt());
Здесь возникнет проблема при конкурентных запросах, но потом. Догадываетесь почему?

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/FileIterator.java
> +                low = ++mid;
Зачем инкрементировать сам `mid`? Выглядит неожиданно.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PeekIterator.java
> +        int keyComparison = this.peek().key().compareTo(e2.peek().key());
Здесь возникнет исключение, если один из итераторов пуст, но обычно `compare` **определён** для такого случая.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        List<PeekIterator> iteratorsCopy = new LinkedList<>(iterators);
Это лишнее копирование, потому что `stream()` ниже не модифицирует исходный `iterators`.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        this.iteratorQueue = new PriorityQueue<PeekIterator>();
Тип generic лишний.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        iteratorsCopy = iteratorsCopy.stream().filter(Objects::nonNull)
Вообще это антипаттерн: инициализировать переменную `iteratorsCopy` строчкой выше, чтобы сразу её перезаписать.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        checkNextValueAndFix();
В такой реализации инстанцирование могильных итераторов, у которых не будут дёргать `next()`, становится довольно дорогим. Можем отложить `checkNextValueAndFix()` до извлечения элемента?

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +    private void checkNextValueAndFix() {
Название метода неговорящее. По сути мы пропускаем могилы и значения, которые они накрывают, верно?

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        mappedDiskData = mapDiskData();
Не хватает `this.`.

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                iteratorsList.add(new PeekIterator(new FileIterator(pair.getDataBuffer().rewind(),
Зачем эти вызовы `rewind()`?

2022-03-21 14:52 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        int index = readPrevIndex() + 1;
Почему не `mappedDiskData.size()` вместо `readPrevIndex()`?

2022-03-21 19:33 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +import static java.nio.file.Files.readAllBytes;
понятно, исправлю

2022-03-21 19:42 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/FileIterator.java
> +        dataBuffer.rewind();
да, вы правы. Хотел подстраховаться и не заметил, что не изменяю позицию у буфферов

2022-03-21 19:43 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +        dataBuffer.rewind();
В новых коммитах бинарный поиск перенесён в файл-итератор и там нет сброса позиции у буфферов

2022-03-21 19:55 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/FileIterator.java
> +                low = ++mid;
поправил

2022-03-22 17:59 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/PersistentDao.java
> +                iteratorsList.add(new PeekIterator(new FileIterator(pair.getDataBuffer().rewind(),
В моей реализации файловый итератор меняет позицию в буффере индексов, при этом меняется позиция и в буффере индексов в дао. Поэтому перед каждый созданием файлового итератора я сбрасывал позицию в буффере. Я осознал, что этот подход не будет работать в многопоточности и некоторых других и случаях и переписал. Теперь файловый итератор не меняет позицию переданных буфферов

2022-03-22 18:02 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        this.iteratorQueue = new PriorityQueue<PeekIterator>();
исправил

2022-03-22 18:04 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        iteratorsCopy = iteratorsCopy.stream().filter(Objects::nonNull)
исправил

2022-03-22 18:11 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        checkNextValueAndFix();
в таком случае, нам придется при каждом вызове hasNext() вызывать checkNextValueAndFix(). Оно нам нужно?

2022-03-22 18:11 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +    private void checkNextValueAndFix() {
Переименовал

2022-03-25 16:16 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/PeekIterator.java
> +        int keyComparison = this.peek().key().compareTo(e2.peek().key());
Поправите для общности? Можно использовать аналогию со сравнением строк, в т.ч. пустых.

2022-03-25 16:19 UTC, incubos commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        checkNextValueAndFix();
Да, но разве повторные вызовы `checkNextValueAndFix()` не бесплатны (почти)? Хотя мы в `next()` тоже дёргаем. Убедили.

2022-03-25 16:23 UTC, incubos requested changes
Есть несколько мелких замечаний. После исправления +20% за этап за BB.

2022-03-26 10:59 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        List<PeekIterator> iteratorsCopy = new LinkedList<>(iterators);
поправил

2022-03-26 11:02 UTC, ArtyomScheredin commented on src/main/java/ru/mail/polis/artyomscheredin/MergeIterator.java
> +        List<PeekIterator> iteratorsCopy = new LinkedList<>(iterators).stream().filter(Objects::nonNull)
незачем, уберу

2022-03-27 18:30 UTC, incubos approved these changes
1.2x за `MappedByteBuffer`

2022-03-31 14:54 UTC, merged