Kiselyov Alexander Stage3
polis-vk/2022-nosql-lsm pull request #81
Opened 2022-03-17 22:08 UTC by AlexanderKiselyov

2022-03-20 16:59 UTC, Artyomcool commented
Почините тесты для ревью

2022-03-24 13:24 UTC, Artyomcool requested changes
Решение не соответствует ТЗ. Кроме того, поработайте над качеством кода, чтобы можно было предметно ревьюить.

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(indexPath));
открывать файл на каждое чтение - дорого

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(path))) {
открывать файл на каждое чтение - дорого

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(indexPath))) {
открывать файл на каждое чтение - дорого

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        NavigableMap<byte[], BaseEntry<byte[]>> diskPairs = new ConcurrentSkipListMap<>(Arrays::compare);
загрузка всех данных в память была запрещена. не понятно как вы уложились в тесты, возможно мы подтюним значения в тестах.

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +                && Arrays.compare(nextMemoryEntry.key(), nextDiskEntry.key()) == 0) {
довольно дорого производить полное сравнение на каждой итерации

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +            return hasNext();
StackOverflow рано или поздно придёт. Напомню, вы работаете с условно бесконечным потоком данных.

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +    }
вам не кажется что код одинаков?

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +public class MergeIterator implements Iterator<BaseEntry<byte[]>> {
дублирование кода должно было подсказать, что выбран не лучший путь

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +    private BaseEntry<byte[]> compareNotNullEntries() {
не очень понимаю, как работает этот метод

2022-03-24 13:24 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        }
не очень понимаю, почему тут два настолько похожих участка кода

2022-03-30 15:21 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +public record FileOperations(Config config, long filesCount, String fileName) {
исправил

2022-03-30 15:22 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(indexPath));
исправил, теперь открытие происходит только для чтения всех нужных записей за раз

2022-03-30 15:22 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        try (FileInputStream fis = new FileInputStream(String.valueOf(path))) {
исправил

2022-03-30 15:23 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +                && Arrays.compare(nextMemoryEntry.key(), nextDiskEntry.key()) == 0) {
поменял итератор полностью

2022-03-30 15:23 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +            return hasNext();
исправлено

2022-03-30 15:23 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +    }
исправлено

2022-03-30 15:24 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/MergeIterator.java
> +    private BaseEntry<byte[]> compareNotNullEntries() {
исправлено

2022-03-30 15:24 UTC, AlexanderKiselyov commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        }
исправлено

2022-03-31 06:47 UTC, AlexanderKiselyov commented
IndexedPeekIterator и MergeIterator были взяты с лекций

2022-03-31 13:19 UTC, Artyomcool approved these changes
Как я говорил на занятии, брать мой код для ДЕЙСТВУЮЩЕГО задания - плохая затея.
В итоге в вашей работе то, что заслуживает оценки, сильно уменьшено, и написано неоптимально.
Полный балл * 2/3.

2022-03-31 13:19 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +                ssTables = pathStream.toList().stream()
stream -> list -> stream...
Выглядит очень странно.

2022-03-31 13:19 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +        long mid = (low + high) / 2;
В данном случае всё ок, но будьте осторожны с переполнениями.

2022-03-31 13:19 UTC, Artyomcool commented on src/main/java/ru/mail/polis/alexanderkiselyov/FileOperations.java
> +    private static final int BUFFER_SIZE = 4000 * Character.BYTES;
на самом деле, оптимальный размер около 120кб.

2022-03-31 13:20 UTC, merged