Implement deletion tests for Stage 3
polis-vk/2022-nosql-lsm pull request #84
Opened 2022-03-18 23:42 UTC by Sanerins

Косницкий Александр

2022-03-19 12:52 UTC, incubos requested changes
Имеется ряд замечаний.

2022-03-19 12:52 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertFalse(dao.get(keyAt(1), null).hasNext());
`allFrom()`?

2022-03-19 12:52 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +    void CheckFlow(Dao<String, Entry<String>> dao) throws IOException {
Методы должны называться с маленькой буквы.

2022-03-19 12:52 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        Iterator<Entry<String>> iter = dao.get(null, null);
`all()`?

2022-03-19 12:52 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(iter.next(), entryAt(1));
См. перегруженные методы `assertSame()` -- можно переписать понятнее.

2022-03-19 12:52 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +public class PersistentDeleteTest extends BaseTest {
Нужно больше разнообразных тестов по аналогии с тестированием корректности merge, в частности:

- disk + mem
- запись, удаление, запись для disk/mem/disk+mem
- разнообразные range запросы, пересекающие могилки, для disk/mem/disk + mem

2022-03-19 19:59 UTC, incubos commented
> Имеется ряд замечаний.

Исправления ожидаются до понедельника, чтобы вмёрджить и дать студентам шанс поправить свои решения. В противном случае мы опубликуем собственный набор тестов и дополнительных баллов, к сожалению, не будет. Спасибо за понимание.

2022-03-19 23:18 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        Iterator<Entry<String>> iter = dao.get(null, null);
Действительно, теперь использую

2022-03-19 23:18 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(iter.next(), entryAt(1));
Улучшил

2022-03-19 23:20 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +    void CheckFlow(Dao<String, Entry<String>> dao) throws IOException {
Ой...

2022-03-19 23:23 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertFalse(dao.get(keyAt(1), null).hasNext());
Исправил

2022-03-20 01:43 UTC, Sanerins commented
Тесты были существенно доработаны, было добавлено много "подлых" ситуаций, таких, как начало и конец итераторов на удаленных сущностях, поиск значений среди удаленных, а так же жесткий компот из проверок в последнем тесте, который позволяет эффективно проверить работоспособность благодаря разработанному для этого API

2022-03-20 01:45 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +public class PersistentDeleteTest extends BaseTest {
Постарался разнообразить тесты

2022-03-20 12:23 UTC, incubos requested changes
Хорошие тесты! Есть набор небольших предложений по улучшению.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertFalse(dao.get(keyAt(2), keyAt(9)).hasNext());
Лучше до 10.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allTo(keyAt(9)), 1);
И здесь тоже до 10 (граничный случай).

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allFrom(keyAt(2)), 10);
И здесь как выше.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.get(keyAt(2), keyAt(9)), 5);
Давайте до 10.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allTo(keyAt(9)), 1, 5);
И тут.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allFrom(keyAt(2)), 5, 10);
И здесь как выше.

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                    List.copyOf(values.tailSet(entryAt(i * oneForth), true)));
Зачем указывать `true`?

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                    List.copyOf(values.headSet(entryAt(i * oneForth), false)));
Зачем указывать `false`?

2022-03-20 12:23 UTC, incubos commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                List.copyOf(values.subSet(entryAt(size / 4), true,
Сгодится `subSet()` без `true`/`false`.

2022-03-20 12:59 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +import java.util.SortedSet;
Лишний импорт убрал

2022-03-20 12:59 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertFalse(dao.get(keyAt(2), keyAt(9)).hasNext());
Действительно, совсем забыл про то, что у нас exclusive, когда писал данный тест

2022-03-20 13:00 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allTo(keyAt(9)), 1);
сделано

2022-03-20 13:00 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allFrom(keyAt(2)), 10);
исправил

2022-03-20 13:00 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.get(keyAt(2), keyAt(9)), 5);
согласен

2022-03-20 13:00 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allTo(keyAt(9)), 1, 5);
сделано

2022-03-20 13:00 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +        assertSame(dao.allFrom(keyAt(2)), 5, 10);
исправил

2022-03-20 13:01 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                    List.copyOf(values.tailSet(entryAt(i * oneForth), true)));
У меня фобия exclusive/inclusive небольшая, рационально тут явно прописывать не надо, конечно)

2022-03-20 13:01 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                    List.copyOf(values.headSet(entryAt(i * oneForth), false)));
Исправил

2022-03-20 13:02 UTC, Sanerins commented on src/test/java/ru/mail/polis/alexanderkosnitskiy/PersistentDeleteTest.java
> +                List.copyOf(values.subSet(entryAt(size / 4), true,
действительно, полностью согласен с этим

2022-03-20 13:02 UTC, Sanerins commented
Постарался решить все вышеуказанные недостатки

2022-03-20 13:25 UTC, incubos commented
Спасибо за contribution! +6 баллов.

2022-03-20 13:26 UTC, merged