Baidiya Rosan HW2
polis-vk/2022-nosql-lsm pull request #88
Opened 2022-03-20 01:40 UTC by AirBurn0

- [x] Бинарный поиск
- [x] Итератор по всем файлам
- [x] Проходит тесты
- [ ] Хороший код
- [ ] Поддерживает удаления

2022-03-20 13:33 UTC, incubos requested changes
Решение не проходит новые тесты.

2022-03-22 11:30 UTC, AirBurn0 commented
> Решение не проходит новые тесты.

Теперь проходит

2022-03-23 17:14 UTC, incubos requested changes
Есть критичные замечания, в таком виде не больше 5 баллов. Требуются исправления ASAP.

2022-03-23 17:14 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +public class MemoryAndDiskDao extends InMemoryDao implements Dao<ByteBuffer, BaseEntry<ByteBuffer>> {
Без IDE теперь читать код становится невозможным.

2022-03-23 17:14 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private BaseEntry<ByteBuffer> getInFile(ByteBuffer key) throws IOException {
См. комментарий выше -- этот код становится не нужным. Наша цель написать максимально лаконичную и компактную реализацию, а не порождать отдельные похожие методы под частные случаи.

2022-03-23 17:14 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private long[] getIndexArray(int fileNumber) throws IOException {
Затягивать индекс в память не хотелось бы -- он может быть довольно большим в случае большого количества записей с маленькими ключами и значениями.

2022-03-26 15:37 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private long[] getIndexArray(int fileNumber) throws IOException {
Исправил на реализацию с MappedByteBuffer

2022-03-26 15:37 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private BaseEntry<ByteBuffer> getInFile(ByteBuffer key) throws IOException {
Исправил на стандартную реализацию get()

2022-03-26 15:37 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Исправил на стандартную реализацию get()

2022-03-26 15:38 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                return Collections.emptyIterator();
Логично, добавил

2022-03-26 15:39 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +        try (FileChannel in = FileChannel.open(filePath, StandardOpenOption.READ)) {
Исправил на реализацию с MappedByteBuffer и теперь открываю файлы только один раз

2022-03-26 15:39 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            Files.createDirectory(indexesDir);
Убираю, тогда

2022-03-26 15:39 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +import static ru.mail.polis.baidiyarosan.FileUtils.writeOnDisk;
Оу... Убрал

2022-03-26 15:40 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/SimpleDaoIterator.java
> +public class SimpleDaoIterator implements Iterator<BaseEntry<ByteBuffer>> {
Переименовал, надеюсь новое название передает идею класса

2022-03-26 15:41 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/DaoIterator.java
> +    private BaseEntry<ByteBuffer> skipSame(BaseEntry<ByteBuffer> check, int max) {
Переименовал

2022-03-26 15:43 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +public class MemoryAndDiskDao extends InMemoryDao implements Dao<ByteBuffer, BaseEntry<ByteBuffer>> {
Убрал

2022-03-26 15:44 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
>  public class InMemoryDao implements Dao<ByteBuffer, BaseEntry<ByteBuffer>> {
В ней меньше проверок и вызовов внешних методов, думаю она больше подходит для работы с только данными памяти

2022-03-26 15:44 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +            long[] indexes = getIndexArray(file);
Убрал, теперь везде вызовы с использованием MappedByteBuffer

2022-03-26 15:45 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        ByteBuffer indexBuffer = ByteBuffer.allocate(collection.size() * Long.BYTES);
Логично, переделал этот момент

2022-03-26 15:46 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        Path indexPath = path.resolve(Paths.get(FileUtils.INDEX_FOLDER,
Сортировать файлы проще, как по мне. На деле - просто косметическое решение

2022-03-26 15:46 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +            buffer.putInt(entry.value().capacity()).put(entry.value());
оу, да.

2022-03-26 15:48 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return 2 * Integer.BYTES + entry.key().capacity() + (entry.value() == null ? 0 : entry.value().capacity());
Честно, не знал... Переделал все вызовы.
Правда, не особо понимаю, в чем разница для моего кейса?

2022-03-26 15:48 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        buffer.putInt(entry.key().capacity()).put(entry.key());
Честно, не знал... Переделал все вызовы.

2022-03-26 15:49 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        in.position(pos);
Исправил на реализацию с MappedByteBuffer, однако не уверен, исправляет ли API MappedByteBuffer'а эту проблему

2022-03-26 15:50 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return readBuffer(in, FileUtils.readInt(in, temp));
Ух, артефакты разделения API, неаккуратно зарефакторил

2022-03-26 15:52 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +        if (FileUtils.getPaths(config.basePath()).size() == 0) {
Оно быстрее если файлов в файловой системе нет, хоть и незначительно

2022-03-26 16:50 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/DaoIterator.java
> +    public DaoIterator(PriorityQueue<PeekIterator<BaseEntry<ByteBuffer>>> heap) {
Окей, принимаем collection теперь

2022-03-26 16:51 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/DaoIterator.java
> +        PeekIterator<BaseEntry<ByteBuffer>> nextIter;
А это чем-то плохо?

2022-03-26 16:52 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                new PriorityQueue<>(Comparator.comparing(o -> o.peek().key()));
И правда

2022-03-26 16:53 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/DaoIterator.java
> +                return peek();
Могилы фильтровать, чтоб `hasNext()` `true` не выдал, если там одни могилы дальше
Ничего умнее не придумал

2022-03-26 16:54 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/DaoIterator.java
> +    public BaseEntry<ByteBuffer> peek() {
Сделал private, теперь это какая-то странная внутренняя логика для реализации `hasNext()`

2022-03-26 16:54 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/SimpleDaoIterator.java
> +    public SimpleDaoIterator(PeekIterator<BaseEntry<ByteBuffer>> iter) {
Оказалось что не нужен, его теперь там и нет, спасибо.

2022-03-26 16:56 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    private BaseEntry<ByteBuffer> binarySearchFile(Path searchPath, ByteBuffer key)
По крайней мере этот дубликат убрал

2022-03-26 17:42 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        while (min <= max) {
Написал другой

2022-03-26 17:42 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +    public static int getEndIndex(FileChannel in, long[] indexes, ByteBuffer key, ByteBuffer temp)
Теперь бинарный поиск один.

2022-03-26 17:48 UTC, AirBurn0 commented
Исправил большинство замечаний и изменил подход к работе с памятью

2022-03-27 15:40 UTC, incubos commented
Concurrent тесты не проходят. Локально у меня тоже воспроизводится:
```
> Task :test

BasicConcurrentTest > testConcurrentRW_2_500(Dao) > ru.mail.polis.BasicConcurrentTest.testConcurrentRW_2_500(Dao)[1] FAILED
    java.util.concurrent.TimeoutException at TimeoutInvocation.java:70

BasicConcurrentTest > testConcurrentRead_8_000(Dao) > ru.mail.polis.BasicConcurrentTest.testConcurrentRead_8_000(Dao)[1] FAILED
    java.util.concurrent.TimeoutException at TimeoutInvocation.java:70

77 tests completed, 2 failed
```

2022-03-27 15:42 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return 2 * Integer.BYTES + entry.key().capacity() + (entry.value() == null ? 0 : entry.value().capacity());
В вашем кейсе всё может работать корректно, но по спеке `capacity()` может быть гораздо больше, чем `remaining()`, потому что кто-то явно мог выставить в `ByteBuffer` `position` и `limit`, чтобы предоставить вашему коду slice данных.

2022-03-27 15:43 UTC, incubos commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +        if (FileUtils.getPaths(config.basePath()).size() == 0) {
Да, верно, но DAO мы открываем один раз, чтобы потом долго с ним работать, т.е. на практике кода больше, а профита мало

2022-03-27 16:34 UTC, incubos requested changes
Имеется ряд существенных замечаний.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return min;
Метод `getInFileCollection()` проверяет возвращаемое значение на `-1` -- в каких случаях возвращается `-1`?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return min;
Если я правильно понимаю код, то в случае, если `key` больше всех элементов массива, мы вернём индекс сразу за массивом, а если `key` меньше всех элементов массива, то -- **0**.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +           return new InMemoryDao(config);
Поддерживать 2 реализации DAO так себе идея, пусть и такую простую как `InMemoryDao`. Предлагаю остановиться на одной.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDao.java
>      public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Чем нас не устраивает default реализация в интерфейсе `Dao`?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +                return peek();
Рекурсия здесь недопустима: у нас может быть "кладбище" из многих могил и мы упадём по `StackOverflowException`.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +                return peek();
Если что, в Java всё ещё нет tail-call optimization.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +public class InMemoryDaoIterator implements Iterator<BaseEntry<ByteBuffer>> {
Неудачное название, скорее, это `TombstoneFilteringIterator` или что-то наподобие, верно?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +    public BaseEntry<ByteBuffer> next() {
По контракту `Iterator` реализация `next()` должна кидать `NoSuchElementException`, если итератор исчерпан.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +public class MemoryAndDiskDaoIterator implements Iterator<BaseEntry<ByteBuffer>> {
Не совсем удачное название класса, потому что в коде нет ни memory, ни disk. `MergingIterator`?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +    public BaseEntry<ByteBuffer> next() {
Добавил тест. Теперь PR не проходит.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +        this.heap = new PriorityQueue<>(Comparator.comparing((PeekIterator<BaseEntry<ByteBuffer>> i) ->
Этот компаратор имеет смысл засунуть в константу, чтобы не создавать лишние объекты каждый раз.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +    public BaseEntry<ByteBuffer> next() {
См. JavaDoc к `Iterator.next()` про `NoSuchElementException`.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +        PeekIterator<BaseEntry<ByteBuffer>> nextIter;
Почему эта переменная объявлена вне цикла, а не по месту первого присваивания?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +            if (heap.peek() == null) {
Почему не первым условием `while`?

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +            if (heap.peek() != null) {
Эта проверка здесь выглядит лишней и усложняет код.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +                return peek();
Рекурсия здесь недопустима из-за возможных "кладбищ". Добавлены тесты, которые данное решение не проходит.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                try (FileChannel in = FileChannel.open(filePath, StandardOpenOption.READ);
Открывать все файлы и делать `mmap()` на каждый `get()` трудно назвать эффективным решением.

2022-03-27 16:34 UTC, incubos commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
Давайте просто выпилим эту реализацию? Default `get()` сводится к range, который уже фильтрует могилы, верно?

2022-03-29 12:19 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +                try (FileChannel in = FileChannel.open(filePath, StandardOpenOption.READ);
он открывает их только если до этого не открывал,
иначе он пишет это в map, и во второй раз пытается прочитать уже оттуда

2022-03-29 12:23 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +public class InMemoryDaoIterator implements Iterator<BaseEntry<ByteBuffer>> {
Понял, переименовал

2022-03-29 12:26 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +    public static ByteBuffer readMappedBuffer(MappedByteBuffer in, int pos) {
Исправил

2022-03-29 12:26 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        ByteBuffer val = in.slice(pos + 2 * Integer.BYTES + keySize, valSize);
Сделано обновлением `currPos`

2022-03-29 12:31 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +        return min;
удалил, таких кейсов на данный момент нет

2022-03-29 12:35 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDao.java
> +    public BaseEntry<ByteBuffer> get(ByteBuffer key) throws IOException {
сделал

2022-03-29 12:43 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +            if (to.compareTo(readMappedBuffer(file, intAt(index, end))) <= 0) {
вообще, `>`, это особенность реализации бинарного поиска, который может выкинуть такой `min`, что при `min == max`, `min = mid + 1`, тогда как это формально больше `max` на 1

сделал `end == size + 1` и прокомментировал, а то с этими поисками какая-то каша

2022-03-29 12:47 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +            if (to.compareTo(readMappedBuffer(file, intAt(index, end))) <= 0) {
не факт что бинарный поиск нашел конкретный элемент

2022-03-29 12:51 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/FileUtils.java
> +            if (to.compareTo(readMappedBuffer(file, intAt(index, end))) <= 0) {
метод мог выкинуть элемент, превосходящий ключ поиска, отсюда для реализации exclusive я отбрасываю такие элементы и шагаю назад

2022-03-29 12:55 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +    public BaseEntry<ByteBuffer> next() {
> По контракту `Iterator` реализация `next()` должна кидать `NoSuchElementException`, если итератор исчерпан.

Исправил

2022-03-29 12:58 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +            if (heap.peek() != null) {
Перенес

2022-03-29 13:01 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +            if (heap.peek() == null) {
Перенес

2022-03-29 13:02 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +        this.heap = new PriorityQueue<>(Comparator.comparing((PeekIterator<BaseEntry<ByteBuffer>> i) ->
Сделал

2022-03-29 13:08 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +                return peek();
> Если что, в Java всё ещё нет tail-call optimization.

очень жаль

2022-03-29 13:09 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/InMemoryDaoIterator.java
> +                return peek();
> Рекурсия здесь недопустима: у нас может быть "кладбище" из многих могил и мы упадём по `StackOverflowException`.

заменил на `do` `while()`

2022-03-29 14:50 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/baidiyarosan/MemoryAndDiskDaoIterator.java
> +                return peek();
проходит, теперь

2022-03-29 14:51 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +           return new InMemoryDao(config);
:disappointed: удалил

2022-03-29 15:08 UTC, AirBurn0 commented
> 

Теперь должны проходить. Как я понял, это связано с медленной конвертацией String в ByteBuffer и наоборот, немного изменил это

2022-03-30 16:03 UTC, incubos requested changes
Есть пара новых небольших замечаний. 1.2х после исправления за MBB.

2022-03-30 16:03 UTC, incubos commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +        if (data.isDirect()) {
Правильнее использовать метод `hasArray()`.

2022-03-30 16:03 UTC, incubos commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +            bytes = data.array();
Так нельзя делать в общем случае -- см. метод `arrayOffset()`.

2022-04-01 12:28 UTC, AirBurn0 commented on src/main/java/ru/mail/polis/test/baidiyarosan/ByteBufferDaoFactory.java
> +        if (data.isDirect()) {
Понял

2022-04-05 16:41 UTC, merged