Komissarov Gleb, Stage 3
polis-vk/2022-nosql-lsm pull request #89
Opened 2022-03-20 01:50 UTC by RalerCulte

2022-03-23 20:53 UTC, atimofeyev requested changes

2022-03-23 20:53 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileIterator.java
> +                MemoryAccess.getLongAtIndex(offsets, idx * 3),
что тут за волшебные числа?

2022-03-23 20:53 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +        throw new UnsupportedOperationException("Not implemented");
а почему UnsupportedOperationException?

2022-03-23 20:53 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +        lock.readLock().lock();
почему мы пишем под рид локом?

2022-03-23 20:53 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +            FileWorker reader = new FileWorker();
FileWorker можно оздать внутри ифа

2022-03-23 20:53 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +            if (result == null) {
как кстати можно отличить то что мы просто не нашли элемент в памяти или то что его просто удалили (вставили null)?

2022-03-23 21:10 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +            if (result == null) {
Когда entry удаляется, null только в значение value идет

2022-03-23 21:11 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +        throw new UnsupportedOperationException("Not implemented");
Пока, вроде, не требуется его реализация

2022-03-24 11:26 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileIterator.java
> +                MemoryAccess.getLongAtIndex(offsets, idx * 3),
Поправил

2022-03-24 11:27 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +        lock.readLock().lock();
Поправил

2022-03-24 11:27 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +            FileWorker reader = new FileWorker();
Поправил

2022-03-24 20:12 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/MyMemoryDao.java
> +            if (result == null) {
скип лист null вернет если и ничего не вставляли, и если удаляли

2022-03-25 21:06 UTC, atimofeyev requested changes

2022-03-25 21:06 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +                    return null;
не стоит так маскировать ошибку, IndexOutOfBoundsException указывает на явную ошибку в алгоритме или структуре файла

2022-03-25 21:06 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            createCurrentFiles(basePath, i);
в данном случае было бы более понятно если бы созданные файлы вернулись как результат выполнения, то что помещаются в поля объекта дает следующие минусы:
- во первых просто неявное их использование на местах и не понятно где они меняются
- во вторых, что более серьезно, это будет работать с ошибками при конкурентном чтении, потому что при ридлоке будет параллельное чтение, и два потока будут перезаписывать поля

2022-03-25 21:14 UTC, atimofeyev requested changes

2022-03-25 21:14 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            if (status == Status.LOWER) {
вот эти все status и mode только усложняют понимание кода, стоит попробовать сделать без них,
строго говоря не важно ищем мы один элемент или начало интервала, поиск должен просто вернуть позицию в которой мы нашли наш ключ или наиближайшуюю с которой стоит начать

2022-03-27 14:47 UTC, RalerCulte commented
Исправил предыдущие проблемы и изменил линейное слияние итераторов на логарифмическое

2022-04-01 19:12 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +        pathToEntries = basePath.resolve(FileName.SAVED_DATA.getName() + count);
Исправил

2022-04-01 19:12 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            createCurrentFiles(basePath, i);
Исправил

2022-04-01 19:12 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            if (status == Status.LOWER) {
Исправил

2022-04-01 21:21 UTC, atimofeyev requested changes

2022-04-01 21:21 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +        long millis = createFiles(basePath);
тут возвращаются nanos

2022-04-01 21:21 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +                iterator.add(new PeekIterator(Collections.emptyIterator(), i));
а зачем добавлять пустой итератор? Он же потом на первой итерации удалиться сразу

2022-04-01 21:21 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/RangeIterator.java
> +    private void reInsert() {
тут заметное дублирование кода с next(), хорошо бы переиспользовать код

2022-04-01 22:56 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/RangeIterator.java
> +    private void reInsert() {
Поправил

2022-04-01 22:57 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +                iterator.add(new PeekIterator(Collections.emptyIterator(), i));
Поправил

2022-04-01 22:57 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +        long millis = createFiles(basePath);
Поправил

2022-04-01 22:57 UTC, RalerCulte commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            files = null;
Поправил

2022-04-02 18:21 UTC, atimofeyev approved these changes

2022-04-02 18:21 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            e.printStackTrace();
здесь стоит прокинуть ошибку наверх и упасть

2022-04-02 18:21 UTC, atimofeyev commented on src/main/java/ru/mail/polis/glebkomissarov/FileWorker.java
> +            e.printStackTrace();
здесь тоже стоит прокинуть ошибку выше

2022-04-02 18:24 UTC, atimofeyev reviewed
18 + 9 баллов за MemorySegment

2022-04-04 10:04 UTC, merged