Stage3 - Bakin Daniil
polis-vk/2022-nosql-lsm pull request #91
Opened 2022-03-23 15:24 UTC by donebd

Second attempt, previous was infinity build

2022-03-27 11:40 UTC, atimofeyev requested changes

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapSerializeStream.java
>              ByteBuffer localBuffer = ByteBuffer.allocate(
можно было бы не выделять каждый раз новый буфер, в общем буффер для этого и нужен чтобы его переиспользовать

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            private final int size = endIndex;
лишнее забыкание на переменные в методе, лучше уж через обычный конструктор сделать, бьудет более понятный код

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            return null;
тот же вопрос про возможность такого состояния

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +        int position = (first + last) / 2;
возможное переполнение

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MergeIterator.java
> +            return getNext();
хорошо бы без рекурсии

2022-03-27 11:40 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/PersistentDao.java
> +        return storage.get(from, to, getInMemoryIterator(from,to));
Смотрится так что это обязанностью текущего дао объединять результаты инмемори и из стораджа.
Я бы не предавал в сторадж какой-то итератор, это размывает обязанности классов. Сторадж должен заниматься стораджем

2022-03-31 13:37 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +                mapData.add(mapChannel.map(FileChannel.MapMode.READ_ONLY, 0, mapChannel.size()));
На сколько я понимаю мы не помещаем даныне в память, а просто говорим о её синхронизации с местом в памяти. И помойму это является эталонной реализацией, которая была представлена на лекции

2022-03-31 21:30 UTC, atimofeyev requested changes

2022-03-31 21:30 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            Path mapPath = config.basePath().resolve(DATA_FILE_NAME + i);
Тогда стоит кинуть ошибку, а не тихо ее заглотить и далее работать некорректно

2022-03-31 21:30 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +        int position = (first + last) / 2;
а почему тут поправить не захотели?

2022-03-31 21:30 UTC, atimofeyev commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            private final int size = endIndex;
Здесь не согласны с замечанием?

2022-03-31 21:45 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            private final int size = endIndex;
А как в конструктор передать, в анонимный итератор? Или если его вынести то мне там нужен метод из некста, его как передать?

2022-03-31 21:47 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +        int position = (first + last) / 2;
ой, пропустил

2022-03-31 21:48 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +        int position = (first + last) / 2;
хотя нет не пропускал, точно исправлял, но что то куда то делось...
сейчас поправлю

2022-03-31 21:51 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            private final int size = endIndex;
Мне нужно будет ссылку на storage в конструктор давать чтобы дергать вот эти методы
return readEntry(getInternalIndexByOrder(next++, indexesBuffer), mapBuffer);

2022-03-31 21:59 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            Path mapPath = config.basePath().resolve(DATA_FILE_NAME + i);
Да, стоило бы, подумаю как решить

2022-03-31 22:26 UTC, donebd commented on src/main/java/ru/mail/polis/daniilbakin/MapsDeserializeStream.java
> +            private final int size = endIndex;
поправил

2022-04-01 19:28 UTC, donebd commented
Наверное можно мерджить, у меня все равно за этот стейдж 0 баллов.

2022-04-01 20:43 UTC, atimofeyev approved these changes

2022-04-01 20:46 UTC, atimofeyev reviewed
18 * 1.2 за MappedByteBuffer = 21 баллов

2022-04-04 10:02 UTC, merged