Galeev Artur Stage3
polis-vk/2022-nosql-lsm pull request #92
Opened 2022-03-23 17:46 UTC by coradead

2022-03-27 20:43 UTC, Artyomcool requested changes
Приведите код в порядок и уберите копипасту, чтобы я мог продолжить ревью.
Штраф в /10 за проглоченное исключение останется.

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +            );
не очень эстетично читается

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +    public class PriorityIterator<E> implements Iterator<E> {
зачем захватывать InMemoryDao#this ?

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +    public class PriorityIterator<E> implements Iterator<E> {
Переформулирую: почему класс нестатический?

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +                }
Вот так делать совсем-совсем не надо, обработка исключительных сиутаций не должна превращаться в один из способов возврата результата. Вероятно вам показалось, что это нормально, исходя из того, как я работал с файлами: там это обосновано производительснотью, это очень редкий случай и по возможности так делать не нужно.

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +                throw new IndexOutOfBoundsException();
NoSuchElementException

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +                e.printStackTrace();
Как обещал. Баллы снижаются в 10 раз.

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +                            throw new UncheckedIOException(e);
отличный повод не использовать stream api там, где в этом нет потребности.

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +                    .sorted(Comparator.comparing(p -> p.getFileName().toString()))
если файлов будет больше 10, вас ждёт сюрприз

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +    public class PeakingIterator implements Iterator<BaseEntry<ByteBuffer>> {
вас вообще не смутила копипаста?

2022-03-27 20:43 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/FileDBReader.java
> +    // protected because Im using for my local tests
package private будет достаточно

2022-03-29 21:29 UTC, coradead commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +            );
Постарался исправить

2022-03-29 21:30 UTC, coradead commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +    public class PriorityIterator<E> implements Iterator<E> {
Я собирался вынести в отдельный класс(я понимаю, что там много что надо было изменить и тд), но из-за того, что сдавал впритык - не успевал изменить, а после дедлайна побоялся

2022-03-29 21:30 UTC, coradead commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +                }
заменил обработкой null

2022-03-29 21:30 UTC, coradead commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +                throw new IndexOutOfBoundsException();
ok

2022-03-29 21:31 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +                            throw new UncheckedIOException(e);
избавился от лишнего try catch

2022-03-29 21:31 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +                    .sorted(Comparator.comparing(p -> p.getFileName().toString()))
Я этот вопрос еще в общий чат задавал, понял свою ошибку

2022-03-29 21:32 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/DBReader.java
> +    public class PeakingIterator implements Iterator<BaseEntry<ByteBuffer>> {
исправил, вынес в отдельный файл

2022-03-29 21:32 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/FileDBReader.java
> +    // protected because Im using for my local tests
ok

2022-03-31 13:40 UTC, Artyomcool requested changes
Уберите лишние изменения.
Затем, полный балл * 1.2, -2 балла за лишние аллокации.

2022-03-31 13:40 UTC, Artyomcool commented on src/main/java/ru/mail/polis/arturgaleev/InMemoryDao.java
> +        String[] temp = new File(String.valueOf(config.basePath())).list();
Лучше использовать апи Files.

2022-03-31 13:40 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/FileDBReader.java
> +            int result = getEntryByPos(mid).key().compareTo(key);
Очень много лишних аллокаций

2022-03-31 13:40 UTC, Artyomcool commented on src/test/java/ru/mail/polis/DaoTest.java
> +@Timeout(2115)
Нет

2022-03-31 13:40 UTC, Artyomcool commented on src/main/java/ru/mail/polis/Entry.java
> +public interface Entry<D> extends Serializable {
Нет.

2022-04-06 22:10 UTC, coradead commented
Там крч тесты запускаются для других дао.  Мне мб поднять week?  Прошлый коммит показывает, что все ок

2022-04-06 22:13 UTC, coradead commented
Я только что увидел, что можно запрашивать проверки

2022-04-11 14:44 UTC, Artyomcool requested changes

2022-04-11 14:44 UTC, Artyomcool commented on src/test/java/ru/mail/polis/BaseTest.java
> +import java.util.*;
Опять лишние изменения

2022-04-11 14:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/MergeIterator.java
> +                return -Integer.compare(it1.getPriority(), it2.getPriority());
Объяснял на занятии, почему так делать в общем случае не стоит.

2022-04-11 14:44 UTC, Artyomcool commented on src/main/java/ru/mail/polis/test/arturgaleev/MergeIterator.java
> +            if (it1.peek().key().compareTo(it2.peek().key()) < 0) {
Сравнение не бесплатно. Зачем делать его дважды?

2022-04-11 14:51 UTC, coradead commented on src/test/java/ru/mail/polis/BaseTest.java
> +import java.util.*;
Это автоматическая оптимизация идеи. Я борюсь с этим

2022-04-11 14:52 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/MergeIterator.java
> +                return -Integer.compare(it1.getPriority(), it2.getPriority());
Это занятие было после дедлайнов. В новых версиях это изменено

2022-04-11 14:54 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/MergeIterator.java
> +            if (it1.peek().key().compareTo(it2.peek().key()) < 0) {
Я уже исправил это в новых версиях

2022-04-11 20:49 UTC, coradead commented on src/test/java/ru/mail/polis/BaseTest.java
> +import java.util.*;
И в новых версиях уже все пофикшено

2022-04-11 20:49 UTC, coradead commented on src/main/java/ru/mail/polis/test/arturgaleev/MergeIterator.java
> +                return -Integer.compare(it1.getPriority(), it2.getPriority());
(в новых я перешел на сегменты)

2022-04-24 14:40 UTC, Artyomcool approved these changes
Полный балл 1.*2

2022-04-24 14:40 UTC, merged