Kondraev Dmitry, Stage 3
polis-vk/2022-nosql-lsm pull request #94
Opened 2022-03-23 20:29 UTC by mariohuq

`MemorySegment`, no r/w blocking

2022-03-25 09:52 UTC, incubos commented
Week 2, потому что до deadline тесты не проходили.

2022-03-31 21:43 UTC, mariohuq commented
Частично используется код @Artyomcool, но иначе организован, например, `MemorySegmentEntry`, merge iterator, filter iterator.

2022-04-01 21:23 UTC, atimofeyev requested changes
не проходят тесты

2022-04-09 13:36 UTC, atimofeyev requested changes

2022-04-09 14:21 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/SortedStringTable.java
> +        return ~low;
Побитовая инверсия гарантирует, что результат ≥0 получается тогда и только тогда, когда ключ нашелся.
Если сделать минус, то, если ключ будет меньше всех существующих, то метод вернёт -0 = 0, как если бы ключ был.

2022-04-09 14:22 UTC, mariohuq commented on src/main/java/ru/mail/polis/dmitrykondraev/FilesBackedDao.java
> +        map.clear();
Ок, исправлю

2022-04-09 17:19 UTC, atimofeyev commented on src/main/java/ru/mail/polis/dmitrykondraev/FilesBackedDao.java
> +        map.clear();
перечитал условие задачи, пока можно считать что во время флаша ничего больше непишем, так что для этого стейджа не важно

2022-04-09 17:20 UTC, atimofeyev approved these changes

2022-04-09 17:20 UTC, atimofeyev reviewed
27 балов, +50% за MemorySegment

2022-04-11 15:50 UTC, merged