Stage3
polis-vk/2022-nosql-lsm pull request #96
Opened 2022-03-23 20:45 UTC by Dmitree-Max

2022-03-27 17:02 UTC, incubos commented
Concurrent тесты флапают:
```
> Task :test

BasicConcurrentTest > testConcurrentRW_2_500(Dao) > ru.mail.polis.BasicConcurrentTest.testConcurrentRW_2_500(Dao)[1] FAILED
    java.util.concurrent.TimeoutException at TimeoutInvocation.java:70

BasicConcurrentTest > testConcurrentRead_8_000(Dao) > ru.mail.polis.BasicConcurrentTest.testConcurrentRead_8_000(Dao)[2] FAILED
    java.util.concurrent.TimeoutException at TimeoutInvocation.java:70

158 tests completed, 2 failed
```

2022-03-27 17:33 UTC, incubos requested changes
Есть ряд существенных замечаний к алгоритмической сложности реализации.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/NaturalOrderComparator.java
> +public class NaturalOrderComparator implements Comparator<MemorySegment> {
Имеет смысл завести singleton, потому что состояния нет.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentInMemoryDao.java
> +    private Path getLogName() {
Почему не просто `logs.size()`?

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentInMemoryDao.java
> +    private Entry<MemorySegment> checkLogForKey(MemorySegment log, MemorySegment key) {
Здесь реализован линейный поиск по файлу. Это неприемлемо на данном этапе.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    static class Source {
`private`?

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    public Entry<MemorySegment> next() {
См. контракт `Iterator.next()` в JavaDoc про `NoSuchElementException`.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    private Source peekIterator() {
Выбор `Source` для каждого элемента происходит за линию. Это не очень эффективно в случае большого количества файлов. Нужно за логарифм.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +                sources.get(0).element = sources.get(0).iterator.next();
Здесь протекает абстракция: метод неявно подразумевает, что перед ним вызвали `next()` и передали `key` из этого элемента -- верно? Нужно изменить логику и сделать её явной.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentInMemoryDao.java
> +    public Entry<MemorySegment> get(MemorySegment key) throws IOException {
Мы ведь можем использовать range `get()` и упростить код, выпилив `checkLogsForKey()`.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    static class FileEntryIterator implements Iterator<Entry<MemorySegment>> {
Здесь происходит позиционирование на начало диапазона за линию, что недостаточно эффективно на данном этапе.

2022-03-27 17:33 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +        public Entry<MemorySegment> next() {
Конструктор и этот метод имеют много общего -- нужно порефакторить.

2022-03-31 22:22 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/NaturalOrderComparator.java
> +public class NaturalOrderComparator implements Comparator<MemorySegment> {
исправил

2022-03-31 22:22 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentInMemoryDao.java
> +    private Entry<MemorySegment> checkLogForKey(MemorySegment log, MemorySegment key) {
исправил, теперь бинарный поиск

2022-03-31 22:23 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    private Source peekIterator() {
поправил. Выбор за константу, добавление за логарифм. Теперь использую мапу ключ-источник.

2022-03-31 22:25 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +                sources.get(0).element = sources.get(0).iterator.next();
Нет, мне кажется абстракция не протекала и честно двигала все итераторы с таким ключом, но этот кусок был переделан, так как теперь разрешение одинаковых ключей происходит на этапе добавление источника в мапу.

2022-03-31 22:25 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/MemorySegmentInMemoryDao.java
> +    public Entry<MemorySegment> get(MemorySegment key) throws IOException {
исправил

2022-03-31 22:25 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    static class FileEntryIterator implements Iterator<Entry<MemorySegment>> {
исправил, теперь бинарный поиск

2022-03-31 22:26 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +        public Entry<MemorySegment> next() {
поправил. Убрал дублирование кода

2022-03-31 22:26 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    static class Source {
поправил

2022-03-31 22:34 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    public Entry<MemorySegment> next() {
Поправил, теперь бросаем исключение если элементов больше нет.

2022-04-03 13:02 UTC, Dmitree-Max commented
The PR is ready. Up until previous wednesday the concurrent tests were unstable, but I made an optimization for the case where we have entries only in one source (in case of those test only from memory) and now tests pass fine.

2022-04-06 10:56 UTC, incubos commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    private Source peekIterator() {
Выбор из `TreeMap` тоже за логарифм. Ну да ладно.

2022-04-06 11:01 UTC, incubos approved these changes
1.5х за сегменты.

2022-04-06 11:02 UTC, merged

2022-04-06 11:54 UTC, Dmitree-Max commented on src/main/java/ru/mail/polis/dmitreemaximenko/BorderedIterator.java
> +    private Source peekIterator() {
используется только метод firstEntry()