Kovalenko Pavel, Stage 3
polis-vk/2022-nosql-lsm pull request #97
Opened 2022-03-23 20:57 UTC by PaaavelZ

2022-03-25 09:52 UTC, incubos commented
Week 2, потому что до deadline тесты не проходили.

2022-03-27 04:39 UTC, PaaavelZ commented
> Week 2, потому что до deadline тесты не проходили.

Всё верно, поставил

2022-03-27 04:40 UTC, PaaavelZ commented
Теперь тесты проходят. Код климат обещают снять, так что, наверно, мой PR готов к проверке.

2022-04-01 21:24 UTC, atimofeyev requested changes
Не проходят проверки, надо поправить

2022-04-04 16:43 UTC, PaaavelZ commented
@atimofeyev теперь все тесты проходят. Проверьте, пожалуйста.

2022-04-09 11:44 UTC, atimofeyev requested changes

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        dataFile.putChar(Utils.LINE_SEPARATOR);
и хдесь не понятен смысл LINE_SEPARATOR

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/EntryComparator.java
> +        if (keyCompare == 0 && (Utils.isTombstone(e1) || Utils.isTombstone(e2))) {
не понятно почему такое условие?оно же просто лишнее тут

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (sstables.size() != mappedSSTables.size()) {
1. в каком случае это может понядобиться?
2. надо старые замапленные файлы размапить
3. повмесеместно не хватает примитивов синхронизации, код получается не безопасным c точки зрения многопоточности

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/IteratorComparator.java
> +                compare = Integer.compare(it1.getPriority(), it2.getPriority());
приоритет должен же сортироваться в обратном порядке?

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.addAll(peekIterators);
зачем мы все итераторы перекладываем?

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.removeIf(this::removeIteratorIf);
а если следом опять могилка?

2022-04-09 11:44 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        PeekIterator<Entry<ByteBuffer>> second = iterators.poll();
зачем мы достаем два итератора?

2022-04-09 11:52 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        indexesFile.putChar(Utils.LINE_SEPARATOR);
Чтобы было удобно читать. Наверно, это лишние 2 байта, которые на миллион энтрей превращаются в 2 МБ. Уберу

2022-04-09 11:54 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/EntryComparator.java
> +        if (keyCompare == 0 && (Utils.isTombstone(e1) || Utils.isTombstone(e2))) {
Если у меня две могилки с равными ключами, то я должен сравнивать энтри уже по приоритету, которого здесь нет, поэтому отдаю это сравнение наоткуп caller'у. Не знал, как сделать иначе, можно по ключам тут compare возвращать, но извне логика будет ещё сложнее

2022-04-09 11:55 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.addAll(peekIterators);
Мы у них всех скипнули могилки, однако наша хипа их приоритет не поменяла. Делаем это за неё ручками

2022-04-09 12:34 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/EntryComparator.java
> +        if (keyCompare == 0 && (Utils.isTombstone(e1) || Utils.isTombstone(e2))) {
так если keyCompare  == 0 то в любом случае тут 0 вернется, в независимости от условия с могилками

2022-04-09 12:34 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.addAll(peekIterators);
а точно у всех? наверняка же только у некоторых, почему бы не перекладывать только тот итератор из которого достали ентрай

2022-04-09 12:34 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (sstables.size() != mappedSSTables.size()) {
1) я решил делегировать ответственность за выдачу приоритетного файла сериалайзеру, так что понадобится в случае, когда мы в мёрж итераторе даём FileIterator'ам те файлы, которые соответствуют их приоритету;
2) у MappedByteBuffer функция unmap приватная, он сам отвечает за свой размаппинг, мы на это повлиять не можем;
3) в stage3 ещё не обсуждается проблема многопоточности так остро, как в stage5, где всё вокруг неё крутится. Однако добавить несколько примитивов всё же не помешает

2022-04-09 12:41 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        PeekIterator<Entry<ByteBuffer>> second = iterators.poll();
Начнём с того, что хотя бы один итератор вытащить надо - нам надо что-то (iterators.remove()) с чем-то (iterators.peek()) сравнивать. Представим себе такую ситуацию, что первый итератор который мы вытащили - у него элементы 1 2, а у второго (который остался) - элементы 1 3. Когда мы пробросим через все итераторы значение 1, у первого итератора останется значение 2, у второго - 3. Когда мы вставим обратно наш итератор, голова нашей кучи не изменится, как бы мы ни пытались. В ней будет элемент 3, хотя приоритетным для нас будет элемент 2. Я не нашёл сему объяснения, но в результате наблюдений понял, что вытаскивать надо два итератора, чтобы такого не было.

2022-04-09 12:46 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/EntryComparator.java
> +        if (keyCompare == 0 && (Utils.isTombstone(e1) || Utils.isTombstone(e2))) {
Да, вы правы

2022-04-09 14:08 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        Path file = config.basePath().resolve(filename + (sstables.size() + 1) + Utils.FILE_EXTENSION);
такой подход ещё добавит гибкости в создании файлов, тут точно верное замечание

2022-04-09 14:49 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.addAll(peekIterators);
Точно у всех. С могилками я прыгаю по каждой паре итераторов (от наиболее проритетных к наименее приоритетным) и у них у всех с помощью функции fallEntry пробрасываю энтрю, если она могилка. Рассмотрим также на примере:
Пусть у нас коллекция из 3 итераторов - 1: 1 3, 2: 1 3, 3: 1 2 (приоритет соответствующий). Пусть единичка - могилка. Тогда после первого пробрасывания имеем: 1: 3, 2: 3, 3: 2. На лицо нарушение порядка в третьем итераторе (теперь он должен быть самым приоритетным из всех). А может быть и в пятом.
Раз мы трогаем все итераторы, то менять порядок надо тоже относительно всех итераторов.
![image](https://user-images.githubusercontent.com/76079492/162579097-8b5b4561-1524-4084-a31f-2aa9f8f8873e.png)
![image](https://user-images.githubusercontent.com/76079492/162579241-9261f22a-bf18-4085-914d-799bdb2476d0.png)

2022-04-09 16:30 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (sstables.size() != mappedSSTables.size()) {
2. ну почему же, есть возможность явного вызова, правда через ансейф, просто иначе это будет делаться в непонятное время , в общем я так понял вы должны были что-то подобное проходить на курсе, или все одинакого гуглят )

2022-04-09 16:31 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        PeekIterator<Entry<ByteBuffer>> second = iterators.poll();
почему же голова кучи не изменится?

2022-04-09 16:33 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.removeIf(this::removeIteratorIf);
тут я больше намекаю на то что стоит сделать более общее решение

2022-04-09 16:40 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (sstables.size() != mappedSSTables.size()) {
Я даже сразу о рефлексии не подумал. Так вот, где она используется! Попробую)

2022-04-10 07:38 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        serializer.write(sstables.lastEntry().getValue(), memorySSTable);
Теперь создаю новую пару файлов непосредственно в Serializer.write

2022-04-10 07:41 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.addAll(peekIterators);
Теперь в fallEntry записываю, какие итераторы я пробросил, организую трансфер этого списка итераторов туда, где они рефрешаться, и уже удаляю не все итераторы, а только те, что были затронуты. Хорошая микрооптимизация

2022-04-10 07:50 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        PeekIterator<Entry<ByteBuffer>> second = iterators.poll();
Вероятно, я как-то странно отлаживал. Теперь не достаю тут итераторы, но с тем условием, что раз я тут выполняю fallEntry, то после этой операции я должен достать изменившиеся итераторы и засунуть их обратно в кучу (чуть выше пояснил за этот момент).

2022-04-10 08:44 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/IteratorComparator.java
> +                compare = Integer.compare(it1.getPriority(), it2.getPriority());
Верно, но в IteratorComparator используется в MergeIterator, а там мы уже имеем те приоритеты, что нам нужны, благодаря методу get(int priority) у Serializer. Как видно, он достаёт (size - priority), то есть приоритетные итераторы идут с конца. Чуть выше писал, что делегировал ему выдачу итераторов
![image](https://user-images.githubusercontent.com/76079492/162610151-d50ed3da-c914-4b30-b99d-bc29701ab2df.png)
![image](https://user-images.githubusercontent.com/76079492/162610205-60bb0277-63a7-4afc-bae6-9fdcfebde786.png)

2022-04-10 08:49 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/IteratorComparator.java
> +                compare = Integer.compare(it1.getPriority(), it2.getPriority());
Однако вижу нарушение Single Resposibility. Вы правы, переношу это логику в IteratorComparator

2022-04-10 09:25 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/comparators/IteratorComparator.java
> +                compare = Integer.compare(it1.getPriority(), it2.getPriority());
Всё бы ничего, но у меня тогда нарушится вся моя логика, если я поставлю здесь reverse compare. У меня у итератора на мапу приоритет = 0, это самый приоритетный итератор. После него с priority = 1 идёт итератор на самый последний записанный файл, priority = 2 - итератор на (n-1) файл, и так далее. Я всё же решил соблюсти такой инвариант, что чем меньше приоритет, тем приоритетнее становится итератор. Логику "выборки" итератора я перенёс в MergeIterator.

2022-04-12 21:39 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +        iterators.removeIf(this::removeIteratorIf);
Если итератор один в очереди, то такого точно не случится - мы в цикле бегаем и смотрим, чтобы у него не было могилки. Если итераторов несколько, можно усовершенствовать метод backIterator, чтобы он клал в очередь только те итераторы, у которых гарантированно есть следующий элемент. Таким образом у самого приоритетного для нас итератора всегда будет следующий элемент, который не будет могилкой (мы в цикле смотрим по iterator.peek()), либо же итераторов не будет вовсе.

2022-04-13 21:06 UTC, atimofeyev requested changes

2022-04-13 21:06 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            int compare = Utils.entryComparator.compare(first.peek(), second.peek());
не понимаю зачем мы тут сравниваем два итератора, это же задача приорити очереди вернуть нам итератор с наименьшим ключем

2022-04-13 21:06 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +    private void backIterator(PeekIterator<Entry<ByteBuffer>> it) {
такие методы только запутывают логику, было бы понятнее если там где он вызывается и делалось iterators.add(it)

2022-04-14 02:53 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
У нас канкаркет коллекция, она внутри сама напичкана примитивами синхронизации

2022-04-14 02:55 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (!Files.exists(file)) {
1) вместо rename можно делать move
2) про завязку на состояниях согласен, было бы понятней, если бы addFile возвращал файл, который он добавил, а addPairedFiles вообще бы не было

2022-04-14 02:56 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            int compare = Utils.entryComparator.compare(first.peek(), second.peek());
Мы итераторы сравниваем комплексно для нашей очереди итераторов. А что, если у первого итератора приоритет 1, у второго 2, но у первого итератора первый элемент это key10, а у второго - это key2? Тогда второй будет приоритетнее.

2022-04-14 07:22 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +    private void backIterator(PeekIterator<Entry<ByteBuffer>> it) {
Удалил такие методы

2022-04-14 07:47 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/Serializer.java
> +        if (!Files.exists(file)) {
исправлено

2022-04-14 07:57 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            int compare = Utils.entryComparator.compare(first.peek(), second.peek());
Это очень верное замечание. После того, как я сделал общее решение, все эти проверки разом стали ненужными. Спасибо Вам большое!

2022-04-14 08:07 UTC, PaaavelZ commented
Все замечания исправлены

2022-04-14 08:17 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
Точно, подумал про то, что у нас канкарент коллекция сама с этим справится, но извне нам тоже надо контролировать все наши процессы. Так что он тут нужен, добавил

2022-04-14 08:24 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
У нас же канкарент коллекция, она внутри сама регулирует вставку. Все элементы вставятся. А извне я не вижу причин, зачем нам это регулировать - в дальнейшем мы же будем брать "слепки" нашей базы на некоторый промежуток времени, и если после совершения снэпшота у нас продолжилась запись, то мы её не учтём, что в порядке вещей

2022-04-16 05:43 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
в дальнейшем стейдже я думаю увидим проблемы, то что мапа сама по себе потокобезопасная, не делает безопасным работу с ней. 
Например после компакшена мы очищаем мапу, и вот в промежутке между компакшеном и очисткой мы спокойно можем вставить в мапу новый элемент, и он не успеет попасть в скомпакченный файл и будет удален из мапы

2022-04-16 05:51 UTC, atimofeyev requested changes

2022-04-16 05:51 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            first = iterators.poll();
а для чего тут мы достаем два итератора? и почему мы сначала вставляем в очередь итератор с могилкой, а потом его удаляем, нарушется же сортировка

2022-04-16 12:22 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
Действительно, подправлю

2022-04-16 12:49 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            first = iterators.poll();
И вправду, выходит несвязно как-то всё. Упростил эту логику. К тому же, итераторы и без того достаются в fallAndRefresh, так что смысла их доставать по-новой не вижу.

2022-04-16 13:00 UTC, PaaavelZ commented on src/main/java/ru/mail/polis/pavelkovalenko/PersistentDao.java
> +        memorySSTable.put(entry.key(), entry);
Учту Ваши замечания в stage5. На текущих канкарент-тестах локи тормозят программу, из-за чего тесты про ходят (там 10к апсертов одновременно).

2022-04-16 21:09 UTC, atimofeyev approved these changes

2022-04-16 21:09 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            if (it.hasNext()) {
для чего мы тут собираем список и потом его разом удаляем, посечму бы это сразу не делать с очередью? По моему было бы проще и не хуже по эффективности

2022-04-16 21:15 UTC, atimofeyev commented on src/main/java/ru/mail/polis/pavelkovalenko/iterators/MergeIterator.java
> +            if (it.hasNext()) {
18 баллов

2022-04-16 21:29 UTC, closed without merging